### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Yachtsman** [mysociety/fixmystreet#1006]
Hello,

Please add the Russian language to repository.

Thanks!

**Comment by dracos** [comment]
Hi @Yachtsman – we are very happy to accept a Russian translation if you are able to provide one :) You can either translate the `.po` file directly, if you know what that means, or we are available on Transifex at http://transifex.com/projects/p/fixmystreet/ – that already has an empty Russian translation, I see.

**Comment by dracos** [comment]
I should add that if you're running the latest code, you only need to translate the v1.5 resource which matches the latest version of the code. Please feel free to join and ask questions on our mailing list, http://fixmystreet.org/community/ has details.

**Comment by Yachtsman** [comment]
@dracos I'm translating it in Transifex and have to see the changes in interface.
Thank you for your help here.

**Comment by dracos** [comment]
@Yachtsman Great! Sorry, I'm not sure what you mean – are you asking for help in seeing your translation in your own installation, or are you okay for the moment?

**Comment by Yachtsman** [comment]
I'm OK for now. Thank you again.

**Comment by guland2000** [comment]
Please, help me find .po files (and other files) to translate Russian language.
I see only [FixMyStreet.po](https://github.com/mysociety/fixmystreet/blob/master/locale/ru.UTF-8/LC_MESSAGES/FixMyStreet.po) as i understood it must be more... for FAQ,category (reports about) and so on ?!

**Comment by dracos** [comment]
The documentation for customising the language can be found at https://fixmystreet.org/customising/language/ - see under "Contributing a translation", which includes the .po file, how to translate static files such as the FAQ, and how to translate categories, body names and report states. Hope that's helpful.
