### ISSUE TITLE
Set up FixMyStreet for Alcantarilla, Murcia

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet#1012]
Set up a vanilla version of FixMyStreet for Alcantarilla in Murcia, Spain.

They would like:
- [x] Grey and Yellow similar to the UK site
- [x]  Site name is : arreglamibarrio.org (Domain name already bought)
- [x] DNS updates for the above once @flupsy picks server etc
- [x] This administrative area from OSM: http://www.openstreetmap.org/relation/345087 
- [x] Attached logo 
![arreglamibarriofb](https://cloud.githubusercontent.com/assets/4170351/5998722/81cef66a-aac2-11e4-9f1f-6329e181212b.jpg)
- [x] @JenMySoc has xls of categories and email addresses associated with them

They've started the translation into Spanish already. Please let me know what other information you need for this! If possible if this is a quick job could this be added to the sprint w/c 2nd Feb?

**Comment by Flupsy** [comment]
Let's put it on pluto.

**Comment by dracos** [comment]
The site is deployed at arreglamibarrio.fixmystreet.com, with that logo. That OSM boundary isn't in global mapit (it was broken in the past, after I investigated), so I've taken a copy to our international mapit instead, that's fine, and seems to be working. So still need:
- [ ] DNS set up for real domain
- [ ] contact email address for the site itself. I've put Jen for now.
- [ ] FAQ page, in Spanish presumably? Errors as no Spanish FAQ present.
- [ ] The bodies can be set up in the admin, which is working (in Spanish)

**Comment by Flupsy** [comment]
@JenMysoc can you ask the domain owners to make the same changes as for the Nicaragua domain?  I'll create the zone at our end.

**Comment by Flupsy** [comment]
Zone & alias files created.

**Comment by JenMysoc** [comment]
Email sent with these details and the DNS changes :)

**Comment by JenMysoc** [comment]
Contact email address: incidencias@ocmalcantarilla.es

DNS has been changed

They're finishing off the FAQ page now, do we have a format we want that sent over in @dracos ?

**Comment by Flupsy** [comment]
DNS bit done.

**Comment by dracos** [comment]
"do we have a format we want that sent over in" – in the same format as the English HTML page would be perfect (ie. HTML, like https://github.com/mysociety/fixmystreet/blob/master/templates/web/base/faq/faq-en-gb.html ), but we can HTMLify it if not.

**Comment by fcoasensio** [comment]
We thought it would be better a larger population. It is pretty expand territory with only one municipality morePlease, you can extend the administrative area?? http://www.openstreetmap.org/relation/340611
