### ISSUE TITLE
send-reports and send-alerts are hard on the database

### ISSUE THREAD

**Issue by Flupsy** [mysociety/fixmystreet#1017]
This isn't necessarily a problem that can be solved, but I've noticed that `send-reports` in particular is very CPU-intensive on the database.  Is there an index that could be added, or anything else that could be done, to optimise the queries?

**Comment by Flupsy** [comment]
All the queries in the slow query log look like

`select problem.id, problem.bodies_str, problem.postcode, problem.geocode, problem.title from problem_find_nearby($1, $2, $3) as nearby, problem, users`

**Comment by dracos** [comment]
Thanks. That's a query from `send-alerts`, not `send-reports`, did you mean `send-alerts` in the issue description?

Taking the 8am run of `send-alerts`, I think it makes c. 5000 queries of that type, of which 56 get in the slow query log. Takes under half an hour to run, so is doing on average 3 a second. Is it constant usage for the time the script is running? Something at start/end? It's only meant to be looking at problems from the past week, but I'm not sure it's doing that first off (ie. it's not doing things in the "right" order to save itself effort), so I'm sure it can be improved.

**Comment by dracos** [comment]
This might be helped by #1178

**Comment by Flupsy** [comment]
https://secure.mysociety.org/admin/cacti/graph.php?action=view&rra_id=all&local_graph_id=993 says it all -- problem solved!

**Comment by dracos** [comment]
![graph_image php](https://cloud.githubusercontent.com/assets/154364/9193133/0487c038-4009-11e5-9691-94a31496800a.png)

**Comment by dracos** [comment]
Also #1182 and probably #1185.
