### ISSUE TITLE
[BUG] in the time calculated for ( sent to *** from ** ) in report page

### ISSUE THREAD

**Issue by MohHeader** [mysociety/fixmystreet#1025]
Please check the following page for example : 
https://www.fixmystreet.com/report/9468

Although it is reported on Sun 7 October 2007 
it is listing that : 
Sent to Tandridge District Council less than a minute later

Thanks,

**Comment by MohHeader** [comment]
Ok,
Looks strange, But I checked the code : 
````
Utils::prettify_duration($problem->whensent->epoch - $problem->confirmed->epoch, 'minute')
````
Does that mean that the time is considered by the difference between ( time of sent, time of received )
hmmm, I think if so, it needs some sort of re-wording ( or may be not :) )

Thanks,

**Comment by dracos** [comment]
Hi @MohHeader, thanks for your report. What that text means is that the report was confirmed by the user at 19:09 on 2007-10-07, and that we sent it to Tandridge Council at 19:10 on 2007-10-07, ie. "less than a minute later". Sometimes we might have problems sending the report on to the council, and so we show the time difference, though normally it will always be within five minutes or so. This seems clear enough to me, and yours is the first report I'm aware of concerning this text – what did you think it meant?

**Comment by MohHeader** [comment]
Hi @dracos , 
I got your point, It is my bad.

BTW: FixMyStreet is a great OS platform, Thanks for maintaining it. :+1: 
Thanks,
