### ISSUE TITLE
Poster for windows

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1028]
Discussion was provoked by this poster (seen on Facebook) https://drive.google.com/file/d/0B_rp9EM3A2vpTEphRmpiZlJkNkE/view

We could do something similar for our downloads page, but it was agreed that we'd prefer something less 'creepy' - maybe:
- 'Our kids play in this street: please keep it poo-free'
- 'We love our street; please don't let your dog poop here'
- 'No-one likes poops - please scoop!' etc etc

Or maybe even a series of posters with different messages. Refreshing the downloads page would also be a good excuse to blog and tweet about them again.

Martin remarked that this might be a good 'end of Friday' task to fill an odd hour (which maybe should become a category?)

**Comment by wrightmartin** [comment]
Here's an intimal idea

![fms-poop-poster](https://cloud.githubusercontent.com/assets/2292925/6596051/6509f668-c7e8-11e4-9ef7-9e1b7446d044.png)

**Comment by MyfanwyNixon** [comment]
It's great.

I'm just wondering slightly about 'spotted some poop? etc'. 
Maybe 'Let's keep our street poop-free - report persistent problems with FMS'

Small point, though.

**Comment by wrightmartin** [comment]
![fms-poop-poster](https://cloud.githubusercontent.com/assets/2292925/6616835/5f61d0ec-c8aa-11e4-98e1-4314163a759a.png)

**Comment by MyfanwyNixon** [comment]
:+1:

**Comment by MyfanwyNixon** [comment]
and of course :poop:

**Comment by MyfanwyNixon** [comment]
Bumping up - can we get this poster added to https://www.fixmystreet.com/posters please?

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/fixmystreet/pull/1097

**Comment by MyfanwyNixon** [comment]
I think the page has lost a subheading. Didn't it use to say 'graphics' above: 
> Ideal for promoting FixMyStreet in your community newsletter or local magazine. Specially designed to stand out, and get your message across

**Comment by zarino** [comment]
@MyfanwyNixon: According to the [file history on GitHub](https://github.com/mysociety/fixmystreet/commits/master/templates/web/fixmystreet.com/static/posters.html), it's said "Pre-made Adverts" since I created the page last November.

![screen shot 2015-04-24 at 10 50 26](https://cloud.githubusercontent.com/assets/739624/7316551/c19d25c2-ea6f-11e4-8251-e5307b5a35bd.png)

**Comment by MyfanwyNixon** [comment]
Oh, that's fine - it just doesn't say anything at the moment.

**Comment by zarino** [comment]
Oh!? It does when I visit it (that screenshot above is one I took a few minutes ago).

Which browser are you using?

**Comment by MyfanwyNixon** [comment]
Firefox!

**Comment by dracos** [comment]
Has a heading here in FF31.

**Comment by MyfanwyNixon** [comment]
I'm on 37.0.2

![fireshot screen capture 099 - promote fixmystreet with our free goodies_ posters flyers and kids activity packs __ fixmystreet - www_fixmystreet_com_posters](https://cloud.githubusercontent.com/assets/944656/7317068/64495972-ea74-11e4-85e6-ba9090f8cc66.png)
