### ISSUE TITLE
Investigate time cost for pulling PorMiBarrio changes into main FMS branch

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet#1032]
Code repo is at https://github.com/datauy/fixmystreet and we should also contact @fernandouval to let him know if we're planning on pulling in changes (@JenMySoc can do this)

**Comment by fernandouval** [comment]
I'm aware of that Jen :). There is still some changes I have to upload, I asume that late in March everithing will be uploaded. Still a cost estimation would be very welcome, and we might be able to help with that and implementation.

Please let me know anything you need.

**Comment by dracos** [comment]
Here's a starter list of the main functional changes not yet present upstream:
* Facebook/Twitter login
* Optional identity document field for user, with validation
* Category groups (used for e.g. pin icon choice)
* User photo
* List update alerts on /my page
* More edit user stuff on /my
* Possible option of deleting your own report, if I've understood that right
* Scrolling (to an error?) during report/update creation
* Option to resend problems when update reopens
* Public stats page with graphs
* More data passed to front end, including category, state, username etc
* Pin colour based on more data, including e.g. category/group/state
* Open311 - some form of timezone fix? Plus other testing.

And of course:
* The front end design/JavaScript changes – currently some templates are duplicated, so I haven't broken that down yet into whether any bits of this could be shared upstream, but as this is all in the cobrand this is less of a shared issue, assuming any core functional things are included. It would be good for this to be included as an example of a much different design, of course, along with documentation on how it can be used.

**Comment by dracos** [comment]
Closing this as the list exists, and can open tickets for other things as they are wanted. Social login was #1146, public stats are #1330.
