### ISSUE TITLE
FixMyStreet account management: “How do I change my password?”

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#1034]
Most sites have an account management screen or menu, that lets users:

* Change their password
* Change their full name
* Change their username / email address (sometimes!)
* View all content created by them
* Manage their email subscriptions

The most common user support request for FixMyStreet is helping people change their password (especially in the wake of security scares like Heartbleed). The link to change your password is currently hidden on the “Your reports” page, because there is no user menu / account management page.

I suggest we add a user management page, so the workflow matches people’s expectations.

**Comment by abimysoc** [comment]
We're also seeing the occasional "how do I _create_ an account?" support enquiry, I think because https://www.fixmystreet.com/auth?r=my doesn't look like a typical account creation screen/workflow.

**Comment by dracos** [comment]
Comment going to be done in #642, change email/your account done by #1350 and after.
