### ISSUE TITLE
Set Up FixMyStreet for Uganda

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet#1037]
As part of an indigo funded project we need to set up a version of FixMyStreet for Uganda

I still need to get some details from the group but so far we have:

- [x] Name of the site: FixMyCommunity
- [x] Domain name; http://fixmycommunity.ug/ (already registered)

I need to get:
- [x] Administrative boundary data, which you can find normally on OpenStreetMap
- [ ] Problem categories and the email addresses for the council or local authority where the problems for each category can be reported.  
- [x] Site colours and Logo

**Comment by JenMysoc** [comment]
From Emmanuel: 

"Here is the Boundary information
Kasese   http://www.openstreetmap.org/relation/3501895
Kayunga http://www.openstreetmap.org/relation/3498104
Soroti http://www.openstreetmap.org/relation/3497400#map=10/1.7907/33.6024
Gulu http://www.openstreetmap.org/relation/3497245
Moyo http://www.openstreetmap.org/relation/3501824#map=10/3.4887/31.7127

For the colours to use for the Logo, Black, Orange and White would do."

By logo I think he means site, and keeping the same logo. Are we all ok with this?

**Comment by dracos** [comment]
Assuming this was all done!
