### ISSUE TITLE
extend the administrative area

### ISSUE THREAD

**Issue by fcoasensio** [mysociety/fixmystreet#1046]
Please, you can extend the administrative area? http://www.openstreetmap.org/relation/340611

**Comment by fcoasensio** [comment]
We thought it would be better a larger population. It is pretty expand territory with only one municipality more. Please, you can extend the administrative area??

**Comment by dracos** [comment]
I have added that area to the admin interface, so you can associate your Ayuntamiento de Alcantarilla body with both areas (you may need to hold down "Control", or "Command" on a Mac, to select more than one area). You could also unset the "parent", you don't need to set that to anything.
