### ISSUE TITLE
ArreglamiBarrio having a search issue on the maps

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet#1067]
The message from Francisco reads:

Actualmente hay dos zonas (Alcantarilla y Murcia). Todas las busquedas aunque sean de Murcia me focalizan el mapa de Alcantarilla. Igualmente, las propuestas que ofrece tras la busqueda aparecen todas en relación a Alcantarilla.

Which basically says:

At the moment there are two zones (Alcantarilla and Murcia). All the searches, even if they're for Murcia, focus me on the map of Alcantarilla. In the same manner, the suggestions that are offered for search all appear in relation to Alcantarilla.

**Comment by dracos** [comment]
I've updated the search to use "Murcia" rather than "Alcantarilla" as it was; hopefully this will be a good enough improvement!
