### ISSUE TITLE
DMARC causing issues with some councils

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1070]
e.g. Sedgemoor:

    SMTP error from remote mail server after end of data:
    host cluster8.eu.messagelabs.com [85.158.140.211]:
    553-DMARC domain authentication fail. Refer to the
    553-Troubleshooting page at http://www.symanteccloud.com/tro
    553 ubleshooting for more information. (#5.7.1)

**Comment by abimysoc** [comment]
Kingston

**Comment by abimysoc** [comment]
Warwickshire (cc @BenJam because that's a commercial client).

**Comment by abimysoc** [comment]
North Devon

**Comment by abimysoc** [comment]
Sutton

**Comment by Gemmamysoc** [comment]
Haringey

**Comment by Gemmamysoc** [comment]
Sedgemoor District Council

**Comment by abimysoc** [comment]
Tower Hamlets

**Comment by abimysoc** [comment]
Cambridgeshire
