### ISSUE TITLE
Enable 'quote_names' in dbic connection args

### ISSUE THREAD

**Issue by osfameron** [mysociety/fixmystreet#1084]
This setting would allow us to join to the users table without generating invalid SQL like `JOIN users user` as `user` is a reserved word.

It's not possible to simply add this, as I discovered, because there is various literal SQL that isn't correctly escaped.  Also quoting searches which _should_ work has some oddities, e.g. https://gist.githubusercontent.com/osfameron/104bb2d98879bf0b8616/raw/61d08c7ccc9982f36fe8342369607fa49c9b3be4/gistfile1.txt

There are some individual workarounds scattered around code, e.g.:
- NOT joining users
- manually setting the quote_name before doing something, then trying to roll back

The first makes me sad, and the 2nd is overly tricky and according to #dbix-class may be hard to properly localise so risks subtle bugs. Worth spending a bit of time to test and refactor this properly.

**Comment by racke** [comment]
We have a related problem in https://github.com/interchange/TableEditor/issues/64, so I also would be interested in a possible solution.
