### ISSUE TITLE
Possible DBIx::Class upgrade issue will break RABX column inflation in near-future

### ISSUE THREAD

**Issue by osfameron** [mysociety/fixmystreet#1088]
Discovered that Zurich staging was failing to update extra columns.  This test script confirmed:

```
use FixMyStreet::App;

my $c = FixMyStreet::App->new();

my $category = $c->model('DB::Contact')->search(undef, { rows => 1 })->single;
$category->set_extra_metadata( testing_foo => 1 );
$category->update;

$category->discard_changes;
say $category->id;
say Dumper($category->get_extra);
# returned empty hash: {}
```

DBIC on local was version  '0.08270', while staging had '0.082820'.  Looks like I'd made an error while updating modules on staging.  Blowing away `local/` and rebuilding fixes above test.

Looking at `FixMyStreet::DB::RABX`, it looks like the `filter_from_storage` routine didn't get passed $ser.  There are changes in https://metacpan.org/changes/distribution/DBIx-Class relating to FilterColumn, so I suspect we have a regression coming up soon.  (At least it's worth checking.)

**Comment by dracos** [comment]
This is a rather serious bug in DBIx::Class which I reported http://lists.scsys.co.uk/pipermail/dbix-class/2015-June/012057.html - "if you set a filtered column more than once before saving it, the
data is lost when saved".

**Comment by dracos** [comment]
We upgraded a long time ago now, this was sorted.
