### ISSUE TITLE
Follow-up "questionnaire" email could be much better

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#1103]
The email currently:

* Doesn't tell you where the problem was
* Doesn't show you the picture you uploaded with the report
* Requires you to load a page in your web browser and complete a whole form

The email *could* instead:

* Show you the location of the problem on a map (see https://github.com/mysociety/fixmystreet/commit/caa28b8701ff8de8d98ae98fbf133db0be8141c8 for example of embedding map in email)
* Show you your picture of the report, so you can differentiate it from others you might have reported around the same time
* Give you simple "Yes" and "No" buttons (like WriteToThem)

**Comment by Gemmamysoc** [comment]
From user feedback it would also be good to state on the email that responses to questionnaire can be made anonymously.

**Comment by zarino** [comment]
This ticket as it stands requires very little designer time. However, if we're adding an image or a map to the email, it would be a shame not to also give the email a HTML part, like the Collideoscope batched report emails.
