### ISSUE TITLE
Questionnaire page hides the report details

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#1104]
If you've come to the Questionnaire page via the link in the email, chances are you won't immediately know which report you're being asked to evaluate. Especially if you're a heavy user and your report titles are generic like "Flytipped mattress" or "Pothole".

The Questionnaire page, by default, doesn't give you a single clue as to which report we're asking you about.

To see the report details, you have to click the "Your report" tab – which @paulfurley didn't notice until I studied the page with him a second time.

![screenshot from 2015-05-01 14 18 39](https://cloud.githubusercontent.com/assets/739624/7430844/07779668-f010-11e4-931a-b26362fedce8.png)

Could we find a way of putting the report details right there, next to or above the questionnaire form, so you can see them both at the same time?

**Comment by dracos** [comment]
Yeah, not great. FWIW, the old (pre-full page map) design did have the questionnaire in the left column, map/report details on the right, this was lost in the move to the full page map design.

**Comment by kim07** [comment]
:+1:

**Comment by wrightmartin** [comment]
Here's a quick, not really thought through change to this form

![questionnaire](https://cloud.githubusercontent.com/assets/2292925/9335391/a37df4a6-45cb-11e5-8893-d1d516d67bef.png)

**Comment by zarino** [comment]
:+1: Exactly what I was imagining. Although with the addition, probably, of a "Show full report" link next to the report preview, in case I want to remind myself of the report in full. Or potentially just make the report title clickable.

**Comment by dracos** [comment]
Nice :) The only thing I'd suggest (already discussed in person) is that we probably need in some way to show update/updates if there are any, because they might be of relevance in deciding the answer to the questionnaire. Perhaps last update/updates in some form of scrolling box, or "updates since last questionnaire" even, that shouldn't be too hard.

**Comment by wrightmartin** [comment]
This latest design adds the most recent updates to the report embed. Over to you @zarino 

![questionnaire](https://cloud.githubusercontent.com/assets/2292925/9354369/c4064a10-4667-11e5-8ff2-9504963a21a2.png)

**Comment by zarino** [comment]
I've started this in a branch called [#1104-questionnaire-form-design](https://github.com/mysociety/fixmystreet/compare/issues/%231104-questionnaire-form-design).

Progress so far:

- [x] Remove tabs
- [x] Add "Your report" summary in grey box, with photo, title, meta info
- [ ] Show latest update for report
- [ ] Make the radio buttons look like big clickable segmented buttons

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/fixmystreet/pull/1200
