### ISSUE TITLE
Twitter share button missing on Firefox

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1124]
I can see it on Chrome but not on Firefox!

Firefox: 
![notweetbutton](https://cloud.githubusercontent.com/assets/944656/8155662/346aeb92-133e-11e5-9dbf-a4db5f25202d.png)

Chrome:
![yestweetbutton](https://cloud.githubusercontent.com/assets/944656/8155682/6a474e68-133e-11e5-8d9e-1b571f4e7a21.png)

**Comment by MyfanwyNixon** [comment]
Still happening! Have checked on my desktop as well as laptop.

**Comment by dracos** [comment]
The code is there and it's created the button, it's just set to invisible with zero width. Have reduced it to just a hidden div on load, it just doesn't display then: http://dracos.co.uk/temp/hidden-twitter-button-2015-07-28/ – not sure if there's any workaround.

**Comment by dracos** [comment]
This was fixed in 03ad5de783ac71695b1ce0d377dde549fc7311cb
