### ISSUE TITLE
Add warning of bounceback to confirmation emails (Ealing)

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/fixmystreet#1128]
This is what Ealing has told us:

"If requests are sent through to the customer_services mailbox from yourselves they will receive a bounceback but will be actioned. However, the turnaround time will be slower than a customer reporting the issue via the appropriate web form on our website."

Could we add a warning of this to the confirmation emails users receive when sending reports to Ealing?

**Comment by Gemmamysoc** [comment]
Bounceback from Ealing:

This mailbox is now closed and your email will not be responded to.
 
The fastest way to access council services is via our website
 
Please use one of the following links to contact us depending on your enquiry:
 
Report a missed refuse or recycling collection: www.ealing.gov.uk/missedcollection
 
Order new recycling containers: www.ealing.gov.uk/recyclingcontainer ( Customers who either live in a flat or along a red route need to call 020 8825 6000 to order recycling containers.)
 
Subscribe to the Garden Waste Collection Service: www.ealing.gov.uk/gardenwastesubscribe
 
Report a variety of issues or request services through our online forms: www.ealing.gov.uk/reportit
 
Find out more about online services: www.ealing.gov.uk/doit
 
If your enquiry is regarding an FOI request please send your email to FOIRequests@ealing.gov.uk
 
If you cannot find the service you wish to access online, please contact us on 020 8825 6000
 
Kind Regards
 
Customer Services
 
Ealing Council

**Comment by abimysoc** [comment]
This is now out of date and Ealing are currently set to REFUSED pending them providing us with any email address at all to use (the customer services one is now closed).
