### ISSUE TITLE
Grey overlay on Map when using GoogleMap as map service

### ISSUE THREAD

**Issue by vannenc** [mysociety/fixmystreet#1133]
![sans titre](https://cloud.githubusercontent.com/assets/2804514/8306930/c786a8e6-19cc-11e5-89b9-803cf8dad8b5.png)
The map view is completely black when using GoogleOL as map type. It happens only with GoogleOL. The map view remains black until I scroll on it.

Any idea how to fix this?

**Comment by akuckartz** [comment]
Can OpenStreetMap be used instead ?

**Comment by vannenc** [comment]
I like Google map better and it seems more accurate in the regions I would be using it.

**Comment by dracos** [comment]
I have no idea why this works, but if you don't mind the Satellite view being the default, then the following diff will allow the map to work from the page load, and switch correctly Map/Satellite:

```diff
diff --git a/templates/web/base/maps/google-ol.html b/templates/web/base/maps/google-ol.html
index 919ae07..ce22fc9 100644
--- a/templates/web/base/maps/google-ol.html
+++ b/templates/web/base/maps/google-ol.html
@@ -10,7 +10,7 @@
 [% END %]
 
 [% map_sub_links = BLOCK %]
-<a class="hidden-nojs" id="map_layer_toggle" href="">[% loc('Satellite') %]</a>
+<a class="hidden-nojs" id="map_layer_toggle" href="">[% loc('Map') %]</a>
 [% END %]
 
 [% map_html = BLOCK %]
diff --git a/web/js/map-google-ol.js b/web/js/map-google-ol.js
index 5d128a7..a0e58cd 100644
--- a/web/js/map-google-ol.js
+++ b/web/js/map-google-ol.js
@@ -1,9 +1,9 @@
 $(function(){
     $('#map_layer_toggle').toggle(function(){
-        $(this).text(translation_strings.map_map);
+        $(this).text(translation_strings.map_satellite);
         fixmystreet.map.setBaseLayer(fixmystreet.map.layers[1]);
     }, function(){
-        $(this).text(translation_strings.map_satellite);
+        $(this).text(translation_strings.map_map);
         fixmystreet.map.setBaseLayer(fixmystreet.map.layers[0]);
     });
 });
@@ -26,8 +26,8 @@ function set_map_config(perm) {
         zoomDuration: 10
     };
     fixmystreet.layer_options = [
-        {},
-        { type: google.maps.MapTypeId.HYBRID }
+        { type: google.maps.MapTypeId.HYBRID },
+        {}
     ];
 }
 ```

As to what the actual issue is with the original code, I'm not sure, I can't see any reason why it's behaving like it is; if you look into it more and can work it out, please do let us know!

**Comment by vannenc** [comment]
I believe it is related to OpenLayers 2.x. I said a few people getting the same issues on stackoverflow.
