### ISSUE TITLE
after completing the survey, there's no link back to fixmystreet

### ISSUE THREAD

**Issue by mhl** [mysociety/fixmystreet#1140]
At least I couldn't see any obvious link or redirect at the end of the survey that might take me back to the site. Maybe we consider that the end of the transaction, but it seems there could be some call-to-action at the end.

**Comment by dracos** [comment]
Just to check, do you mean on a page such as https://www.fixmystreet.com/questionnaire/submit?token=_test_&been_fixed=Yes ?

**Comment by mhl** [comment]
No, it was some non-mySociety survey site I was taken to.

**Comment by dracos** [comment]
Ah, so you mean when confirming a report, https://www.fixmystreet.com/P/_test (steps to get to the survey would have been helpful, hard to remember where these things have been added :) ) – this is a research survey, @jacksonj04 @Rebeccarumbul something you can add to it? We try and always have somewhere to point people at once they've done something.

**Comment by jacksonj04** [comment]
I'm actually just about to pull the survey on FMS as we've collected enough data, so I'm going to close this as a wontfix, but I've added a note to our surveys checklist to make sure we get a CTA (or at least a more coherent message than just "thanks") at the end.
