### ISSUE TITLE
Remove Essex County Council special code

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1149]
Essex County Council problem reports are routed at the code level to special-case bodies (for east/mid/south/west), rather than by entering email addresses for the main council body in the admin interface. 

However, it looks like Essex have changed their system. The district-specific contacts are now bouncing - reports aren't being delivered. Default behaviour needs to be restored for this council.

**Comment by Gemmamysoc** [comment]
I'll write to Essex to ask them for new email addresses

**Comment by abimysoc** [comment]
Some contacts here: http://www.essex.gov.uk/Pages/Contact-us.aspx

**Comment by dracos** [comment]
Merged in fdbfe27, live on site.
