### ISSUE TITLE
Down for maintenance page static assets broken on admin site

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#1164]
Which 404 because the server isn't serving them:

![screen shot 2015-07-28 at 17 23 42](https://cloud.githubusercontent.com/assets/663700/8936993/80afce42-354d-11e5-8186-e816db4b3dfa.png)

Should these be somewhere else, like S3?

**Comment by dracos** [comment]
The server should still serve static assets when the site is down, I haven't noticed it not doing so before.

**Comment by stevenday** [comment]
My mistake - this was on the admin site that's proxied. I guess the assets should be referenced differently to work there.
