### ISSUE TITLE
Recent photos sidebar on alerts page runs over the footer

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#1168]
Moving this from https://github.com/mysociety/FixMyStreet-Commercial/issues/336 because it affects all FMS installations. e.g.

![screen shot 2015-07-30 at 16 42 51](https://cloud.githubusercontent.com/assets/663700/8987663/0eb751dc-36da-11e5-9f59-0c5d9663458c.png)

Should be as simple as removing the sticky-sidebar class, so PR to follow!

**Comment by dracos** [comment]
https://www.fixmystreet.com/alert currently overlaps still.

**Comment by zarino** [comment]
I would remove the sidebar, and put the "photos of recent nearby reports" in a horizontal line somewhere in the main content of the page, so your eye passes over them as you set up your report.

Need to take some care over where we put them, but I see no reason they *have* to be in a sidebar.
