### ISSUE TITLE
Broken mobile behaviour on report page

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#1173]
This comes from https://github.com/mysociety/FixMyStreet-Commercial/issues/579

@zarino's original comment was:
> What's wrong:
>
> I can scroll down and see completely unformatted content that should only be shown to desktop users.
>
> Steps to reproduce:
>
> Go to /around on a mobile / narrow screen
> Click on the map to plot a marker
> Change your mind and click "Try again"
> Note you can now scroll down and see all the ugliness
>
> Likelihood of someone finding this:
>
> Low.

This was raised on the smidsy cobrand, but actually occurs on all of them, hence me moving it here.

I made a gif that shows this in more detail:

![](http://g.recordit.co/aKu0PBzRm2.gif)

**Comment by stevenday** [comment]
I did a bit of investigating:

1. When the page is loaded, the `#map_box` is absolutely positioned with a `height: auto` to make it fill the visible space. This is set through a `style` attribute, and I can't see anywhere that this is set in the FMS code, so I presume OpenLayers is doing it. This results in the instructions and list of recent reports being hidden behind the map. They're never actually hidden, it's just that in most places on collideoscope the list of reports is small enough that it doesn't poke out the bottom enough to be able to scroll to it. On FMS.com though, there are loads of reports in most places, so it does, and you can scroll to it straight away.
2. When you click on the map to drop a pin, the `#map_box` gets updated to be relatively positioned. Again, it's through a `style` and I can't see any of our code doing this, so I presume that OpenLayers does it as a response to us showing the "Try again / OK" buttons and telling the map object to update it's size. At this point, FMS's `map-OpenLayers.js` also explicitly hides the `#side` div which contains the instructions on how to make a report and shows the `#side-form` which holds the reporting form. The change to `position: relative` means that the map isn't over the top of the content anymore and it flows below it.
3. Clicking OK at this point just scrolls you down to the form.
4. Clicking "Try again" hides the form div again and shows the instructions one instead. It doesn't change the position css of the `#map_box`, so in any cobrand you can scroll down now and see it all. Unfortunately in collideoscope the styling for the `#side` div is only in the desktop stylesheet, so it all looks a bit broken.

Aside from the fact that I'm not totally sure how to fix this yet, this raises the question of whether it's better to:
a) actually show the info and latest reports from the beginning, rather than hiding them behind the map. (Amongst other things, it contains the link to skip the map if you can't see it, which would be nice to keep).
b) properly hide and show all of the content we don't want with JS..

I'm going to move this and these comments onto the main FMS repo to discuss there

**Comment by dracos** [comment]
The intention was the map was full screen and you had to use the map, I believe. If you scroll over the map itself, the map zooms (according to 4eab56c784bb53d2e174e7b7101da7eba49a1a02 and on my phone, anyway), it was, I thought, only if you're over the tiny bit of content at the bottom that you can scroll, which is why I don't think this has really been much of an issue. The setting of style is all FMS code, though - your step 1, it is set in https://github.com/mysociety/fixmystreet/blob/master/web/cobrands/fixmystreet/fixmystreet.js#L86-L91. Step 2, the setting of relative is done by https://github.com/mysociety/fixmystreet/blob/master/web/js/map-OpenLayers.js#L673 (with a comment saying it's becoming relative to make it easier to scroll when OK is pressed).

**Comment by dracos** [comment]
Fixed by freezing body/html when full screen map is being shown.
