### ISSUE TITLE
Translation of report status

### ISSUE THREAD

**Issue by vannenc** [mysociety/fixmystreet#1179]
Is there a way to get the translation of report statuses in other languages? In the admin panel, it is shown in English.

**Comment by dracos** [comment]
Could you provide more details? The report states do appear translated for me on a report's edit page, here's a screenshot of my install set to Swedish:
![screen shot 2015-08-11 at 13 52 33](https://cloud.githubusercontent.com/assets/154364/9197929/43bcddca-4030-11e5-9197-18a5f367f354.png)

**Comment by dracos** [comment]
Ah, I see when it prints the database field directly (when it starts with a lower case letter), that will be in English as that's what the token is. This applies to the table on the front page, and the list of reports; can't think of a reason off hand why they couldn't be the translated versions too.

**Comment by vannenc** [comment]
The editing of a report is translated correctly, but the summary on the admin panel is not.

This is the home page of the admin.

![sans titre](https://cloud.githubusercontent.com/assets/2804514/9198010/ff0360b8-4049-11e5-89fd-a10d8b81719d.png)

**Comment by dracos** [comment]
Yes, thanks for confirming – those strings are directly from the database tokens, not being translated at all (not even into display English which would be e.g. "Open" rather than confirmed). It should be straightforward to fix this, hopefully can look soon.
