### ISSUE TITLE
Wrong Google Analytics cookies listed on privacy page.

### ISSUE THREAD

**Issue by evdb** [mysociety/fixmystreet#1190]
The current privacy page https://www.fixmystreet.com/privacy lists cookies that are used by the older analytics service - the `__ut*` ones.

The new cookies are `_ga` and `_gat` as described on https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage

**Comment by dracos** [comment]
Thanks for spotting, updating now.
