### ISSUE TITLE
Make it easier to restyle the selected item in the menu

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#1191]
From https://github.com/mysociety/fixmystreet/pull/1155/files#r37307090 - whilst styling Bromley's cobrand in their blue colour, I found that the CSS selector for the main menu's selected item were pretty specific (lot's of tag names and id's) and it had to be set separately from the main menu itself. It'd be nice if that was easier.

**Comment by dracos** [comment]
I have started on reducing the specificity, especially of the IDs (so you'd have to override `ul#main-menu span` currently). But I'm not sure the specificity is the cause of needing to set the selected colour separately. The default nav styling for layout is:
* $nav_fg/transparent for normal items
* $nav_fg/$nav_fg_hover on hover
* $primary/transparent for selected
* $primary_text/$primary for report-a-problem-btn and mysoc-menu.

If you've given the menu a background colour, and/or want the selected to have its own colour, they'll need to be set regardless of specificity. Perhaps the defaults could be improved somehow for this situation, the interaction with the variables isn't great, and we could add more.
