### ISSUE TITLE
mySociety/Config.pm missing from vagrant install

### ISSUE THREAD

**Issue by milh0use** [mysociety/fixmystreet#1196]
I tried installing the vagrant install of fixmystreet according to the instructions here: http://fixmystreet.org/install/vagrant/

But at the point of starting the server, get a message that:
Can't locate mySociety/Config.pm in @INC

I've looked for the file across the whole guest filesystem with no luck. Can I fetch it from somewhere?

**Comment by dracos** [comment]
Hi – I believe you forgot the '--recursive' from step 1 of that URL :) If you forget that, the submodule isn't initialised, which contains the file you refer to. You can do it after a normal `git clone` by doing `git submodule update --init` inside the repository. Hope that's helpful.

**Comment by dracos** [comment]
Should also note – doing the `git submodule update --init` should be all you need to do, you don't need to run vagrant up or anything again. Perhaps the install script should rerun the submodule update to make sure this has been done (though it's possible in development you might not want that, I imagine it's quite rare).

**Comment by dracos** [comment]
Made issue for that perhaps at https://github.com/mysociety/fixmystreet/issues/1197

**Comment by milh0use** [comment]
Gosh yes, that's it, sorry! I even installed it twice to try to identify what I'd done wrong but just re-ran the git clone from command history!

Thanks!
