### ISSUE TITLE
Generating .po files is hard

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#1202]
It involves installing Locale::Maketext::Extract and running scripts with environment variables set. We should have a way to set this up and scripts that do the right thing.

**Comment by dracos** [comment]
Just to document what's needed at present to install/run:
```
$ bin/cpanm -l local-carton Locale::Maketext::Extract
$ PERL5LIB="local-carton/lib/perl5:local/lib/perl5" PATH="local-carton/bin:$PATH" bin/gettext-extract 
```

**Comment by hcprieto** [comment]
Hi, 
Just to confirm. I ran the installation/run commands you provided, on my vagrant installation... and it worked! Strings got extracted. 
Thanks!
