### ISSUE TITLE
Promote native apps in iOS and Android

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/fixmystreet#1219]
We should be promoting the native FMS apps with [Smart App Banners](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html) on iOS and [native app install banners](https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android#native) on Chrome.

**Comment by struan** [comment]
I find them quite annoying, especially if I don't want to use the app so I'd not be in favour of this.

**Comment by jacksonj04** [comment]
The logic for using the native banners is that they stay gone once you dismiss them, unlike JS hack-arounds which insist on reappearing. I couldn't find any previous discussion of if we should or shouldn't though.

Let the games begin!

**Comment by abimysoc** [comment]
Obligatory reference to https://xkcd.com/1174/
