### ISSUE TITLE
403 accessing /admin

### ISSUE THREAD

**Issue by mijacr** [mysociety/fixmystreet#1228]
/admin interface can only be accesed from local network (and htpasswd works accordingly)
But when i try to access it remotely, i get a 403 without getting prompted to input password.

It's a fresh install from the script.

**Comment by dracos** [comment]
Sorry to hear that. I'm not sure what could be happening, because the install script only adds auth_basic to /admin, it doesn't do anything IP address related as far as I am aware. Can you get any debug/error logs and find more details as to why it's being rejected? What is your web server configuration?

**Comment by mijacr** [comment]
Server configuration for /admin:  
   location /admin {
        auth_basic "FixMyStreet admin interface";
        auth_basic_user_file /var/www/fixmystreet/admin-htpasswd;
        try_files $uri @catalyst;
    }

The new log line in access.log is:

20x.19x.1x.21x - - [24/Sep/2015:15:57:48 -0600] "GET /admin HTTP/1.1" 401 596 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML,$

But i get a 403 in my browser (no password prompt):
Error Code: 403 Forbidden. The server denied the specified Uniform Resource Locator (URL). 

 from local ip i get prompted for the password and it works allright.

When i disable auth_basic in the server's config, i can get into /admin from any IP.

Thanks for the swift attention
Offtopic: are there code tags or something to improve the look of this post?

**Comment by dracos** [comment]
(Yes, you can use ``` at start and end of a code block.)

Very strange, I'm not sure what's happening there I'm afraid; if nginx is serving a 401 but you are getting a 403, I can't see why that would happen. Does the same happen with all browsers? Can you see the contents of the headers returned for the 401 response, do they look okay?

**Comment by mijacr** [comment]
Yes, same response at least from both chrome and firefox. And the access.log says
` ` ` 20x.19x.1x.21x - - [25/Sep/2015:13:29:26 -0600] "GET /admin HTTP/1.1" 401 194 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:32.0) Gecko/2010$` ` ` 
I have been wraping my head arround this for a while to no avail, also the fact that the auth works fine from local ip rules out problems with htpasswd permissions and such...

**Comment by mijacr** [comment]
This are the response headers from the browser:
```HTTP/1.1 403 Forbidden ( The server denied the specified Uniform Resource Locator (URL). Contact the server administrator.  )
Connection: close
Pragma: no-cache
Cache-Control: no-cache
Content-Type: text/html
Content-Length: 2024```

**Comment by dracos** [comment]
I'm sorry, I'm not sure why that is happening for you, but it doesn't appear to be FixMyStreet related, but something to do with your web server configuration. I have just spun up a fresh instance and the admin works, asking for username/password, the same both locally and remotely. I can only suggest you look at other aspects of your configuration to see if they're interfering.
