### ISSUE TITLE
Reports list page includes deleted categories

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#1239]
The new combined reports listing page, with filters, includes deleted categories, whereas other pages (e.g. the new report page) purposely exclude them. Was there a reason for that, or do they need to be removed from that page too?

For example, see: http://fix.royalgreenwich.gov.uk/reports/Royal+Borough+of+Greenwich - there's a "Testing" category which is marked as deleted in the admin.

**Comment by dracos** [comment]
Sounds like a bug to me.

**Comment by dracos** [comment]
Around.pm has not_deleted, but it's missing from Reports.pm
