### ISSUE TITLE
Report questionnaire image overlaps text

### ISSUE THREAD

**Issue by paulfurley** [mysociety/fixmystreet#1243]
On Firefox 41.0 on Linux.

![image](https://cloud.githubusercontent.com/assets/254290/10264615/1691c704-6a09-11e5-888d-deb70fd03fa7.png)

**Comment by dracos** [comment]
Thanks for letting us know!
@zarino Is it okay to move the 120px to the inline-block a? That seems to fix it.

**Comment by zarino** [comment]
@dracos – if that fixes it! (Probably neatest to then give `.update-img { width: 100% }` rather than duplicating the `120px`).

**Comment by dracos** [comment]
That'll make the image take up the whole width of the column. It doesn't seem necessary to specify a width on the parent, a float will take up the width of its content, won't it?

**Comment by zarino** [comment]
Sorry, I meant `.update-img img` :-)

**Comment by dracos** [comment]
I changed the inline-block to block as I couldn't see any reason why it needed to be an inline block, and that fixes the issue (as block gets its width from its parent, not its children); thanks :)
