### ISSUE TITLE
all reports page doesn't show map if there are zero reports

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#1247]
Currently on a body's reports page, it looks like there's no coordinate to centre the map on (because normally this works by finding a bounding area of the outermost pins), so we end up with blue ocean. Looks like this is spoiling zoom calculations too (guess: that probably expects the diagonal opposite corners of the bounding box to not be coincident).

We do render the admin boundary of the body's area(s) on this page, and that is informative even if there are no reports to show: so if there are no pins to extract locations, use the bounding box of the MapIt areas instead.

Example of this in effect on FMS: https://www.fixmystreet.com/reports/Armagh+City%2C+Banbridge+and+Craigavon (body with 0 reports)

Concept by @dracos; errors in reporting it are my own.

**Comment by dracos** [comment]
NI council boundaries don't simplify correctly (MapIt returns a "no boundary at all once I've simplified" error), so there is no boundary on the page you link, so nothing to be done, unless FMS stored some body area information at its end somehow (doesn't seem worth it, niche issue there with NI boundaries). If there were a boundary, with no reports, then it would zoom to its bounding box (it zooms to whatever has been plotted on the map).

**Comment by davewhiteland** [comment]
ah got it -- thanks! My mistake in misreporting it :-)
