### ISSUE TITLE
Firefox not showing the "get updates" link

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#1257]
Works for me in Chrome and Safari (screenshot below), not in FF 41.0.1
e.g. URL https://www.fixmystreet.com/around?zoom=3&lat=51.43155&lon=-0.55192&layers=B

![firefox_fms](https://cloud.githubusercontent.com/assets/111320/10397876/d5f0a556-6ea1-11e5-8a35-cd672a21eac9.png)

**Comment by dracos** [comment]
It's there in FF40 :-/

**Comment by abimysoc** [comment]
It's there in my FF 41.0.1 as well... (Ubuntu version)

**Comment by davewhiteland** [comment]
Works for me now in FF 49
