### ISSUE TITLE
Allow specific users to be nominated to never receive questionnaires

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#1265]
Currently, whether or not questionnaires are sent depends on a system-wide setting.

On the Ugandan platform, there are some nominated users working for the FMS-platform-running team who are submitting accumulated reports on behalf of citizen users. These users (i.e., email-address nominated logins) don't benefit from being sent questionnaires because they're actively monitoring the state of the problems they've submitted anyway.

So maybe add a user-specific flag to the user to "never be sent questionnaires".

I thought this might work as a `has_permission_to` setting, but inspecting the code I suspect that's not the case because these reporter-users aren't associated with a body (that is, they're not staff users in the sense of [user-associated-with-a-body](http://fixmystreet.org/glossary/#staff-user)).

**Comment by dracos** [comment]
Since b01df0c7609a1d6c008b943a9936d471cf0e0ce3 `has_permission_to` is independent of the User’s `from_body` (this was done for trusted users), so this could potentially be done that way now. But it would still apply on a per-body basis, though.

**Comment by davea** [comment]
This would also make for a useful feature for public users who want to opt out of receiving all current/future questionnaires. User support message has mentioned it:

> How do I stop the questionnaire emails coming?
I've responded to one or two and your privacy policy suggested I could then opt out but I've seen no option either when submitting incidents or when responding to questionnaire emails?
