### ISSUE TITLE
document how to add new static pages

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#1275]
We encourage new static pages to be provided through a CMS like WordPress running on a subdomain maybe, but should at least document:

* adding a new static page to a cobrand if you really want to do (within the code)

* suggestions on how to do this outwith the code (e.g., WordPress running alongside)

**Comment by dracos** [comment]
Once #1276 is merged, this will be:
1. Put a new file in `templates/web/cobrand/about/foo.html` (or `foo-language.html`)
2. Now available at `/about/foo`.
