### ISSUE TITLE
Add option to include report images as attachments in body report email

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#1278]
Zurich has code to attach images to the body report email at https://github.com/mysociety/fixmystreet/blob/a577e6cead169a5f28daf020ebbc86de6fbac6c2/perllib/FixMyStreet/Cobrand/Zurich.pm#L1012-L1036 – generalise this so that any cobrand can do it, via a configuration/cobrand variable.

**Comment by jonkri** [comment]
+1

**Comment by jonkri** [comment]
Like with #72, this would not just be useful when we have HTML e-mail, but also right now with text mail.

**Comment by jonkri** [comment]
It's very nice to see progress on this! :)

What's the current status of this issue and #72, and HTML mail in general?

We will want to use HTML mail in FixaMinGata, as it looks better and makes printing of attachments easier than with text mails (at least under certain circumstances).

Cheers!

**Comment by dracos** [comment]
This has been done as part of HTML email (though it does only include the first image of the report).

**Comment by jonkri** [comment]
@dracos: I'm curious... How difficult would it be to attach a full version of the uploaded problem pictures in the report sent to the body? Thanks!

**Comment by dracos** [comment]
The Zurich cobrand attaches the full size images using the `munge_sendreport_params` cobrand function, which I assume works! You could fetch different size versions by doing something similar, I imagine.
