### ISSUE TITLE
Consider HTML emails for various emails

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#1281]
Confirmation emails could be made clearer (do we want map/photo there, or too much weight?), questionnaire emails (see #1103), report emails to body (optional image #1278, map image?) - attachments as well as HTML version, possibly others.

**Comment by zarino** [comment]
Something like these? (I've only considered public-facing emails so far, not sure I know enough about authority workflows to know how their emails should look)

![problem-confirm 2](https://cloud.githubusercontent.com/assets/739624/12845677/8c02727e-cbff-11e5-94a0-46c7ad2dbe2a.png)

![confirm-report-sent 2](https://cloud.githubusercontent.com/assets/739624/12845681/8efaf190-cbff-11e5-8190-af640923e1ae.png)

![comment-confirm 2](https://cloud.githubusercontent.com/assets/739624/12845682/9195bef8-cbff-11e5-8526-1b3f1877af68.png)

![questionnaire 2](https://cloud.githubusercontent.com/assets/739624/12845683/94aae87a-cbff-11e5-9e8d-fe50dbb5e00f.png)

**Comment by jonkri** [comment]
These look really nice!
