### ISSUE TITLE
Update clients list on /reports

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1282]
https://www.fixmystreet.com/reports references Barnet as a FixMyStreet for Councils customer, who aren't any more, and doesn't reference Harrogate, who are.

I am sure there could be a way of automating this when a new cobrand is added.

**Comment by MyfanwyNixon** [comment]
This is pertinent to https://docs.google.com/document/d/1zMia1nWltNKFE0LuK-OMzuw5X5heH4bPYve71xuufx4/edit, so there is a little urgency attached, thanks.

**Comment by dracos** [comment]
Have included Warwickshire too. And updated the manual text on www.fixmystreet.com/council too.
"I am sure there could be a way of automating this when a new cobrand is added." - I don't see how easily, as the code will all be sat there and ready before the site is "live", so there has to be a manual flag at some point to say when it actually is live. This should be in a commercial checklist as part of any putting site live process.

**Comment by MyfanwyNixon** [comment]
Thanks @dracos !

**Comment by abimysoc** [comment]
There is an internal checklist for putting a new cobrand live; I've just added a reminder about this.
