### ISSUE TITLE
Bad response from gaze.mysociety.org not obvious

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#1286]
If gaze returns a 500, say, because NFS/Apache grr, the error you get is `Couldn't render template "around/display_location.html: file error - maps/.html: not found` - as it's slipped through to the template `PROCESS` line. Really, if we get a bad response, we should just default to something. Though it is good to know when gaze has stopped working, I guess!

Also errors if called from cron scripts.

**Comment by jonkri** [comment]
+1

**Comment by dracos** [comment]
Sorry about that! An Italian IP address brought it down by scraping it all far too fast, I don't know what they're trying to do, they could get all the data much more easily another way. Will take a look at improving this soon.
