### ISSUE TITLE
Add common tasks to admin index page

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#1295]
- [x] Look at analytics and see popular/used admin pages and how the admin is being used
- [x] Add report/update search box to admin index
- [x] User search box on admin index
- [x] Add body search/lookup to admin index, autocomplete? (and bodies list page).
- [ ] Perhaps one universal search box on index page? Bit more work compared to copies of current above.

**Comment by abimysoc** [comment]
I use /reports /users and /bodies admin pages all the time, /stats occasionally, and the rest never. I'd like the admin to default to /reports; the current stats summary is nice to have _somewhere_, but it doesn't represent a top task.
