### ISSUE TITLE
'Donate' banner

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1299]
As suggested by @markcridge:
Can we display a banner across the top of the site, from Monday to Weds next week, and linking to https://www.mysociety.org/donate/

(I'm aware that this is the site of ours where users are most likely to think we're a council service, so I'm trying to pick the words with care)

> FixMyStreet is run by the charity mySociety. Can you help support us with a small donation?

**Comment by dracos** [comment]
Ready in `1299-banner` branch.

**Comment by dracos** [comment]
(Please deploy that branch, rather than merge it to master.)

**Comment by abimysoc** [comment]
Just to note, this banner also displays in the admin interface, in case we want to exclude that for a future iteration!

**Comment by MyfanwyNixon** [comment]
Hi, can we re-instigate the donations banner for Xmas 2016? Thought it could run from 16 December to 2 January this year.

**Comment by dracos** [comment]
Done. Sorry, I missed this as this ticket was for the 2015 banner, which was implemented successfully; new ticket for new functionality/bug please, reopening only for unfinished feature/not working bug, thanks :)

**Comment by MyfanwyNixon** [comment]
Thanks @dracos. It can come down now. 

I promise I'll start a new ticket next year!

**Comment by dracos** [comment]
Removed :)
