### ISSUE TITLE
Don't restrict image uploads to JPEG

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1302]
We have just noticed that FixMyStreet only supports the uploading of JPEG images in problem reports. It would be nice if this could be extended, for instance by supporting uploading of PNG files.

Cheers!

**Comment by dracos** [comment]
Now any refactoring of multiple uploads is out of the way, this should be easier to achieve, though still a bit of work. I hope to look at this in the next week or two.

**Comment by jonkri** [comment]
Cool! :)

**Comment by zarino** [comment]
I just encountered this too (albeit not a real world use-case: just uploading a PNG I found online for testing purposes).

**Comment by abimysoc** [comment]
User comment:

> [PNGs] seem to be silently dropped. It would be good if these appeared or were rejected with an error.

**Comment by dracos** [comment]
An error message is being shown, but annoyingly the preview PNG is also being generated and displayed on top.
