### ISSUE TITLE
We tell people to use the app next time, when they just have

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1305]
I used the app to make a report and the email confirmation link took me to the browser site, where I had the message as seen on https://github.com/mysociety/fixmystreet/blob/9e3abbbe4a69b4ab1d743b0b2e7e24ff4ac45ac2/templates/web/fixmystreet.com/next_steps.html "Next time, try our mobile app!"

Is there any way to not show this message when someone has just used the app?

**Comment by struan** [comment]
We know when they've used the mobile app as it says either iOS or Android in the service column for the problem so it should be simple enough to do this.

**Comment by dracos** [comment]
Easy enough to leave it out, do we have something to replace it with? Each message on https://www.fixmystreet.com/P/_test_ takes up a third of width currently.

**Comment by abimysoc** [comment]
I wondered about suggesting a call for donations but the process of donating seemed a bit fiddly for users we know to be on a mobile device. Then I thought: hmm. In that case, is it appropriate to offer them downloadable posters? Will the Twitter/Facebook links open native apps, or browser tabs? 

Is there, in fact, a more complicated task (that probably should be ticketed separately if we care about it) lurking underneath the simple one of changing a bit of text?

**Comment by dracos** [comment]
Email confirmation might not be on the mobile, could be later on desktop. Zarino points out on mobile these things are vertically stacked anyway so probably can just remove it for now and 50% the other two.

BBC News (probably slightly more shared than us) use links for Twitter/FB; apps can (certainly on Android) intercept links if they've registered them. So I think that's okay probably (might want to add WhatsApp? ;) ). Posters though, hmm, guess not, but perhaps good to advertise for someone to get later.
