### ISSUE TITLE
Add House Rules to FAQ

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#1311]
“Please could we add these 'House rules' to the FAQ page at the bottom of the 'What shouldn't I report?' section: https://docs.google.com/document/d/1RzSKmtNldxdcWNKsGEALrnxnQLAxMmqCyAkluwKlDYA/edit ? This will help guide people about how we expect the site to be used.”

**Comment by abimysoc** [comment]
I've added a suggestion to the doc that would fix #890 as well.

**Comment by dracos** [comment]
Added.
