### ISSUE TITLE
Photo upload on Opera/Lumia Windows

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1322]
https://twitter.com/trapprain/status/692455107347255296

> fyi photo uploading button doesn't work via @opera on Lumia Windows phone.

**Comment by dracos** [comment]
Is okay in Opera Mini 13 on Android, Windows has Opera Mini 9 or Opera Mobile 10, I think. It looks like our file uploader has an issue for Win9 at https://github.com/enyo/dropzone/issues/100. We should at least get it to fallback to the old file upload boxes, presumably some detection. Can hopefully blacklist when we find out the user agent, have asked.

**Comment by dracos** [comment]
Updated in our copy of dropzone, PR made to dropzone, looks like fallback is now appearing: https://twitter.com/trapprain/status/693109556596051968
