### ISSUE TITLE
Unsent reports won't be sent if status isn't "confirmed" or "fixed"

### ISSUE THREAD

**Issue by struan** [mysociety/fixmystreet#1334]
If a report doesn't get sent and in the meantime the status of it is changed to something other than "confirmed" or "fixed" then that report will never be sent. This is especially relevant in cases with council integrations where the user could mark it as "fixed - user" or, if there is a council login, it could be marked as "in progress"

**Comment by dracos** [comment]
I guess the theory here was if something has already been marked fixed or some in progress state, that probably means something that might then it doesn't need to be reported.

**Comment by dracos** [comment]
This was fixed (to send all open states) by 5df39f76b761d88dfa5ca86e8bf01a73115eba1c.
