### ISSUE TITLE
scroll-sidebar on hover over pin is losing the "call to action"

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#1344]
Here's my workflow:

* home page, enter postcode
* see map, with "Click Map to Report Problem" call to action in lovely big letters and GREEN
* hover deliberately or accidentally over a pin
* sidebar scrolls, *losing the call to action*
* OK, where was I? ah yes, reporting a problem: click on Report A Problem button
* bang, home page

It's not *wrong*, but I lose the key instruction that I need to click on the map.

Can we hold the call to action on the sidebar in position, and scroll the side bar under it?

**Comment by zarino** [comment]
See also https://github.com/mysociety/fixmystreet/issues/1349

**Comment by abimysoc** [comment]
Recent user support emails, since the change, that I suspect are related:

1

> I am trying to report a problem. Everytime I identify the spot I wish to report I get a list of all problems in the area and the green icon to report does not come up.

2

> your site won't let me post a new problem, it just invites me to update on a previous case

3

> Trying to report a problem. Tried putting the address and postcode of the problem area but am taken to previous problems  near this address wnd cannot get into the part of your site that allows submission of if information re problem

Suspect we may also see an increase in people trying to report new problems via the "report abuse" link (as that's the only hint about reporting _something_) though haven't checked the data to see if this is true.

**Comment by dracos** [comment]
Sidebar  no longer autoscrolls. See #1350/#1351 for further work.
