### ISSUE TITLE
Add Adwords conversion tracking code

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1345]
See https://github.com/mysociety/Non-Site-Specific/issues/687

As a condition of the higher level Google Adwords grant, we need to be tracking at least one goal. The sooner we can get this in place, the sooner I can reapply and the sooner we'll get more users back!

@jacksonj04 says:

> https://support.google.com/adwords/answer/6095821 is the guide on doing it.

> Basically, on each site, on each page which counts as a 'conversion' (eg the WTT success page, the WDTK success page, the TWFY postcode search result page, the FMS success page) we add a bit of code which tells AdWords "whatever you did, worked". When AdWords spots an incoming "success" message, it records that against the relevant ad (assuming the user arrived on the site via an ad) as a conversion.

For FMS, yes, the obvious goal is the 'your report is on its way' confirmation page. Could also consider adding the 'sign up for alerts' confirmation, though ads don't really point at that.

**Comment by MyfanwyNixon** [comment]
Can I bump this please? Be great to get this sorted so I can reapply for the higher tier Google Grant.

**Comment by dracos** [comment]
I was waiting to be told the conversion tracking tag to add to the website (which from the linked page is done in Adwords) – if that's been done, let me know what it is and I can then add it to the right page on the site :)

**Comment by jacksonj04** [comment]
@dracos: necessary tracking code emailed to you.

**Comment by MyfanwyNixon** [comment]
\o/

**Comment by dracos** [comment]
Thanks, now added.

**Comment by MyfanwyNixon** [comment]
Thanks both - @jacksonj04 do I need to do anything at the Adwords end?

**Comment by jacksonj04** [comment]
*In theory*, no. Conversions should start appearing in 24 hours or so.

**Comment by MyfanwyNixon** [comment]
Excellent, thanks. I'll wait a bit before reapplying - I guess the more sites we have the code installed for, the happier Google will be.

**Comment by MyfanwyNixon** [comment]
Just a note to say that in the last month we've had a 12.18% conversion rate which seems pretty good, especially given that for FMS we route people through the landing pages on mysociety.org. An endorsement of that approach, I guess (though there are other drawbacks, such as not being able to add site extensions to the ads).

Total clicks from ads: 2,193
Conversions in the last month: 275
'Cost' per conversion: $9.95 - this is high, but I suppose it's nominal to us since the grant covers it.

**Comment by MyfanwyNixon** [comment]
This conversion rate continues to be pretty consistent, with higher click numbers over the last 30 days. 

6,533 clicks from ads
11.65% conversion rate
761 conversions
Cost of each $9.61

Are we *only* tracking people who make reports or are there other actions that count as conversions for FMS, eg signing up to an alert?

**Comment by dracos** [comment]
Only creation of reports, either if logged in or via confirmation email.

**Comment by MyfanwyNixon** [comment]
I see that we have a goal named 'map click' - I know you say we're only counting report creation but that does make it sound like clicking on a map is counting as a conversion? or is it just badly named?

**Comment by dracos** [comment]
A map click sends a page view (I guess nowadays it should be an event, this must predate that), but there's nothing at the FixMyStreet end about it being a goal.

**Comment by dracos** [comment]
The `ecommerce:addItem` and the `googleadservices.com/pagead/conversion` code only appears on a report confirmation page. What these all do at the GA end, I cannot say.

**Comment by dracos** [comment]
The "clicking on the map" goal does appear to be measuring whether the map has been clicked, yes, I'm not sure what that has to do with the create new report goals though.

**Comment by MyfanwyNixon** [comment]
I don't know enough about the way the conversion tracking was set up - @jacksonj04 probably does though. 

So basically are we saying that not all Analytics goals are counted as Adwords conversions? In which case, no worries.

**Comment by dracos** [comment]
As far as I can tell from the FMS end at least, the adwords `googleadservices` code is only printed on a confirmed report page, no other. I don't know what that code does or where, or whether other code is related, though :)

**Comment by jacksonj04** [comment]
Correct, unless somebody has changed it (or Google has changed how it works, which frankly wouldn't surprise me) only pages with the `googleadservices` code will count as an Adwords conversion (because we don't pipe Analytics data back to Adwords, as per our privacy policy).

**Comment by MyfanwyNixon** [comment]
Thanks Nick and Matthew!

**Comment by MyfanwyNixon** [comment]
@jacksonj04 please could you have a look at [this page on Analytics](https://analytics.google.com/analytics/web/#report/advertising-adwords-campaigns/a660910w48856950p49313740/%3F_u.date00%3D20160101%26_u.date01%3D20160824%26_.goalOption%3DALL%26_r.drilldown%3Danalytics.campaignCampaignId%3AFixMyStreet%20%2F%2014291319%26explorer-table-dataTable.sortColumnName%3Danalytics.goalConversionRate%26explorer-table-dataTable.sortDescending%3Dtrue%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.rowStart%3D0%26explorer-table.rowCount%3D100/)?

Ie FixMyStreet>Acquisition>Adwords>Campaigns

Assuming I'm looking at the correct view, this is showing 0 conversions and only 9 sessions across all of our FMS ads for the last year. So, either that or the stats I mentioned [above](https://github.com/mysociety/fixmystreet/issues/1345#issuecomment-239807568) (taken from the Adwords interface) are wrong, or something's wrong on this page.
