### ISSUE TITLE
Reduce sensitivity of map pin hover listener

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#1349]
When you hover over a map marker on the FMS `/around` page, two things happen:

* All other map markers fade away
* The sidebar scrolls to reveal the hovered report

Problem is, it's too easy to trigger this behaviour by just passing your cursor over markers. And you might "hover" over a number of markers while you're making your way to the *one marker* you actually want to click.

Can we introduce a timeout, so that the markers only fade and the sidebar only scrolls after, say, 200ms hovering over a single marker?

**Comment by abimysoc** [comment]
Related user feedback:

> It's now virtually unusable: when you click on "problems nearby" you
get a massive list with no scroll bar, so you can't tell if you are
at the top of the list or the bottom: there is no indication of
date, and when you move the cursor across the list, it bobs up and
down, so you almost immediately lose your "place" in the list and
can't get back to it.

> Quite apart from being annoying, it's headache-inducing.

> I like the idea of "ghosting" out other pins near to the one you are
looking at, but this weird unordered flappy slidy list is quite,
quite horrible.

**Comment by davea** [comment]
Personally I find the scroll-on-hover behaviour incredibly annoying and disorienting. If I want a page to scroll. I'll scroll it. Anything that tries to do that for me will probably get it wrong.

Highlighting the relevant pin when hovering over a report in the sidebar is ++useful, but I don't see the benefit to the current marker hover behaviour. Why not a popover bubble when clicking a marker?

**Comment by abimysoc** [comment]
> Why not a popover bubble when clicking a marker?

:+1:  (that's "make FMS behave more like Google Maps" again, see #1326)

**Comment by dracos** [comment]
Will get rid of auto-scrolling on marker hover, sorry, one sec.

**Comment by dracos** [comment]
Gone.
