### ISSUE TITLE
Pull in report on list pages but keep in list view

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#1351]
It might be nice for when you select a report on a list view that the report is highlighted on the map, and details of the report (and everything from a report page) are pulled in and displayed directly but staying within the list view, letting you more easily switch to another report (and behaves more like Google Maps qv #1326).

**Comment by zarino** [comment]
* Get the page that you would normally send the user to, and instead just Ajax it, cut out the sidebar content div, and inject that into the current page.
* Consider the "get updates" button and the social sharing button.
* Might need to re-bind javascript on the new content (eg: dropzone listeners, login field unfolding, form validation)

**Comment by dracos** [comment]
It might be nice as part of this to have separate report pages have a clickable map to start a new report (which will then conceptually be the same behaviour of this, having a report within the around page).
