### ISSUE TITLE
fixmystreet.com /about page lacks text

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1354]
I'm not sure it's linked from anywhere but we can do better than the completely blank slate at https://www.fixmystreet.com/about (that I see frequently, because I can't remember that the FAQs live at /faq) - paging @MyfanwyNixon?

**Comment by dracos** [comment]
It is used on some cobrands but not fixmystreet.com. It should probably be a 404, it doesn't exist and isn't linked from anywhere.

**Comment by abimysoc** [comment]
Maybe it _should_ be linked from somewhere? I'd include it in the FAQs section (and TBH move the first four FAQs onto it = job done). On my first visit to a civic tech website I often have a look at the 'about' page to find out who runs the site and what they think it's for.

**Comment by dracos** [comment]
Made it 404.
