### ISSUE TITLE
"Can't see the map? Skip this step" link is no longer visible

### ISSUE THREAD

**Issue by abibroom** [mysociety/fixmystreet#1360]
It's there in the page source but it's not showing for me. Tested in Chrome and Firefox.
![fms-nomap](https://cloud.githubusercontent.com/assets/560001/13851557/93872748-ec56-11e5-9cb8-f70656c25eed.png)

**Comment by dracos** [comment]
It is keyboard accessible (appears when tabbing through as similar skip links do on BBC news etc); I wouldn't mind if it were always visible as it used to be, to cope with edge scenarios of map not loading or similar, but don't mind its current behaviour either; check with @zarino if there would be a way to do that or if we decide it's not worth it.

**Comment by dracos** [comment]
We also don't want to encourage skipping unless necessary, I guess.

**Comment by abimysoc** [comment]
Support email today where I think the problem was the user had an out of date browser that didn't load the map properly - this would have helped that person.
