### ISSUE TITLE
Lots of alert emails being rejected with "Spam content found"

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1364]
~75 in last 24 hours, predominantly ntlworld, virginmedia, virgin.net, blueyonder addresses.

**Comment by dracos** [comment]
I have contacted Virgin's abuse team, and BT's outsourced at http://miracare.mirapoint.com/checkip.html; we don't appear to be listed on any black list that I can see, but perhaps we were temporarily mistakingly and it has picked it up and cached it? :-/

**Comment by abimysoc** [comment]
This issue is back.

**Comment by dracos** [comment]
Have set emails to go with ReturnPath so hopefully that will help (or not, who can say).
