### ISSUE TITLE
Hardcoded council IDs in unexpected places

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#1368]
`Problem.pm` has [hardcoded](https://github.com/mysociety/fixmystreet/blob/e994554ec343239c4c5235338f5fd04046f247b8/perllib/FixMyStreet/DB/Result/Problem.pm#L657) IDs that should probably be refactored out into `Cobrand::UK`, where they make more sense

**Comment by abimysoc** [comment]
See also #506 since I happen to be looking through the issue list and noticed it: duplicate?

**Comment by davea** [comment]
Yep, this is a duplicate of #506.
