### ISSUE TITLE
Allow users to change photo orientation when uploading

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1378]
Oh no, my photo is sideways:

![photo-orientation](https://cloud.githubusercontent.com/assets/560001/14424686/63d11346-ffda-11e5-80bc-5f400db6cae4.png)

Whilst obviously one can change the orientation of a picture and re-upload it, users may not have the tools, the skills or the time to do so, particularly on mobile devices: so a "rotate photo" button would be a nice addition.

**Comment by dracos** [comment]
Might be two things - preview image and/or server not fixing. http://stackoverflow.com/questions/22765456/dropzonejs-javascriptloadimage-rotate-image might be of relevance to the preview if it's that. I think server is doing all it can to auto-rotate to correct rotation, might just be old camera?
Admins can rotate, so could offer it, but easiest would have to be post-report creation.

**Comment by willnwhite** [comment]
![image is upside down after drag and drop](https://cloud.githubusercontent.com/assets/8081877/16151581/b808b924-3495-11e6-8573-5e9828b3fa49.png)
Submitted as-is and then it was the right way up.
