### ISSUE TITLE
Unexpected white border beside description_tips

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#1380]
I think this crept in as part of the RTL support.

![screen shot 2016-04-18 at 15 55 59](https://cloud.githubusercontent.com/assets/739624/14608657/873254c2-057e-11e6-9e97-b81344f8a710.png)

White border-left on `.description_tips li` – it's invisible on cobrands where the sidebar form is white, but on cobrands like Oxfordshire, it can be seen pretty clearly.

Maybe the [style rule in `_base.scss`](https://github.com/mysociety/fixmystreet/blob/master/web/cobrands/sass/_base.scss#L1379) should be `border-left: solid 4px transparent` rather than `border-left: solid 4px #fff`?

**Comment by dracos** [comment]
Sounds okay to me. The `.change_location` similarly is using #fff.

**Comment by dracos** [comment]
Fixed by https://github.com/mysociety/fixmystreet/commit/f070fb4f6743f69b99362b821d4395e6f99700eb
