### ISSUE TITLE
Don't show "Download the app" confirmation to people who made their report via the app

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#1387]
In testing a new version of the app just now, I confirmed a test report via my email and got served:

![screen shot 2016-04-21 at 10 13 32](https://cloud.githubusercontent.com/assets/663700/14703806/bbf2bbde-07a9-11e6-9ab0-0214c7a4f3b8.png)

This feels a bit less than joined up :)

**Comment by dracos** [comment]
I thought I had fixed this in https://github.com/mysociety/fixmystreet/issues/1305 but clearly missed somewhere.

**Comment by dracos** [comment]
Was running on old checkout, that advert was removed in 61b0ea8be19a1db68d19508112afbe7a15814f36 and #1305 did fix it :)
