### ISSUE TITLE
Clear metadata from uploaded pictures

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1411]
If metadata is not removed from uploaded pictures (and I'm not sure whether this is the case), we might accidentally reveal information about the uploading user (who may want to be anonymous on the web site).

**Comment by dracos** [comment]
Has this happened, or is this theoretical? We strip the thumbnails generated, but leave the original alone, like Flickr, I thought in case it could be useful to someone (e.g. image direction, I dunno!). We can strip comments if we think it's worth doing, sure; perhaps at the same time we should create a 'maximum' size for uploaded photos to save a bit of disc space.

**Comment by jonkri** [comment]
Thanks for your reply, Matthew!

This concern was reported to us by a user of FixaMinGata. I have asked for more information.

My spontanous thought here is that it's probably worth it to take a secure/restrictive approach here, and explictly allow metadata values that we know/assume are safe, rather allowing everything, or everything except what we know is not safe. Even if we know that it's purely theoretical, we don't know what will be added to the images in the future. (The cost of this approach is of course that we might lose out on valuable metadata information that doesn't reveal anything about the user, while we're "catching up" on our metadata configuration.)

**Comment by jonkri** [comment]
Just FYI, I didn't receive an update from the user that requested this in the first place, but I still think that what I wrote in my last comment above makes sense. :)

**Comment by davea** [comment]
@jonkri Feel free to reopen this if it's still a concern. 30dd9d8bd1f4229bf5cb0a8c559ba00dba35b750 reduces network/disc usage but doesn't strip any metadata from uploaded images.
