### ISSUE TITLE
Unattractive shadows on light themes

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1419]
Boxes like the "hello" box and the box to the right of the FAQ (there might be others, I'm not sure) have a dark shadow around them that, while looking OK against the dark background of FixMyStreet, in my opinion looks a bit bad against the lighter background:

![shadow](https://cloud.githubusercontent.com/assets/777056/15685290/54505f86-276b-11e6-857b-0e1e439b8e55.png)

I also think it looks bad on FixaMinGata, which has a light grey background.

**Comment by dracos** [comment]
Yes, I think the default should probably be not to have any shadows at all except perhaps on map page if it works there (think it might be gone there already!).
