### ISSUE TITLE
Post button on updates is sometimes partially hidden

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1421]
Two separate user support emails today; I'm assuming some recent CSS change has inadvertently introduced this bug.

1

> When using Firefox, cannot post an update to an
issue as the "Post" button is hidden by the 4 options at the bottom
of the left-hand pane.  But works OK in Chrome.

2

>Within about the last week, a problem has developed, when using
Firefox, in that the Post button on the comment form, when not
logged in, and not using a password, is partially underneath the
bottom menu (which has a transparent margin) and is not accessible
with the mouse.

>I have had to select a field higher up and then use tab and enter to
submit the forms.

>Iceweasel 38.8.0 on Debian.

FWIW I can't replicate it; I have Firefox 46.0.1 for Ubuntu.

**Comment by dracos** [comment]
Should be fixed by https://github.com/mysociety/fixmystreet/commit/cd42db616993bd40525f30b6e405d8b5bce2f1db
