### ISSUE TITLE
Official image on Docker Hub

### ISSUE THREAD

**Issue by ovidiub13** [mysociety/fixmystreet#1435]
Hello,

I see no containerization option for FixMyStreet, especially for Docker. Are there any plans for this?

I'd like to help with this, and build an official image for Docker Hub. For this I'd need some guidance.

I see in the install steps [here](http://fixmystreet.org/install/manual-install/) that many development tools are needed to be installed in order to "build" FixMyStreet.

The container needs to be as light weight as possible.

Is it possible to "build" everything that needs to be built, and then put FixMyStreet in a fresh container with just the runtime dependencies? What are the runtime dependencies?

**Comment by ovidiub13** [comment]
I'm currently working on the 1.8.3 release.

**Comment by dracos** [comment]
Discussion thread on mailing list at https://groups.google.com/a/mysociety.org/forum/#!topic/fixmystreet/78L4vJMBZRc

**Comment by ovidiub13** [comment]
here is all the work I've put into it: https://github.com/ovidiub13/fixmystreet-docker

I haven't done anything an it in a loooong time. I'm currently involved in a few projects, and this is not a priority for me at the moment. If I get PRs, I'll reply, and merge them if the work. But I'd like to see this in the official FMS repositories.

Currently there are 2 fan based docker images on the hub:
https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=fixmystreet&starCount=0

**Comment by dracos** [comment]
We have a docker image now available at https://hub.docker.com/r/fixmystreet/fixmystreet/

**Comment by ovidiub13** [comment]
Can you please add a description and link to sources on that page?

Joi, 25 oct. 2018, 14:00 M Somerville <notifications@github.com> a scris:
