### ISSUE TITLE
HTTPS for Councils powered by FMS?

### ISSUE THREAD

**Issue by edent** [mysociety/fixmystreet#1443]
When signing in/up to FMS on my local council's page, I'm taken to

http://fixmystreet.oxfordshire.gov.uk/auth?r=my

If I go to [http**s**://fixmystreet.oxfordshire.gov.uk/auth?r=my](http://fixmystreet.oxfordshire.gov.uk/auth?r=my) my browser complains that the site isn't secure.

Would it be possible to mandate that all councils using FMS use SSL?

**Comment by dracos** [comment]
Oxfordshire now has SSL, thanks for letting us know. We certainly would like them all to, I actually thought Oxfordshire already did! It can rely upon the council, e.g. if they'd like us to use assets from their site, and that isn't HTTPS, but almost all are already, and hopefully can push any remaining.
