### ISSUE TITLE
Better map behaviour when pressing the back button

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1450]
The following enhancement idea got reported by a FixaMinGata user, so I thought I'd share it here.

After having visited a report page and navigating back, the map doesn't "remember" any panning and zooming adjustments that were made by the user. If it did, it would be easier for a user to check different reports in a certain subarea in a body.

Steps to reproduce:

1. All reports
2. Click on some body (like, Aberdeen City Council)
3. Zoom in and maybe pan to some subarea on the map
4. Open a problem report
5. Click the back button

Expected results:

The map looks like it did prior to opening the problem report in the fourth step.

Actual results:

The map looks like it did after the second step.

**Comment by dracos** [comment]
The changes in #1432 will cause the URL to update when reporting a new problem, which sounds like this sort of thing. Should make it easier to do this sort of thing (note for future: currently, the loading of the area boundary then fits the map bounds, so that would need to change).

**Comment by jonkri** [comment]
Thanks for the update, @dracos!

**Comment by dracos** [comment]
Actually the changes for #1432 have implemented this exactly, I think :) If you perform the steps you describe, you get what you're after. Hooray!

**Comment by dracos** [comment]
e.g. see https://www.fixmystreet.com/reports/Aberdeen

**Comment by jonkri** [comment]
Great! Thanks! :)
