### ISSUE TITLE
Mail sent after updating a problem is not filled in

### ISSUE THREAD

**Issue by loran750** [mysociety/fixmystreet#1460]
Hello

When you update a report, the mail sent to the owner of the report has a template not treated : 

**Subject of email** : _New <?=$values['site_name']?> updates on report: '<?=$values['title']?>'_

**Content of the email** : _You asked us to send you an email every time an update was made to the <?=$values['site_name']?> report: <?=$values['title']?>.

The following updates have been left on this report:

<?=$values['data']?>

<?=$values['state_message']?>

If you would like to view or reply to these updates, please visit
the following URL:     <?=$values['problem_url']?>

This email was sent automatically, from an unmonitored email account
- so please do not reply to it.

<?=$values['signature']?>

Unsubscribe?

We currently email you whenever someone leaves an update on the <?=$values['site_name']?> report: <?=$values['title']?>.

If you no longer wish to receive an email whenever this report is updated, please follow this link: <?=$values['unsubscribe_url']?>_

Regards

**Comment by dracos** [comment]
Hi, the release notes for 1.8.3 at http://fixmystreet.org/2016/06/03/v1.8.3/ say: “If your templates aren’t kept in the main repository, there are a couple of things to be aware of with this release: […] If you have customised any of the email templates that use <?=...?> style variables (e.g. alert emails, questionnaire, submit), you’ll need to rewrite them to use the standard [%...%] variables.”
If you contribute your changes upstream (I can't see your forked repo anywhere?), this would have been done for you.

**Comment by loran750** [comment]
hello

that's right, i forgot that point in the release note. Thank you.

@dracos : my fork is on bitbucket.

regards

**Comment by dracos** [comment]
Hey, I had a look on bitbucket, but I couldn't see it, could you make your fork public? I was just going to see if your template had anything unusual in it, but hopefully it doesn't :)
