### ISSUE TITLE
Problem creating a new report in busy areas

### ISSUE THREAD

**Issue by BenJam** [mysociety/fixmystreet#1462]
Where we have particularly busy areas residents are frequently (one authority handling 5 per day) leaving a comment on an existing report that should be a new issue.

**Comment by dracos** [comment]
Possibilities:
* #536 (note East Sussex has something on these lines already, making someone choose first if they're reporting or leaving an update);
* #393 (now #1351 is done, the converse could now be done, whereby viewing a report page directly could act as it does when you click a report from a list page (ie. other reports are shown very small, you can start a new report from it more easily, etc)
* #525 (making hide pins more prominent)
* Reduce time before pins stop appearing on the map by default.

**Comment by abimysoc** [comment]
I'd be interested to see what effect #1351 has had on this. The support mail (or lack of) for the main site is already indicating to me that it's changed user behaviour significantly: much, much fewer people now seem to be mistaking the 'report abuse' link on an existing report for the way to make a new report. Hopefully this means it is more obvious how to make a new report instead of updating/flagging an existing one.

**Comment by abimysoc** [comment]
User support emails about the crowdedness of the map / the difficulty of placing new pins definitely seem to be on the increase as the number of reports on the site goes up, particularly in places like Oxfordshire.

**Comment by dracos** [comment]
Here are my current thoughts (could also see @zarino's previous suggestions at https://github.com/mysociety/fixmystreet/issues/525#issuecomment-309734261 – 1 and 2 were done in that list - and my previous plus others at https://github.com/mysociety/fixmystreet/issues/1519#issuecomment-246993721).

I think the following should be implemented:
* (Solution 3 in Zarino's comment, dealing with mis-click on report, or just being on a repot page in general) On a report page (directly or via around), have a way of starting a new report directly at that location: "Report a different problem at this location" [easier to implement if come via around, in JS]
* (asked for couple of months ago, https://github.com/mysociety/fixmystreet-commercial/issues/963) Tracking any clicks on green banner, just to see
* Make hide pins bar/stuff much bigger on mobile, easier to see and to hit.

I think the following should be done, tested ("please try and report a pothole at X" where X is quite busy):
* Moving the green banner on top of the map (comment in #1519);
* Have clicking the green banner, where it is or moved from above, hide/show the pins (or even just on hover hide them, have the bar be some form of toggling interface);
* Replacing the green banner with a draggable pin and instructions to drag it on to the map to report a problem - *starting* a drag immediately hides all map pins. Clicking would still work too;
* Having an always visible clear toggle between "viewing" mode and "reporting" mode that does the sae as hide/show pins but both options always visible - like a Map/Satellite layer picker, maybe? Anyway, as long as it's clear there are two modes and you can switch between them. Clicking in view mode would still work too.

**Comment by struan** [comment]
I'm not sure about the dragging a pin just because my hunch is most people find that slower and harder than clicking. 

I did wonder about having more transparent pins display when you start to move the mouse over the map but, sigh, discoverability.

**Comment by abimysoc** [comment]
User comment:

> Your FAQ mentions that you can "hide pins", but maybe it would be more user-friendly for the default condition to be such that pins relating to Closed/Fixed/Deleted issues are normally hidden. ie only current/un-resolved pins showing. A "Show historic pins" button could enable viewing old issues for analytical purposes.

**Comment by LouiseMySociety** [comment]
Considered done with the map now only 6 months of open reports.
