### ISSUE TITLE
Modifications to /councils to reflect new product features/pricing

### ISSUE THREAD

**Issue by BenJam** [mysociety/fixmystreet#1468]
On 1st Aug GCloud 8 will go live with new product features/pricing. The 'for councils' page needs to reflect this. Immediate need is to:

- [x] take down current page and replace with a 'big things are happening' notice with a redirect to the GCloud 8 page. 

Then we ned to launch into a new page design which describes the new product configuration (fault reporting, case management integration, case management provision) and options (mobile app, tiles, geocoder, assets, planned works etc). 

https://www.digitalmarketplace.service.gov.uk/g-cloud/services/983131669131363

**Comment by wrightmartin** [comment]
Page description diagram

https://docs.google.com/document/d/1Bxontd-v8ex8hk0OO7PH4sqKATht7NUI5VMXTTI-_vY/edit#heading=h.rjn5jb9zu3s

Wireframe

[marketing-page-wireframe-aug-2016.pdf](https://github.com/mysociety/fixmystreet/files/401744/marketing-page-wireframe-aug-2016.pdf)

**Comment by BenJam** [comment]
Looks great, I'm not sure about the copy (which we'll work on with @MyfanwyNixon next week but comments purely on the layout are:

- the 'order' section is almost certainly more important than the case studies, and the optional extras too.
- the optional extras are quite 'in depth' and as such might want to be even less prominent, maybe even hidden.
- all of the optional extras fall under what I would call the 'bring your own' banner, with the exception of the mobile application. If we could simplify our message on the former by breaking it from the later it might ease people's understanding as the read through. This needs to be folded into the overall message at the top. 
- The 'happy clients' section could —maybe even should— link through to the actual FMS for councils instance. Love Clean Streets dos this in it's 'network' pages. 
- This is a web page, and there are things we can do here that we can't do in the GCloud store. WRT the happy clients section we could show the stats for each instance (reports this week), which might drive us to track this more closely and live or die by the success of our clients. This can only be a good thing. Worth thinking about a little more.

**Comment by wrightmartin** [comment]
> reports this week

You'll know better than I do, is this the metric that will turn the heads of Local government customers?

**Comment by wrightmartin** [comment]
Updated wireframe

![desktop hd](https://cloud.githubusercontent.com/assets/2292925/17551197/963c0492-5ef0-11e6-935b-d5fd21c5fd82.png)

**Comment by MyfanwyNixon** [comment]
Marvellous - @BenJam I am going to need more insight into the new product before I can confidently write about it. What's the best way to do that? Hangout?

**Comment by BenJam** [comment]
@MyfanwyNixon content is all taken from the documents uploaded to the digital marketplace https://www.digitalmarketplace.service.gov.uk/g-cloud/services/983131669131363 

I'm tempted to edit some of this down and change some of the wording which we can do in https://docs.google.com/document/d/1Bxontd-v8ex8hk0OO7PH4sqKATht7NUI5VMXTTI-_vY/edit#heading=h.rjn5jb9zu3s

**Comment by BenJam** [comment]
I've replaced the 'partners' section in the above GDoc, trying to get across the various types of system we can work with. Would be good to include those we know we *can* support, possibly grayed out but tracked as an indicator of interest.

**Comment by wrightmartin** [comment]
![desktop hd](https://cloud.githubusercontent.com/assets/2292925/17693218/ab5c4644-6395-11e6-94fb-a43cbbd0a77a.png)

I forgot to upload the latest version before the weekend, sorry

**Comment by BenJam** [comment]
Looks god, might need to drop or re-jig the 'works with' sections as I think Confirm, Exor and Mayrise are technically asset management systems. 

Also wording on 'bring your own, or we can provide' is misleading, we're not about to provide ESRI to customers for £1,500/year. Finally we need to be explicit about +VAT, but this is all wording which I'm looking at now.

**Comment by wrightmartin** [comment]
![desktop hd](https://cloud.githubusercontent.com/assets/2292925/17770505/13e45cd2-6536-11e6-9e84-12b8d7ead051.png)

Latest version

**Comment by MyfanwyNixon** [comment]
I've copy-edited the text on https://docs.google.com/document/d/1Bxontd-v8ex8hk0OO7PH4sqKATht7NUI5VMXTTI-_vY/edit#heading=h.rjn5jb9zu3s

**Comment by wrightmartin** [comment]
Here's the design, this is currently coded up, and has mobile and cross-browser styles left to do

![fixmystreet for councils fixmystreet](https://cloud.githubusercontent.com/assets/2292925/17973935/18cb5498-6adc-11e6-8274-5ecb8ccd66c1.png)

**Comment by wrightmartin** [comment]
Also, we need to decide what the screenshots should show

**Comment by MyfanwyNixon** [comment]
That is super-smart.

**Comment by wrightmartin** [comment]
ok, cross-browser and mobile styles is all done, just a few things from you guys

- [ ] What should the two screenshots show?
- [ ] Which council logos should feature in the clients bit
- [ ] Any other general feedback?

**Comment by MyfanwyNixon** [comment]
Screenshots: I think the map pages are the most visually compelling.

**Comment by abimysoc** [comment]
Councils: not Barnet, because they don't have FixMyStreet any more.

General: comma separators in the prices? justified text?

**Comment by BenJam** [comment]
thanks for putting this together Martin. Some point sin no general order:

* Screenshots: I think we should show an area shot with lots of reports on desktop, a 'create a report' shot on the mobile and a manage report or dashboard on the tablet.
* Council logos: Bristol (lead), Oxfordshire, Zurich, Greenwich and Angus cover a nice rang of big city metropolitan, large area county, smaller district and a range of technology/product options. 
* Generally: 
* * I think some images next to features could break up what is a whole page of text
** The council logos should link through to the respective sites possibly show some broad stats (no. of reports) and it should be obvious this is an option
** the order section could be condensed, perhaps removing the large screenshot
** the optional extras: is the idea to have 1-2 common options open at the start, might be an idea
** I'd like to track which services users hover/click on as an indicator of what to integrate next?
** loving the local imagery on the case studies, could we consider bringing this into the clients section too perhaps?
** consider a 'shortcut' option to go straight to the order section after the features section

**Comment by wrightmartin** [comment]
> Screenshots: I think we should show an area shot with lots of reports on desktop, a 'create a report' shot on the mobile and a manage report or dashboard on the tablet.

Which cobrand?

> the order section could be condensed, perhaps removing the large screenshot

It's not the screenshot that adds the height, it's the form really - apart from making the form parts smaller there's not a huge amount to do here (Making parts of the form layout horizontally is good for aesthetics but never as usbable)

> the optional extras: is the idea to have 1-2 common options open at the start, might be an idea
Yes, there's 1 option open, to show it's an accordian thing

> loving the local imagery on the case studies, could we consider bringing this into the clients section too perhaps?

It's possible; as it is I'm using it as a way to differentiate between the 'clients' section and the 'case studies', as they're different

> consider a 'shortcut' option to go straight to the order section after the features section

Yep, sure

**Comment by wrightmartin** [comment]
> Council logos: Bristol (lead), Oxfordshire, Zurich, Greenwich and Angus cover a nice rang of big city metropolitan, large area county, smaller district and a range of technology/product options

Is the goal here to show a range of installs, or to show a recognisable, populated client list? 

If we're trying to demo a range of installs then the design should change - a list of logos is more suited to a longer list of clients (look at all these folks who've already signed up!), rather than a selected group

**Comment by BenJam** [comment]
wow this is getting all threaded:

on the cobrand, everything is currently in the Oxfordshire one but we should do it neutral I think. Maybe even going so far as to establish a monochrome demo service. 

on images/logos: yes it's good to differentiate and you're right about groups vs. big client list. Let's keep the big client list, i just want councils to say 'oooh they have one like us' as I think Districts worry about price, counties worry about covering large area and metropolitans worry about scale.

**Comment by BenJam** [comment]
perhaps just a nice screenshot of the FMS homepage for the final as it has all the branding etc. again there?

**Comment by dracos** [comment]
PR merged, so presumably done.
