### ISSUE TITLE
Feedback on HTML emails

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1469]
I'll put all the feedback I get in this one ticket for triage rather than opening separate ones, for now.

From a council:

> the new format of the forms are not very good as when we go to reply to the customer, the background colour is almost black

Mail client is Outlook, and when they reply, it sounds like the grey background colour of our email is used in the reply as well.

**Comment by abimysoc** [comment]
The contact form email that goes to FMS support erroneously states "This email was sent automatically, from an unmonitored email account. Please do not reply to it."

**Comment by abimysoc** [comment]
Some mail servers are set up to be really picky:

> 550 5.7.1 Your email program uses "=20" instead of spaces. Please correct this (try setting your mail program to use plain text) and resend your message.

This was a local alert email.

**Comment by dracos** [comment]
That mail server is strange, because it could still contain `=20` if it was plain text only (that's quoted printable) and any space at the end of a line needs encoding like that. I'll try and strip all end-line spaces in the templates, but I don't think we can guarantee this, and shouldn't have to.
