### ISSUE TITLE
Install Readspeaker or similar

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1498]
Doug suggests:

> would mySociety consider using Readspeak on their websites? It works quite well. For an example, try the "Listen" button on here: http://www.disabilitynewsservice.com/bus-companies-using-loopholes-to-evade-access-laws/

Clearly this would be a good step towards further accessibility on our sites - and possibly fulfills some of our desires to reach wider audiences.

http://www.readspeaker.com/benefits-of-text-to-speech/ explains some of the people this addition would help, among them:
- People with learning disabilities
- People who have literacy difficulties
- People with visual impairment

No explicit price list online; would have to approach them. As with [TWFY](https://github.com/mysociety/theyworkforyou/issues/1169) I suppose one question is to what degree such users tend to have sorted out solutions for themselves, eg screen readers.

**Comment by dracos** [comment]
My browser lets me select text – on any website – and select "Start speaking" and it speaks it. It doesn't have as many options as the link you give, sure, but it works on all websites and so is easier and more consistent for me to remember.

Couple of related links: http://www.karlgroves.com/2012/04/19/can-assistive-technology-make-a-website-accessible/ and http://www.headstar.com/eab/issues/2004/nov2004.html#i59-12

**Comment by dracos** [comment]
No intention of doing this at present.
