### ISSUE TITLE
Improve error message seen when 'Name' field validation fails

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1526]
[Was "'Name' field no longer allows an email address to be entered"]

Result of #1514?

Councils often want to post updates on reports using their general contact email address in the 'name' field ([example](https://www.fixmystreet.com/report/857845)). Users also sometimes enter their email address as their name.

Two possible fixes.

1. Revert and allow email addresses again.

2. If disallowing them is intended behaviour (I'm fine with this!) the error message needs to be more helpful - it doesn't say what's actually wrong with the data that's been entered, which is causing confusion.

![error](https://cloud.githubusercontent.com/assets/560001/18508601/b1aa3c66-7a6c-11e6-970f-bcffbc14c0cf.png)

**Comment by dracos** [comment]
After db research, will go with 2 :)

**Comment by abimysoc** [comment]
Email today from a user confused by the error message: they'd put just a first name, not a full name. In this case the message does actually make sense and describe what's wrong, but as it's new behaviour, it's not what regulars used to putting a single name are expecting - could be worth bolding 'full name'?

**Comment by dracos** [comment]
Hopefully bit better now.
