### ISSUE TITLE
Improve ease of cobrand testing

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#1529]
- [x] Set up UK cobrands so when staging/dev, they don't check you're in the right area, and have no problem/update restrictions
- [x] Fix Zurich cobrand so that it doesn't die with division by zero if you use non-Zurich map
- [x] Basic fixture to get something in for testing with the above

**Comment by zarino** [comment]
> Set up UK cobrands so when staging/dev, they don't check you're in the right area…

Is it possible to set this for *all* cobrands? So, any lat/lng will work in any cobrand, if on staging?

**Comment by dracos** [comment]
UK cobrands are the only ones doing this area check. They actually also have another check that co-ords are within UK bounds that might want to skip too.
