### ISSUE TITLE
Activate CORS for /rss to allow problem feeds to be embedded in other webs

### ISSUE THREAD

**Issue by hcprieto** [mysociety/fixmystreet#1540]
To include the right headers included in petitions of rss feeds, the following changes are required in the nginx configuration:

* Inside the @catalyst block, add a line: 
"add_header Access-Control-Allow-Origin $acao;" 

* Above the @catalyst block, add: 
      set $acao ""; 
      if ($uri ~ ^/rss) { 
          set $acao "*"; 
      } 

Would it be possible to have this settings included in the default installation (AWS, etc)? In the AWS installation the configuration file is at: /etc/nginx/sites-enabled/default

**Comment by dracos** [comment]
There's no need to trouble the web server for this, the FixMyStreet code itself can output the header and then it will always be present, whichever web server is in use (it was easier to add it to the webserver config until FixMyStreet adds the header :) ). PR for this at #1541

**Comment by dracos** [comment]
This is now merged, and e.g. live on fixmystreet.com
