### ISSUE TITLE
Leave update when body user changes category

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1544]
Would it make sense to provide body users with a drop down menu that they can use to select the category for a problem when making updates? This would allow body users to correct mistakes made by the reporting user (instead of the FixaMinGata admin having to do it), or save the user the hassle of having to create a new report.

If this would make sense, it would be nice if we could somehow allow the body user to also resend the e-mail, so that the report is being received by the correct entity.

Thanks!

**Comment by dracos** [comment]
Code we are currently working on has involved splitting many administrative tasks into permission based features (i.e.allowing the user body permissions table to be edited in the admin and with many more options). This includes an "inspect" option (meant for people physically inspecting the report) which produces a form like you see below:
![screen shot 2016-09-30 at 15 56 42](https://cloud.githubusercontent.com/assets/154364/18995981/871c89a6-8726-11e6-9433-a0772d3e23a2.png)

plus an "edit category" permission which has a cut down option to enable category changing of a report:
![screen shot 2016-09-30 at 16 06 22](https://cloud.githubusercontent.com/assets/154364/18996341/dd9087c8-8727-11e6-8269-f879e1d11de8.png)

Currently, this only updates the category, it does not resend the report, and that is currently still an admin feature. I agree it would be good to enable the category-edit-user to do this though, perhaps with a tickbox in that form when they update the category as to whether they want to resend or not.

(Another option is you can allow body users access to the whole report-edit section of the admin for reports within their body with another permission, that may provide too much access.)

**Comment by jonkri** [comment]
Thanks for the update! That's very cool!

One suggestion we got was that when an admin (or body user) changes the body responsible for a problem (or the category, more generally), FixMyStreet could let an e-mail go out to the user who reported the problem. This would make the admin/body action visible to the user, which shows the user that the body is acting on the report. As a potential secondary benefit, it also informs the user what the category should have been instead.

I do think that it would provide too much access to body users to be able to access the whole report-edit section (for us).

**Comment by dracos** [comment]
Yes, I think a category change should cause an update to be left as audit, which would then be alerted like a normal update.
