### ISSUE TITLE
document single instance support for multiple languages

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#1571]
A single FixMyStreet can support multiple languages (and have a switcher for explicitly jumping between them if auto-detection picks the "unwanted" one), but it's not clearly documented -- we've been asked a couple of times recently for if/how this can be done.

See http://fixmystreet.org/customising/language/ where this should presumably be described.

See [this FMS question](https://groups.google.com/a/mysociety.org/forum/#!msg/fixmystreet/MXWtK85AzLA/kP93ltVXIgAJ) for example query, and @dracos's reply, which could be the basis for the additional information.

**Comment by dracos** [comment]
Have a switcher auto-appear in default cobrand if multiple languages set up would seem good idea. Ties in with #1619 somewhat.
