### ISSUE TITLE
WFS

### ISSUE THREAD

**Issue by opjbvll** [mysociety/fixmystreet#1575]
Please advise how to pull WFS elements into fixmystreet.

**Comment by dracos** [comment]
Could you provide some more detail as to what you’re after? I can describe what some existing cobrands do in the codebase, if that’s helpful.

There is a JavaScript file `/cobrands/fixmystreet/assets.js` that a cobrand can include to provide a basic set up of asset layer functionality (this may not be what you want, but hopefully is of interest). Then a cobrand can call `add_assets` in a similar fashion to e.g. how Angus does it here: https://github.com/mysociety/fixmystreet/blob/c94ed4479f26b6d4cee0bf16cac47a88ee7f6cae/web/cobrands/angus/js.js – Bristol is another cobrand, that one with multiple asset layers.

**Comment by opjbvll** [comment]
Thank you, that is useful enough.  We are looking to add something similar.
