### ISSUE TITLE
new report not added to /reports

### ISSUE THREAD

**Issue by BenJam** [mysociety/fixmystreet#1576]
v.2.0
added body
added categories to body
added report to category in body (under superuser) 

the report shows up, is recorded on homepage but does not present under the body on /reports

**Comment by dracos** [comment]
This isn’t really enough information to go on, I’m afraid. What is the URL that doesn’t work? What is the URL of the report? What state is the report in? What is bodies_str set to for the report?

**Comment by BenJam** [comment]
this is on my local machine, I can print my config, I could dump the db but it is happening on 2 different local installs here.

**Comment by dracos** [comment]
…and it is not happening in any install that I have access to, so that’s not that helpful :) I can’t help without more information, sorry.

**Comment by dracos** [comment]
My only guess to this is it's talking about the summary table, which is cached for performance reasons; the body pages aren't though, so no idea if it was about them.
