### ISSUE TITLE
If no reports on map, "sort by" doesn't work

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1577]
https://www.fixmystreet.com/around?pc=PO17+6AR has no reports on the map (at time of writing!).

The list of reports shown in the sidebar is the fallback: closest 20 to that postcode. This means the "sort by" dropdown has no effect - even though the list of reports looks on first glance to be the same as any other list of reports - and thus appears to be broken.

Should perhaps say something like "No reports to show on map, here are some nearby ones" as a clue that this list of reports won't behave like other ones. Or make the sort work on those 20 reports regardless of whether they're on the map or not.

**Comment by dracos** [comment]
It does say the text mentioned above now, added as part of pagination. Think that should do; there's not much point in making the sort work because it is the 20 closest to the map, not necessarily the 20 newest/oldest etc, which it might make you think it was otherwise iyswim.
