### ISSUE TITLE
Add translations for fixmystreet.org to transifex

### ISSUE THREAD

**Issue by BenJam** [mysociety/fixmystreet#1578]
or another platform like Write/Read The Docs.

**Comment by dracos** [comment]
fixmystreet.org is a static site of static Markdown pages, so I'm not sure how easily possible this is. "Transifex Live" might be a better way to go for that sort of site, though that then provides all the translations through JavaScript and reloading the content proxied through the Transifex servers.

**Comment by dracos** [comment]
Don't think this is happening any time soon.
