### ISSUE TITLE
Tile loading problem when arriving at report via e-mail

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1591]
Some of our (body) users are quite frequently experiencing problem with some (OpenStreetMap) tiles not loading in the iOS web browser. (It may happen in other environments too.) This problem happens only (or at least significantly more frequently) when reports are opened from a direct link (from an e-mail).

![fmg-map-problem](https://cloud.githubusercontent.com/assets/777056/21525552/55f6cb96-cd1e-11e6-8805-f39076da22cd.png)

What do you think? Is this something that you recognize? It sounds like some kind of race condition.

Thanks!

**Comment by dracos** [comment]
Is this still an issue? All the code does as far as I'm aware is load images from OSM, sorry.

**Comment by jonkri** [comment]
@dracos: I haven't heard anything about this happening for a while. Perhaps this issue can also be closed, for the same reason as #1738?

**Comment by dracos** [comment]
Yep, if you're happy to. Will keep eye out.
