### ISSUE TITLE
Map within report to council should click through to report page

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1596]
... well, that's how I felt, anyway! If I were trying to ascertain the precise position from a report like this:

![fireshot screen capture 973 - fwd_ problem report_ street light out - fixmystreetsupport mysociety_org - mysociety mail - mail_google_com_mail_b_77](https://cloud.githubusercontent.com/assets/944656/21775346/9ebbaf40-d68d-11e6-9efb-a352292d02c6.jpg)

 I think I'd naturally click on the map.  And if I did that, the best result would be to be taken to the report page, where I can zoom in, pan around etc.

**Comment by zarino** [comment]
Great idea!
