### ISSUE TITLE
Add parish councils

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/fixmystreet#160]
Initial tranche of work:
- [x] Add ability for .com to have parishes, but not all parishes as there are too many, so a way to have in config which parish areas should be available to then have for a parish body
- [x] Sort out alerts page to work in a place with a parish council body present (or all parishes if we have that information available there?)

"Is it possible to add a Parish Council Option for email alerts as in many cases (ours included) the District/County areas selected extend well beyond the Parish boundary thus leading to reports being received for "out of area" locations which are of no concern to us?

I notice that the maps used are from OS and that their "Election Maps" application offers a "Civil Parishes or Communities" option already."

**Comment by Gemmamysoc** [comment]
User suggestion:

"Also is it planned
to add a "Parish" option to filtering in a future release please as
County and District filtering is a bit too "broad brush"."
