### ISSUE TITLE
Make "details" strings possible to translate through gettext

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1604]
The following two files contain strings that are not translated through gettext:

* templates/web/base/report/new/form_report.html ("Public details")
* templates/web/base/report/new/form_user.html ("Private details")

Could these be made possible to translate?

Thanks!

**Comment by dracos** [comment]
Sorry about that, don't know how they were missed :( Will look at getting them added and new file pushed asap.
