### ISSUE TITLE
User accounts are case sensitive? Shouldn't be

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1623]
Based on a support email we got today, I'm surmising that email@foobar.co.uk and email@FooBar.co.uk are treated differently in some way, which is incorrect behaviour as they are to all intents and purposes exactly the same thing.

This user was logged in as (not their real email address obvs) email@foobar.co.uk and could only see a couple of their updates on /my. When I checked in admin, these updates seem to be the only ones made under the lower case variant of the email address - their other reports/updates are all under email@FooBar.co.uk (I think; there were quite a lot and I didn't check every single one).

I asked the user to let us know what happens if they log in with mixed case email address (on suspicion that would reveal all the rest of the reports), waiting to hear back.

**Comment by dracos** [comment]
Sorry, I mentioned the 19 accounts at https://github.com/mysociety/fixmystreet/pull/1605 this applies to but didn't yet merge them as mentioned there.

**Comment by dracos** [comment]
All done.
