### ISSUE TITLE
Make dashboard strings translatable

### ISSUE THREAD

**Issue by altinukshini** [mysociety/fixmystreet#1624]
All strings under templates/web/base/dashboard/index.html should be translatable and included in FixMyStreet.po

**Comment by dracos** [comment]
This has never really been a public or stable feature. It will probably be getting some development in the near future as part of some work we are doing, so this might be able to happen as part of that.

**Comment by dracos** [comment]
This has been done in e5529e430f180cebfa992dff6ac8285870576051 though as mentioned this might change in future.
