### ISSUE TITLE
Reconsider reports page

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1630]
The marketing manager at one of our client councils has suggested that we either remove, or reword https://www.fixmystreet.com/reports.

One issue is that of course, client councils are going to show higher numbers of reports, giving an uneven view of the number of problems within their boundaries. This leads to bad press from journalists who don't stop to think about it.

One easyish fix might be to separate out client councils from the others, with a bit of explanatory text?

**Comment by MyfanwyNixon** [comment]
Further nudge from said client - could the team have a think about this, so we can come back with  a definite yay or nay, even if the actual work doesn't get prioritised? 

cc @dracos @jukesie

**Comment by jukesie** [comment]
We spoke to the bit of Oxfordshire we are dealing with re FMSfCouncils yesterday and they raised it as well. Going to add something to an upcoming sprint to investigate appropriate solutions.
