### ISSUE TITLE
Update not always visible due to caching in IE11

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1638]
### Description of problem

Updates might not be visible when visiting a cached report on IE11

### Version

2.0.1

### Steps to reproduce

1. Log in on FixMyStreet (I used https://beta.fixamingata.se/)
2. Visit an existing report through All reports
3. Make an update
4. Click on All reports and the body in question
5. Click on the report

### Actual results

After having performed Step 5, the update is *not* visible (Refreshing the page *will* display the update)

### Expected results

The update is visible after having performed Step 5, without having to refresh the page

### How reproducible

Seemingly always using IE11 (I could *not* reproduce the issue using Mozilla Firefox)

### Additional information

The time specified in the report list (after having performed Step 4) *does* reflect the update just made

**Comment by dracos** [comment]
Yes, I have replicated this. I assume this is down to IE11 too heavily caching ajax calls, it does not appear to call out to the server at all when fetching the report at your step 5. We'll have to add some "don't cache" statement to the JS report call, which is annoying!

**Comment by dracos** [comment]
I've got a PR for this at #1656 – do you want to try out that (tiny) change directly on your server and see if it fixes the issue for you, before I merge it?

**Comment by dracos** [comment]
Have merged/deployed and tested in IE11 on fixmystreet.com and it seems to be okay now.

**Comment by jonkri** [comment]
@dracos: Is it possible that this was also affecting the drop down menu for report states (that body users have access to when making updates)? We had a user reporting that he couldn't see the drop down menu when logged in on Internet Explorer, but that it worked when he switched browser. Thanks!

**Comment by dracos** [comment]
I guess if they had looked at the page before then logging in, then it could have been 'cached' by IE without having the dropdown on it, yes.

**Comment by jonkri** [comment]
@dracos: Thanks for the information! Is there a particular reason why you wrote 'cached' within single-quotes? If it is indeed the case that the paged was 'cached', is that considered to be a bug, then?

**Comment by dracos** [comment]
No, only to highlight it is a bug in IE with it overcaching. This would also be fixed by the same commit that fixed the initial report here.
