### ISSUE TITLE
Save with public update inspection fails

### ISSUE THREAD

**Issue by altinukshini** [mysociety/fixmystreet#1640]
I've replicated this problem many times. I was logged in as superuser (not council user), and tried to inspect a report, I checked the "Save with public update" and received this error below:

If I uncheck the "Save with public update", everything works fine!

[Fri Feb 10 16:09:09.849212 2017] [fcgid:warn] [pid 9026:tid 139948707485440] [client 127.0.0.1:49322] mod_fcgid: stderr: [error] Caught exception in FixMyStreet::App::Controller::Report->inspect "Can't call method "name" on an undefined value at /var/www/mywebsite.org/fixmystreet/web/../perllib/FixMyStreet/App/Controller/Report.pm line 416.", referer: http://mywebsite.org/report/13

**Comment by dracos** [comment]
Yes, currently inspection can't be performed by superusers as it is leaving an update using the user's associated body, which a super user doesn't have. It should presumably do _something_ and not error, we'll look into it, thanks.
