### ISSUE TITLE
FCA Feedback form

### ISSUE THREAD

**Issue by Rachelbaker78** [mysociety/fixmystreet#1643]
**They want to add a feedback form that sends feedback via email: (Approx 0.5 days work)** 
 They need to receive feedback from pages on the ScamSmart tool via email to a nominated address
 Atinuke.akintola@fca.org.uk

1.    The feedback form is a webform that was created by our Digital team on the fca.org.uk website. 
Our website is hosted on Drupal – this platform gives you the functionality to create forms such as these. We receive the feedback submissions by logging into Drupal admin pages, which we can then download into Excel.
2.    We track the submissions by reading through the Excel sheet for developing  themes on a weekly basis.
3.    We don’t collect personal information from respondents.
 
The form is designed as follows:
 
Did you find this page helpful? Yes / No
 
If users answer yes - What did you find helpful about this page? [Text field]
 
If users answer no – What can we do to improve pages like this? [Text field]
 
The form is entirely optional. Users can also answer Did you find this page helpful? without leaving comments on either of the other two questions, and these yes/no answers will still be counted.
 
Whichever platform the agency host the ScamSmart pages would possibly have a similar webform set-up to Drupal, though this depends entirely on what they use.
 
The layout of the form would also depend on what questions you would find useful from a ScamSmart point of view – perhaps you would like additional information that is better suited to the campaign.

_"1.    The feedback form is a webform that was created by our Digital team on the fca.org.uk website. Our website is hosted on Drupal – this platform gives you the functionality to create forms such as these. We receive the feedback submissions by logging into Drupal admin pages, which we can then download into Excel.
2.    We track the submissions by reading through the Excel sheet for developing  themes on a weekly basis.
3.    We don’t collect personal information from respondents.

The form is designed as follows:

Did you find this page helpful? Yes / No

If users answer yes - What did you find helpful about this page? [Text field]

If users answer no – What can we do to improve pages like this? [Text field]

The form is entirely optional. Users can also answer Did you find this page helpful? without leaving comments on either of the other two questions, and these yes/no answers will still be counted.

Whichever platform the agency host the ScamSmart pages would possibly have a similar webform set-up to Drupal, though this depends entirely on what they use.

The layout of the form would also depend on what questions you would find useful from a ScamSmart point of view – perhaps you would like additional information that is better suited to the campaign."_

**Comment by dracos** [comment]
I think this was meant for a different repo.
