### ISSUE TITLE
FCA: Re-direct an old video to a new location. 

### ISSUE THREAD

**Issue by Rachelbaker78** [mysociety/fixmystreet#1644]
"Please can you redirect our old Richard video to the new location. We’ve shared the original link with many partners and it is no longer working because we moved it to the video carousel."

 
Redirect this http://scamsmart.fca.org.uk/page/hear-richards-story to this http://scamsmart.fca.org.uk/case-studies/hear-richards-story

**Comment by dracos** [comment]
I think this was meant for a different repo.
