### ISSUE TITLE
Category entries are being translated upon submission report/new

### ISSUE THREAD

**Issue by altinukshini** [mysociety/fixmystreet#1646]
Issue seems to be with category named "Other", at least it doesn't happen with other names...

I've used change_category_text function on my cobrand module to translate categories and changed the templates/web/base/report/new/category.html to use the abovementioned function as follows:

    <option value='[% cat_op | html %]'[% ' selected' IF report.category == cat_op || category_lc == cat_op_lc || (category_options.size == 2 AND loop.last) ~%]>
        [% IF loop.first %][% cobrand.change_category_text(cat_op) %][% ELSE %][% c.cobrand.change_category_text(cat_op) | html %][% END %]
    </option>

Translation works well, but seems that the category "Other" when translated to "Tjera" in Shqip (sq), throws a validation error upon submission (bcs it is being translated, "Other" doesn't match "Tjera").

**Comment by dracos** [comment]
The new translation mechanism for category names should 'fix' this (in that you won't need to have special code to translate categories and this hopefully won't happen).
