### ISSUE TITLE
t filter not always respected

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1648]
### Description of problem

Reports not matching the <code>t</code> query parameter filter (for instance, filtering out older reports) are displayed when <code>status</code>, <code>filter_category</code> or <code>sort</code> query parameters are set "dynamically" (for instance, showing only reports in a certain category)

### Version

Presumably 2.0+; confirmed on 2.0.1 on FixaMinGata and 2.0.3 on FixMyStreet

### Steps to reproduce

1. Visit All reports
2. Click on one of the numbers, preferably for a body with relatively low numbers, such as the Older problems number in Adur District Council
3. Use the category dropdown to show only problems about some category, such as Abandoned vehicles

### Actual results

The reports displayed include problem reports that don't match the <code>t</code> filter (such as Older problems)

### Expected results

Only reports matching the category and the <code>t</code> filter are displayed, such as problems that are both older and in the Abandoned vehicles category

### How reproducible

Seemingly always, at least using Mozilla Firefox

### Additional information

Looking up the URLs manually does not produce the problem:

- https://www.fixmystreet.com/reports/Adur?t=older (3 problems, as expected)
- https://www.fixmystreet.com/reports/Adur?t=older&filter_category=Abandoned+vehicles&sort=updated-desc (0 problems, as aspected)

A problem that may have the same root cause occurs when you apply a <code>t</code> filter, visit a report and then press on of the back buttons. When this is done, only the relevant reports are displayed briefly, but after a short while reports not matching the filter show up.

This can be reproduced by visiting https://www.fixmystreet.com/reports/Adur?t=older, clicking on a report, and pressing the back button in the browser.

It might be that the JavaScript code doesn't take the <code>t</code> filter into consideration.

**Comment by dracos** [comment]
I noticed this today as well! :) Thanks for the detailed explanation, it does look like it isn't taking account of it in some way as you say.

**Comment by jonkri** [comment]
@dracos: Is https://github.com/mysociety/fixmystreet/pull/1689 related to this issue, perhaps?

**Comment by dracos** [comment]
That was about refetching reports when the map changed, I don't think it would have had any effect on this ticket.

**Comment by dracos** [comment]
If #1753 is done, this will be irrelevant.

**Comment by dracos** [comment]
It was done, there aren't 't' links any more.
