### ISSUE TITLE
Add value attribute to option tag in _inspect.html & category validation

### ISSUE THREAD

**Issue by altinukshini** [mysociety/fixmystreet#1650]
I think there should be a "value" attribute added to the option tag on line 43 in templates/web/base/report/_inspect.html

Not sure how validation is really processed in the back-end but if the value is missing, the content of the tag becomes its value. We're dealing here with reports being saved with a category that doesn't exist, exc upon submission while in different language (translated categories). 
Category validation is missing for this form too - It should have not allowed me to submit the form if the category doesn't exist/match, or should it? - Maybe because the report might have a category that was deleted in the meantime!?

**Comment by dracos** [comment]
The new translation mechanism for category names should 'fix' this (in that you won't need to have special code to translate categories and this hopefully won't happen).
