### ISSUE TITLE
User issue: can't review both the location and nature of the report at once via the questionnaire email

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1659]
> ## Your revised app processes

> I send in quite a high number of reports. Unfortunately, I think your revised follow-up email process is now much less User-Friendly. Whereas before I could review both the exact nature of the problem and its location, I can no longer do that. The result is that i am now responding less because I cannot be sure which problem or where it is that I am being asked about. To be honest, I understand the thinking behind the follow-up process but practically speaking its sometimes very difficult or even impossible to know whether something's been resolved. E.g. an over-flowing litter bin, or something I spotted whilst travelling. at the least, could I please have the old system of review as an option?

**Comment by dracos** [comment]
I don't understand the details of what this is referring to. If it's the move to HTML emails, they contain all the same information they used to, plus more (e.g. a map of the actual location). Do we have an example of what they are talking about, and what they actually think is missing?

**Comment by abimysoc** [comment]
I have asked the user, to see if we can get anything useful about what they think has changed.

**Comment by abimysoc** [comment]
No reply, thus closing as we have insufficient information to resolve. (Can always re-open or re-ticket if the user responds.)
