### ISSUE TITLE
Moderation sometimes doesn't give the user enough information

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1660]
When I moderate a report, the message displayed on the edited report is:

"Moderated by at [time]"

i.e. it doesn't say who moderated it. This isn't very transparent and as a result, I don't use the moderation features - instead I edit the report from the admin interface to be able to add a note like "this report has been edited by FixMyStreet admin to remove [whatever was problematic about it]".

I don't know why this happens but am hazarding a guess that it is because my user is not associated with any body? Displaying "Moderated by a FixMyStreet administrator" would be better in whatever the circumstances are, anyway!

**Comment by dracos** [comment]
Hazarded guess is correct; it assumes anyone using moderation has an associated body. Should be straightforward to sort.
