### ISSUE TITLE
Facebook login API stopped working?

### ISSUE THREAD

**Issue by altinukshini** [mysociety/fixmystreet#1681]
Did Facebook API change or something? The Facebook login stopped working, and I continue to get these Internet Glitch errors on FMS.

How do I debug this furthermore? Apache logs don't seem to be helpful!

Thanks!

**Comment by davea** [comment]
Yes, it appears that the currently used version of the `Net::Facebook:Oauth2` module is [using version 2.2](https://github.com/mamod/Net-Facebook-Oauth2/blob/0.09/lib/Net/Facebook/Oauth2.pm#L11-L12) of the Facebook Graph API which was switched off on March 25th (per [Facebook's deprecation timeline](https://developers.facebook.com/docs/apps/changelog)).

An updated version of the module has been [released on CPAN](https://metacpan.org/pod/Net::Facebook::Oauth2) which should fix the issue. We'll commit a fix to FixMyStreet shortly, but in the mean time you can install version 0.10 of `Net::Facebook::Oauth2` to resume Facebook logins.

**Comment by altinukshini** [comment]
@davea  thank you for the quick reply! I'm not very familiar with cpan and catalyst either, how do I upgrade a lib? 

Can I upgrade like this?

    $ cpan upgrade Net::Facebook::Oauth2

**Comment by davea** [comment]
Once the PR to fix this has been merged (hopefully in the next day), you'll be able to run `./bin/install_perl_modules` to get the latest version of the module.

If you need the fix before then, run `./bin/cron-wrapper ./bin/cpanm M/MA/MAMOD/Net-Facebook-Oauth2-0.10.tar.gz` to install the update.
