### ISSUE TITLE
Greenish pictures in reports list

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1690]
A user reported seeing some pictures as green on FixaMinGata:

![greenish](https://cloud.githubusercontent.com/assets/777056/25040034/525b5ac8-2107-11e7-9a45-a92ce1e6a3c3.png)

Unfortunately, I couldn't reproduce the problem when I visited the same page (I tried both Firefox and Internet Explorer 11), but I figured it would be best to report it anyway.

**Comment by zarino** [comment]
I wonder whether this was something about a poor internet connection, causing some of the images to be only _partially_ downloaded by their browser (the monochrome green "Staket skymmer" photo in particular looks like a normal photo with the Red and Blue channels stripped out).

**Comment by dracos** [comment]
Yes, sorry, no idea what this could be.
