### ISSUE TITLE
Pin visibility problem

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1691]
I have failed to reproduce this problem, but I figured that I would share the information I have with you.

Upon opening the list of new reports, the pins were not visible:

![no_pins](https://cloud.githubusercontent.com/assets/777056/25040868/67272d88-210c-11e7-8a60-3dae8efff30c.png)

Clicking on a report in the list revealed that one pin:

![no_pins2](https://cloud.githubusercontent.com/assets/777056/25041014/45cedf68-210d-11e7-9af4-95ad16a3c95f.jpg)

Zooming in did not initially cause the pin to disappear:

![no_pins3](https://cloud.githubusercontent.com/assets/777056/25041016/49522b22-210d-11e7-8307-26a951483605.jpg)

Zooming in further did cause the pin to disappear:

![no_pins4](https://cloud.githubusercontent.com/assets/777056/25041022/4ce13bd4-210d-11e7-9482-63c1ceacc1a1.jpg)

Clicking on the pin shadow caused the pin to be visible again:

![no_pins5](https://cloud.githubusercontent.com/assets/777056/25041026/4fb8e104-210d-11e7-85f6-dd52e01d975a.jpg)

The user in question is using Internet Explorer. Unfortunately, I do not know which version.

**Comment by jonkri** [comment]
@dracos: Perhaps this issue can be closed for the same reason as #1738?

**Comment by dracos** [comment]
Sure!
