### ISSUE TITLE
Always URL encode Open311 parameters

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1692]
A company that is working on integrating the Open311 extensions with FixaMinGata reported that their web server is interpreting the <code>+</code> character in query parameters as spaces.

As a result, the date string <code>"2017-01-01T00:00:00+01:00"</code> was interpreted as <code>"2017-01-01T00:00:00 01:00"</code>. When I manually converted the <code>+</code> character to <code>%2B</code>, their software could process my query.

I don't know what web server or framework the company is using.

It seems like some HTML standards specifies that application/x-www-form-urlencoded query strings defines <code>+</code> as meaning space, and even though this is not the encoding used when making GET requests, perhaps it would be safer to just always encode parameters (no matter which HTTP method is used), as it shouldn't do any harm (unless some FixMyStreet implementations are relying on it not being URL encoded), as it may increase interoperability.

What do you think?

Thanks!

**Comment by dracos** [comment]
Their behaviour is correct, that is the encoding used when making GET requests, and our code should already be escaping `+`as `%2B`. Could you be more precise as to which part of FixMyStreet is generating a query containing an unescaped `+`? The GetServiceRequestUpdate code seems to use UTC:

```
§ bin/cron-wrapper perl -M5.14.0 -MOpen311::GetServiceRequestUpdates -e '
my $o = Open311->new(endpoint => "http://example.com", test_mode => 1, test_get_returns => {});
my $u = Open311::GetServiceRequestUpdates->new;
my $b = FixMyStreet::DB->resultset("Body")->new({});
$u->update_comments($o, $b);
say $o->debug_details . "\n"'

request:http://example.com/servicerequestupdates.xml?api_key=&end_date=2017-04-30T09%3A28%3A04Z&start_date=2017-04-30T07%3A28%3A04Z
```

And even if I force a time zone, it seems to escape correctly:
```
§ bin/cron-wrapper perl -M5.14.0 -MOpen311::GetServiceRequestUpdates -e '
my $o = Open311->new(endpoint => "http://example.com", test_mode => 1, test_get_returns => {});
my $n = DateTime->now(time_zone => "Europe/Stockholm");
my $d = DateTime::Format::W3CDTF->format_datetime($n);
$o->get_service_request_updates($d, $d);
say $o->debug_details . "\n"'

request:http://example.com/servicerequestupdates.xml?api_key=&end_date=2017-04-30T11%3A31%3A14%2B02%3A00&start_date=2017-04-30T11%3A31%3A14%2B02%3A00
```

It is certainly possible it's missed it somewhere, but we'll need more information to find out where.

**Comment by jonkri** [comment]
Thank you, @dracos! I seem to have made a mistake here - FixMyStreet indeed seems to be escaping these characters correctly. I apologize! I'm closing the issue.

**Comment by dracos** [comment]
No worries!
