### ISSUE TITLE
Option to hide map markers for fixed problems

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/fixmystreet#170]
Email from user:

I'm often interested in looking at unfixed problems in my local area, either to mark them as fixed if they've been addressed, or think about contacting the council if they still need action to be taken.

The full map of all reports is very cluttered -- see eg http://www.fixmystreet.com/around?all_pins=1&no_pins=&zoom=2&lat=52.41385&lon=0.74507&pc=thetford&layers=BT -- and I'm often only interested in problems that aren't marked as fixed.

To this end, it would be very useful if there was a toggle button (similar to the existing show/hide stale reports one) that would allow problems marked as "fixed" to be shown or hidden from the map view.

**Comment by Gemmamysoc** [comment]
User feedback:

"Hi there i am a little confused as i keep seeing problems put down
as being fixed on the site but the pointers do not seem to go just
more on top of each other, some of the pointers have been fixed for
over 6 months but are still cluttering the site and making it look
like no one is bother, my self i think this site is good but still
has a lot of hiccups"

**Comment by Gemmamysoc** [comment]
Similar user suggestion:

"I was wondering if there was a way that you could include different
icons for if a problem is fixed and potentially red markers for when
a problem hasn't been fixed for a long time? Would it also be
possible to hide fixed reports to de-clutter the map?"

**Comment by Gemmamysoc** [comment]
User suggestion: 

"Is it possible to display the yellow markers for solved problems in a different colour? If not, I think it would be a good feature to add"

**Comment by dracos** [comment]
You can select unfixed/closed/fixed reports using the dropdown for a while now.
