### ISSUE TITLE
Hide old pins - not showing 

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1703]
I'm on Firefox 53.0.2 and I don't see the little black 'hide pins' / 'show old' etc bar any more.

![fireshot screen capture 1105 - viewing a location __ fixmystreet - www_fixmystreet_com_around_pc bn2 0eh](https://cloud.githubusercontent.com/assets/944656/26147560/dbbb5d38-3aeb-11e7-9367-f22f996436d2.png)

**Comment by abimysoc** [comment]
For a counterpoint: I have the same browser version and the black bar is present and correct (this is, however, on Ubuntu).

**Comment by MyfanwyNixon** [comment]
I am on Windows 10.

**Comment by zarino** [comment]
"Show old" and the black bar appear fine for me in Firefox 53 running under Windows 8.1 on Browserstack:

![screen shot 2017-05-17 at 10 48 21](https://cloud.githubusercontent.com/assets/739624/26148404/73404e50-3aee-11e7-9e33-0834fc506437.png)

@MyfanwyNixon If you right click on the page, select "Inspect", and then select the "Console" tab, and reload the page, do you see any javascript errors?

**Comment by MyfanwyNixon** [comment]
It is BACK! :O 

I guess it was a minor blip.

![fireshot screen capture 1106 - viewing a location __ fixmystreet - www_fixmystreet_com_around_pc pe21 7ej](https://cloud.githubusercontent.com/assets/944656/26148698/81c7ba0c-3aef-11e7-92d9-ced30fc735c6.png)
