### ISSUE TITLE
FMS.com "down for maintenance" page looks pretty shonky

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#1710]
This page doesn’t get displayed for long, but if anyone sees it, I'm not sure it'd instil much confidence:

![screen shot 2017-05-23 at 11 26 13](https://cloud.githubusercontent.com/assets/739624/26350425/04936dd6-3fab-11e7-96a1-cad7baecd05d.png)

Given FMS is a mySociety product, we _could_ just re-use [the existing “Oops! You caught us!” page](https://github.com/mysociety/maintenance/blob/master/index.html):

![screen shot 2017-05-23 at 11 30 05](https://cloud.githubusercontent.com/assets/739624/26350468/3380ab54-3fab-11e7-908e-85c66d83988c.png)

Or we could even tweak it to have an FMS logo and yellow/black colour scheme!

**Comment by jukesie** [comment]
I'd go with the tweaked version - FMS logo and colour scheme and @fixmystreet and /fixmystreet for the links?

**Comment by dracos** [comment]
![screen shot 2017-05-31 at 18 40 54](https://cloud.githubusercontent.com/assets/154364/26645651/b9910d5c-4630-11e7-9f47-a94f7fb01b6d.png)

**Comment by zarino** [comment]
ZOMG I love it!

**Comment by dracos** [comment]
This is deployed, though when I deployed the site it was too quick and I didn't see it.
