### ISSUE TITLE
Partial map pins

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1738]
Perhaps related to #1691 (and maybe also #1591, and #1690), the same FixaMinGata user reported seeing only partial pins, like so:

![partial map pins](https://user-images.githubusercontent.com/777056/27681966-348b2d3e-5cc1-11e7-8073-15ea894df0af.png)

The user says that he has encountered problems with images (I'm not sure which images) loading incorrectly both from his home and work computer, and on his iPhone.

Perhaps FixaMinGata's proxy configuration has a problem or something, if this looks unfamiliar.

**Comment by dracos** [comment]
That screenshot to me looks like the pin image has half loaded. I can't see that anything FixMyStreet related could possibly cause that. It certainly sounds like an issue with their connection or some interaction between their connection and your server.
