### ISSUE TITLE
"Which report is it a duplicate of?" list doesn't always load

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#1803]
I noticed on [this report](https://fixmystreet.oxfordshire.gov.uk/report/1090325) that the JS that loads in the list of potential duplicates is loading an [invalid URL](https://fixmystreet.oxfordshire.gov.uk/report/1090325%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2007817578766%20%20%20%20%20%20%20%20%20%20%20%20/nearby.json?filter_category=Carriageway+Defect&latitude=51.871885&longitude=-1.47929).

**Comment by dracos** [comment]
Fixed by e10791e6c40d872b15b21a96f5fac2d0f82fbd85
