### ISSUE TITLE
Map controls no longer working

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1822]
I can't pan or zoom using the map control buttons. Interacting with any of them is interpreted as a map click to start a new report.

Click-and-drag to pan the map / middle-button-scroll to zoom both working fine, as are the show/hide and permalink buttons.

Observed in Firefox 55 and Chrome 56.

**Comment by dracos** [comment]
Don't think anything has changed, and it's okay in Chrome (60) and Firefox 55 for me:
![Chrome 60](https://user-images.githubusercontent.com/154364/29774797-c0b46768-8bfa-11e7-921d-b067e0068adb.gif)
Odd.

**Comment by abimysoc** [comment]
Possibly the same problem observed by a user:

> In latest Firefox on WIndows when I try to zoom with + - or use the arrow overlays then the map simply scrolls the content down to bottom right

**Comment by dracos** [comment]
Just to confirm FF on Win okay here:
![ffwin_sm](https://user-images.githubusercontent.com/154364/36377769-316c0ae8-1570-11e8-84fe-de7b7aeb94db.gif)

**Comment by abimysoc** [comment]
Same user followed up to say it also occurs in Chrome for them, so again it seems to be something about the device rather than the browser.

**Comment by tomoccscholes** [comment]
Seems to still be an issue. Not happening on Chrome on my iMac. But replicatable on Chrome 65 on two different Windows 10 machines. Let me know there is anything I can do to dig into the issue for you.
