### ISSUE TITLE
Appended text in problem form

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1854]
When trying out FixMyStreet 2.2, we experienced some text being appended to the form fields in the problem reporting form. Here is a picture that illustrates the problem:

![update_problem_fields](https://user-images.githubusercontent.com/777056/30774776-88679432-a088-11e7-9576-1a544e75543a.png)

The problem seem to occur when logged in, from the `update_problem_fields` method in staff.js.

Is this the intended behavior (sorry - *behaviour* ;))? Have I missed a step or two somewhere? :)

Thanks!

**Comment by dracos** [comment]
Ah, sorry - here in one council in the UK, for users with the `Manage shortlist` permission, this was something to enable quicker reporting of similar issues by pre-filling the title/detail fields. This should be behind some sort of per-cobrand configuration as it may not be wanted (and certainly, hasn't been translated).

**Comment by dracos** [comment]
Until a config hook is added, you should be able to work around this by, in your own JavaScript loaded at some point after staff.js, setting `fixmystreet.hooks.update_problem_fields = null;` (which will just remove the function adding this text). Hope that's helpful.
