### ISSUE TITLE
Two update-leaving bugs in the category change feature, plus blank updates in email

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1857]
I have a question about the (terrific) new feature letting us body users change the category of a problem.

When trying out the feature, I posted an empty update like this ("Save with a public update"):

![change category 1](https://user-images.githubusercontent.com/777056/30926866-d7b93564-a3b6-11e7-93c3-1de484f94059.png)

When I submitted the form, I got an error message letting me know that I should provide a public update, which I guess is appropriate. :)

![change category 2](https://user-images.githubusercontent.com/777056/30926873-e3349b7c-a3b6-11e7-9333-b6817dfc4c55.png)

However, I could, when I refreshed the page, see an update signaling that the category had changed, even though the category change had not actually been carried out (the category remained "Park").

![change category 3](https://user-images.githubusercontent.com/777056/30926886-e97bca64-a3b6-11e7-81f2-dff6745142c7.png)

Have I made a mistake setting this up, or am I misunderstanding something? Or is this perhaps a bug?

When I unticked the "Save with a public update" checkbox, the textarea for the update disappeared, and I could make the category change by submitting the form. However, this time around, I noticed two updates: one regarding the category update, and one empty update.

![change category 4](https://user-images.githubusercontent.com/777056/30926889-ef17d210-a3b6-11e7-8e6b-00f72eaf82f9.png)

Could it be that the last (empty) update is redundant, and could have been left out?

Thanks! :)

**Comment by dracos** [comment]
"Have I made a mistake setting this up, or am I misunderstanding something? Or is this perhaps a bug?" - certainly looks to be a bug, it will make an update for a category change even if the category change then doesn't go ahead due to other errors.

And yes to your other comment as well, it looks like it leaves two updates if you submit that form *and* change the category, which seems a bit superfluous!

Thanks for pointing these out.

**Comment by jonkri** [comment]
Oh, I just noticed one more thing!

In the notification e-mail that goes out, the empty updates are included, like so:

![change category 5](https://user-images.githubusercontent.com/777056/30927187-f9a66196-a3b7-11e7-8080-12680df59484.png)

**Comment by dracos** [comment]
Oh dear! I swear I remember that being spotted and dealt with, but I can't find anything doing that now.

**Comment by jonkri** [comment]
Oh. :) We're using the commit of the 2.2 tag, by the way!

**Comment by struan** [comment]
Both these are now fixed as of 31b8008
