### ISSUE TITLE
Error in RSS feed - malformed XML

### ISSUE THREAD

**Issue by jukesie** [mysociety/fixmystreet#1859]
Bug report via user support email: 

there’s a new parsing error for my own local postcode. See here:
https://www.fixmystreet.com/rss/pc/SG36JW
 
Putting the results through an XML validator says:
Line 105: The entity "rsquo" was referenced, but not declared.
 
The offending line: <title>Door dumped in bush near footpath. Council cut bush around it 2 week&rsquo;
 
XML doesn’t like HTML entity codes, they need to be escaped or converted.
 
I’m wondering if your RSS generator has always had this issue or if it was introduced in your Sep update of your code?
 
I would be grateful if it can be fixed as I’m sure it will impact feeds for other postcodes where similar text is encountered.

**Comment by dracos** [comment]
We're doing HTML entity escaping, when in XML we either need to use numeric entities, or don't bother escaping anything bar the minimal required escaping. This looks to have always been an issue, nothing new I can see in this code.
