### ISSUE TITLE
Add configuration option to show staff user name as well as body name

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1860]
I'm wondering about the purpose of `$can_view_contribute` (`$c->user_exists && $c->user->has_permission_to('view_body_contribute_details', $self->problem->bodies_str_ids)`) in Comment.pm. What is the rationale behind only displaying the name of the user if this condition is fulfilled?

Thanks!

**Comment by dracos** [comment]
If an update is left by a staff user, then that update is displayed by default with the name of the body, rather than the name of the user. If the logged-in user has the `view_body_contribute_details` permission, then that staff user can also see the name of the staff user.

**Comment by jonkri** [comment]
Ah, "staff user" - I've been wondering what to call that in English. :)

We are considering to show the names of staff users. I guess we could just put a FixaMinGata if statement in there, in that case?

Thanks! :)

**Comment by dracos** [comment]
It'd be best if there was a cobrand function that could be called providing a configuration option for whether this happens or not.

**Comment by jonkri** [comment]
Ah, I see. We have actually also been discussing, very briefly, about perhaps making sure staff updates are never anonymous. I'll investigate where we stand and will report back on this. Thanks!

**Comment by jonkri** [comment]
Hi, again!

We have decided *not* to make a change related to how staff updates work, in terms of anonymity.

However, it would be great if there was a configuration option for whether or not to display the staff user name in addition to the body name. :)
