### ISSUE TITLE
"2x" sprites

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1861]
The site logo (both on FixaMinGata and FixMyStreet) is looking a bit blurry on HiDPI displays. Perhaps a "2x" version of the sprite.png image should be used for high-resolution devices.

(Also, should perhaps the image be called "sprites.png" instead, assuming a sprite is an independent part of an image consisting of multiple images?)

**Comment by dracos** [comment]
Hi - as you can see from #1888 we decided instead to drop the sprite! We factored your logo out of it as part of this to its own file, so it should be much easier to supply a 2x version of this if you like (or ideally, an SVG that would work at any DPI, as you can see we've done for the .com logo). Please feel free to supply one, but I'll consider this closed as the sprite doesn't exist any more.

sprite/sprites - they were called sprite images in old computer games that used the same technique, which is I guess where the name came from; the sprite being the composite of all the smaller images.
