### ISSUE TITLE
Question: What determines the "Problem" pin colour?

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1862]
Hi!

We're considering changing the colors of our map pins, like so:

    sub pin_colour {
        my ( $self, $p, $context ) = @_;
        return 'green' if $p->is_closed;
        return 'green' if $p->is_fixed;
        return 'yellow' if $p->is_in_progress;
        return 'red';
    }

These new colours work as expected in the "About" view:

![yellow](https://user-images.githubusercontent.com/777056/31027272-ef022eee-a549-11e7-9795-30e4e440098b.png)

However, if I click on the yellow pin, the "Problem" view opens up, and here the pin is red:

![red](https://user-images.githubusercontent.com/777056/31027296-fdd5bf80-a549-11e7-86a6-4c62ddb33c3b.png)

What determines the colour of a pin in the "Problem" view?

I expected the colour of the pin to match the colour of `pin_colour`, and the "Around" view.

Thank you!

**Comment by dracos** [comment]
I can't reproduce this, I'm afraid; e.g. https://beta.fixamingata.se/around?lat=57.753192&lon=12.046498&zoom=3&js=1 has three pins and all retain their colour when clicked. The pin on around page (Around.pm) and report page (Report.pm) both use `pin_data` – which uses `pin_colour` – to set the pin colour, so they should always be the same.

**Comment by jonkri** [comment]
How odd, I can't reproduce it now either...

I even had the developer tools opened and <kbd>Ctrl + Shift + R</kbd> refreshed (in Firefox), and still, for some reason, saw the wrong pin color.

Thanks for the information! I'm closing the issue.
