### ISSUE TITLE
Problem report scroll offset on narrow browsers

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1863]
If a staff user visits a problem report with a narrow browser width (like with a mobile browser), the site is automatically scrolled quite far down, like so:

![scroll](https://user-images.githubusercontent.com/777056/31047182-1349b9e0-a606-11e7-94ea-0aeec60e4cde.png)

Is this intentional?

While it makes an update more efficient to make, the user has to scroll up quite far in order to see the map and the information reported by the user.

Thank you!

**Comment by dracos** [comment]
What it is *meant* to do is scroll a logged in inspector to the top of the blue 'inspect' form, where it gives the place they can make changes and things most easily, and not much scroll up to see the details if they do need to do that. I can see in FF it is scrolling much too low, not sure why that is happening just yet.

**Comment by dracos** [comment]
Ah so it is the hiding of the 'normal' update form happening after the scroll has happened that is causing the issue. The form should be hidden on load if it's being hidden, not after the fact, so I'll look at fixing that.

**Comment by jonkri** [comment]
That's great, thank you. :)

**Comment by jonkri** [comment]
@dracos:

After having discussed this at FixaMinGata, we concluded that we would like the problem page to be displayed without any initial scrolling, so that the user can see the information about the report immediately when visiting the page, and then scroll down to the inspector when needed instead.

Do you think this is something that could be possible to change, or do you think that it would be preferable to have a cobrand option for this?

Thank you!

**Comment by dracos** [comment]
Yeah, making it a cobrand option should be doable!

**Comment by dracos** [comment]
If your cobrand defines the `fixmystreet.inspect_form_no_scroll_on_load` variable to be true, it should no longer scroll when it loads.

**Comment by dracos** [comment]
The way other cobrands have custom JS is to have a `templates/web/*/footer_extra_js.html` file that adds a cobrand JS file (see the existing examples).
Then that file could contain `fixmystreet.inspect_form_no_scroll_on_load = 1;` and that should be all you need.
