### ISSUE TITLE
Should staff users be able to hide reports?

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1878]
In v1.8.2, staff users can't seem to hide reports. However, when trying out v2.2, we noticed that the "hidden" state is now seems to be available in the dropdown menu for body users.

Is this intentional? If so, is there a way to deactivate it, in case we don't want this change?

I think we want only admin users to be able to hide reports on the site.

Thank you!

**Comment by struan** [comment]
I'm afraid that at the moment there's no way to stop staff users from hiding a report.

The way to fix this would be to add a new permission for hiding reports, and only allow staff with this permission to hide reports.

**Comment by dracos** [comment]
There's plenty of ways :) The most obvious would be to override the `state_groups_inspect` function in your cobrand, to be the same except without hidden.
Perhaps this should be the default unless the staff user also has the 'moderate' permission (which carries with that feature the ability to hide the report). I'll check with our main council user in the UK to see whether they would mind that.

**Comment by jonkri** [comment]
Thanks @struan and @dracos! I look forward to hearing the thoughts of the main council user. :)

**Comment by dracos** [comment]
Yeah, I'm just going to remove hidden as a state for that dropdown; someone with moderate permission can use moderation to hide it, so there's no need for the option here. Thanks for suggesting it. PR at #1879

**Comment by jonkri** [comment]
@dracos: Do you have any suggestions on what would be a clean way way to hide a state in the cobrand file? We would like to have "internal referral" as a state (since integrations may use it), but are interested in hiding it from staff users. I see an example of how the categories can be defined in Oxfordshire.pm, but I was thinking of something that re-uses the subroutine in Default.pm and is a bit more DRY.

**Comment by dracos** [comment]
You can call the parent function with e.g. `my $states = $self->SUPER::state_groups_inspect`, so you could do that and then filter the result. The structure isn't great for this, a bit fragile, but I imagine it would be something like the following (untested!), assuming you have a fixed state:
```
my $states = $self->SUPER::state_groups_inspect;
$states->[2] = [ grep { $_ ne 'internal referral' } @{$states->[2]} ];
return $states;
```
Could put some checking in that it's looking at the right thing first before changing anything to catch any changes, but it's harmless if it fails, I guess.

**Comment by jonkri** [comment]
Thanks, @dracos. :)

**Comment by jonkri** [comment]
@dracos:

When I'm trying this code...

```perl
sub state_groups_inspect {
    [
        [ _('Open'), [ 'open', 'action scheduled', 'in progress', 'investigating' ] ],
        [ _('Fixed'), [ 'fixed - council' ] ],
        [ _('Closed'), [ 'duplicate', 'not responsible', 'unable to fix' ] ],
    ]
}
```

... I'm getting the following menu (where Öppen appears as the first entry, and then Open appears again as a category):

![states](https://user-images.githubusercontent.com/777056/38361677-7c9ee798-38ce-11e8-86fc-a2fce57063a0.png)

Do you know why the "Open"/"Öppen" state behaves this way?

We have state categories for open/Öppen, closed/Stängd and fixed/Löst.

Thanks for any information that you can provide!

**Comment by dracos** [comment]
The default open state (that always exists) is `confirmed`, not `open`. `/admin/states` is a bit confusing by saying open, but I guess that was thought to be clearer that it is the 'open' state as opposed to the 'closed' one.
