### ISSUE TITLE
Problem executen installation instructions

### ISSUE THREAD

**Issue by MickeyBG** [mysociety/fixmystreet#1886]
When i try to install manually the fixmystreet app when i run the sentence bin/install_perl_modules i have the following error ¿any idea?
Thanks

![sin titulo2](https://user-images.githubusercontent.com/33069568/32200539-7423a56c-bdd2-11e7-8cf6-5cf8e29d3302.png)

**Comment by dracos** [comment]
Sorry about that; it looks like an upgrade to Module::ScanDeps should fix this, and we didn't spot this because Travis already had M::B::ModuleInfo installed (I think that's the reason, anyway). Will hopefully test/push a fix in the next couple of hours, thanks for letting us know!

**Comment by dracos** [comment]
I've pushed a fix for this, do let me know if it works/doesn't work for you.
