### ISSUE TITLE
[UK] Investigate whether sprite.png is still worth including

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#1888]
Over time we’ve used more and more image assets on FMS.com that aren’t part of `web/cobrands/fixmystreet/images/sprite.png`.

We should investigate how much of `sprite.png` we’re actually still using, and either: ditch `sprite.png` and just use individual image files; or make an effort to include all the image assets into the sprite, perhaps with it being auto-generated and auto-referenced in the CSS, to reduce the chance of us getting into this same position in a few years’ time.

**Comment by zarino** [comment]
See also https://github.com/mysociety/fixmystreet/issues/1861

**Comment by zarino** [comment]
`sprite.png` (via the `$image-sprite` variable) is used for:

* The "FixMyStreet" logo for `#site-logo` in default cobrand (but not fixmystreet.com, where we override it with base64 encoded data URI).
* IE7 fallback for the base64 encoded logo on fixmystreet.com.
* Large version of the logo for `#site-logo` on fixmystreet.com homepage.
* The "abuse", "feed", and "close" icons in the `#key-tools` bar at the bottom of map list pages (but not the "share" or "problems nearby" chevron icons).
* IE8 fallbacks for the base64 encoded SVGs in `.button-fwd` and `.button-back`. (`.button-fwd` is a trigger to reveal the "rap-notes" problem reporting sidebar when it’s automatically collapsed out of view on mobile. `.button-back` doesn’t seem to be used anywhere.)
* Pan/Zoom controls on the map page.
* "Hide pins" / "Show old reports" etc icon in the `#sub_map_links` on the map page.
* Magnifying glass icon in the top right corner of `.update-img` images.
* The little "up" chevron icon that lets you return to the map view from the reporting form, on mobile.
* "Close" icon on `.promo` elements (not sure whether these are _actually_ used anywhere?)
* The white pin icon on the "fixed" / "closed" etc banners that peek over the edge of report page sidebars.

Looks like FiksGataMi and FixaMinGata have customised their own copies of `sprite.png`, to swap in their own logos, in place of the FixMyStreet one.

There are a bunch things inside `sprite.png` that _aren’t_ used any more, including the various app store logos / buttons, and a few little arrows and stuff.

Since every cobrand inevitably replaces the FixMyStreet logo with their own, I’d be tempted to stop using `sprite.png` for the `#site-logo`, and instead use a stand-alone image file (or inline SVG, or whatever!).

Makes sense for the Pan/Zoom buttons to all be in a sprite together, since they always appear on the same page as each other, they’re thematically linked, and it’s very unlikely that someone would want to modify the image used on one button without also changing all the others to match.

Similarly, it makes sense for the small icons used in the `#key_tools` buttons to maybe all reside in their own little sprite, since they’re of similar dimensions and a similar theme. But I'm aware we have _loads_ of little icons that go in buttons all over the site which _aren’t_ currently part of a sprite. Perhaps we should standardise – either start spriting these little icons together, or just always use separate image files.

**Comment by dracos** [comment]
"Close" icon on .promo elements (not sure whether these are actually used anywhere?) <-- no, and the related CSS is scheduled for removal in #1893.

**Comment by dracos** [comment]
Since every cobrand inevitably replaces the FixMyStreet logo with their own, I’d be tempted to stop using sprite.png for the #site-logo, and instead use a stand-alone image file (or inline SVG, or whatever!). <-- now #1887 done, should be possible to adapt some of that for base stylesheet, so easier to override.

**Comment by zarino** [comment]
Ok, after a chat with @dracos, we’re going to split up the `sprite.png` into individual image files, and where possible, have an `@1x` PNG and an SVG for each. We don’t really load enough icons to make the performance improvement of a sprite outweigh the maintenance burden.

The plan of action is:

1. `fixamingata` and `fiksgatami` have forked the core sprite file – just to override the logos, I think. For each of them:
   * Move the site logo out into a separate file.
   * Check they’ve not customised anything else in their fork of the sprite.
   * Assuming they haven’t, delete their fork of the sprite. It won’t be needed any more.
2. Break up the core sprite – Find where the core sprite has been referenced in the code (a grep for `url[(]([$]image-sprite[)]` will do it) and, for each result:
   * Identify which icon from the sprite is being referenced.
   * Break the icon out into its own `@1x` PNG file. At this point it might be worth redrawing the icon in such a way that we can _also_ export an SVG version, to save doing it later.
   * Use judgement about splitting/combining icons – there might still be cases where a _small_ sprite of related icons makes sense (eg: the pan/zoom controls).
3. Final check for SVG opportunties – Find any PNGs that don’t have an SVG alternative (a grep for `url[(].+[.]png[)]` is a good start) and, where sensible, consider redrawing any lonesome PNG icons so we can also export an SVG version.

At the end of all that, we’ll have:

* Removed `sprite.png` and its fixamingata/fiksgatami cousins.
* Added high-dpi support for pretty much all UI elements.

It sounds arduous, but there aren’t actually _that_ many background-image rules in the fixmystreet sass files—maybe 60 or so—many of which we can safely ignore right now, because they have nothing to do with the sprite and aren’t core UI controls.

If we run out of time, we can stop after step 2 ;-)
