### ISSUE TITLE
Check and deploy new Privacy Policy

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1900]
I've started drafting amendments to the existing Privacy Policy in accordance with the GDPR requirements. Please see initial copy here: https://docs.google.com/document/d/1Wl6qSuGAYjC5kiyhpUA2x03uAMfvltNeP2DTgmUAlzc/edit# (document is only accessible to mySoc staff).

New text is in blue, and the clauses which each piece of text are attempting to satisfy are in quotation marks in the comments. There are still some areas open to debate (not to mention areas where I've made an educated guess about what we collect/what we do with it), so please weigh in.

This copy covers Research as well as Communications and Better Cities, plus there's quite a bit on our direct marketing so @jukesie @davideaton2 @Rebeccarumbul may wish to assess/comment/amend (plus your teams).

**Comment by jonkri** [comment]
Hi!

Curious question:

Have you thought about periodic weeding and destruction of records, related to GDPR, and how this might apply to FixMyStreet?

Thank you!

**Comment by MyfanwyNixon** [comment]
Hi @jonkri 

We've thought about it a lot, yes! 

For users' personal details: FixMyStreet is a site based on user accounts, and we believe that the need for retention periods doesn't apply to this data. As with any other account-based system, users can terminate their accounts when desired, but until they do we think they have the right to retain their log-ins and reports on the site. GDPR talks about not retaining personal data for longer than is required to perform the task in hand, but it is well within FixMyStreet's remit that users may expect to be able to log in and view their reports, or update them, even several years after they are made.

When it comes to the reports themselves: The ICO in the UK states that requests for erasure may be turned down when personal data is processed for archiving purposes in the public interest, scientific research, historical research or statistical purposes. 

Historic FixMyStreet reports provide an invaluable resource for researchers into the quantity and type of street problems made across the UK during the years the site has been running. This research can help inform civic planners, developers, coders, historians and social scientists, among others.

Of course, in line with GDPR requirements, if any user wishes us to remove their personal data we will do so on request. This will ordinarily retain the content of the actual reports, but remove any link to their personal details. 

That's our thinking at the moment, anyway - did you have any thoughts yourself?

**Comment by dracos** [comment]
I also plan to add a script to delete old unconfirmed reports etc, assuming they're no longer necessary.

**Comment by jonkri** [comment]
Hi @MyfanwyNixon and @dracos!

Thanks for the information!

We do have some thoughts:

We think that keeping reports on the site is in the public interest, but we do not see a strong enough need for personal details when the report is fixed. In our view, the report should be unidentified when it is fixed.

We are also wondering if there is a rationale behind (ever) showing the name of the user publicly on the site. And if this should be an option, if perhaps it should not be the default option (be opt-in rather than opt-out).

Is it possible that the privacy policy document in progress could be shared with us?

Also, are there any thoughts about raising the question of GDPR and the FixMyStreet platform in some (other) way so that other countries could also provide input? We think that might be helpful for the whole FixMyStreet community, and provide valuable feedback to the process.

Thank you!

**Comment by dracos** [comment]
@jonkri I think every site will need to decide upon its own privacy policy, based upon their own specific requirements. If you want to write a script that can run from cron that anonymizes fixed reports, happy to have that in the repo, of course :)

The decision for public ownership of reports was deliberate, yes, as part of the site hopefully being a community tool - see e.g. https://github.com/mysociety/fixmystreet/issues/374#issuecomment-36836364 . But again, this could of course be a configuration option as to what the defaults are (would make it easy for us to change if we wanted to, too).

I don't see any reason for the privacy doc not to be shared, I'll take a look, it might even be ready to go live on our site soon. I could certainly post to the list and write about it, along with the variety of privacy-related things included in https://github.com/mysociety/fixmystreet/releases/tag/v2.3.1

**Comment by jonkri** [comment]
Speaking of anonymization scripts: Is it possible to get the time when a given user was last active (like, requesting a page while logged in)? If not, can we see when a given user last authenticated? Thanks!

**Comment by dracos** [comment]
We don't record that information explicitly. It looks like Catalyst sets a `__created` flag in session data when a new session is created, and the `expires` time is updated on each request to extend the session duration, so you could potentially work out 'last page viewed' from that, if you mapped users to sessions. But nothing explicit, no.

**Comment by jonkri** [comment]
@dracos:

Hmm... Does this mean that there is no way to determine which user relates to a given session?

Also, is there some way to tell when an account was created?

Thank you!

**Comment by dracos** [comment]
@jonkri You can go from a session ID to the user ID of that session with something like:
```
my $c = FixMyStreet::App->new();
my $session = $c->get_session_data("session:SESSIONID"))';
print $session->{__user}{id};
```
That `$session` also contains the `__created` and `__updated` I mentioned above.

No, the users table does not store a creation time (you can see the schema in `db/schema.sql`).
