### ISSUE TITLE
[UK] Do we *need* to load tile.jpg, the footer app store logos, and social media icons on map pages?

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#1907]
The footer and body background are all hidden on the map page but, because they’re not explicitly `display: none`, we’re still loading all the image files.

Visitors who come via the homepage will hopefully have all of those assets cached, so it won’t make much difference. But anyone who comes directly to a map page (eg: they’ve just followed a link to a report from social media or an email) will be waiting a few extra milliseconds for these useless images to load.

**Comment by dracos** [comment]
As discussed, they are visible on mobile pages, at the bottom. Definitely an argument for lazy loading them, though, people on mobile might never scroll down to them (also applies to e.g. footer images on front page).

**Comment by dracos** [comment]
PR at #1947
