### ISSUE TITLE
Possible updated translation

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1917]
We just shipped version 2.2 into production and noticed a minor thing - a string that was not translated, and seemingly not present in the .po file on Transifex: the "Change" string, linked to "/auth/change_email" on the "/my" page.

Is it possible that the Transifex file needs to be updated?

Thank you! :)

**Comment by dracos** [comment]
Versino 2.2 does not have a "Change" string on that page; it sounds like you've installed the master branch (or similar)? We generally only update the Transifex files with a new release, and we do plan to do a version 2.3 soon; in the mean time, up to you how you work around this if you want.

**Comment by dracos** [comment]
This is present in the .po file so I assume is dealt with, do reopen if not.

**Comment by jonkri** [comment]
Hi again!

The "Change" string mentioned above did work when updating to 2.3, but there is a similar issue.

The strings `"%s report marked as fixed"` and `"%s reports marked as fixed"` from `templates/web/base/reports/index.html` do not seem to be present in the 2.3 tag commit, or on Transifex.

I don't think that I have the permissions to re-open this issue.

Thank you!

**Comment by dracos** [comment]
Hmm, I think the text should be "problems maked as fixed" to match the same text lower down, which would also fix this issue (not sure why it wasn't in the file though, will look into that).
