### ISSUE TITLE
Questionnaire process could be more efficient

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1939]
It should be possible to update your report just by clicking one of the links in the questionnaire email.

Here's that email:

![buttons](https://user-images.githubusercontent.com/560001/34252295-f30520aa-e63a-11e7-8732-76339370a6ec.png)

Both "Fixed" and "Not fixed" buttons are clickable but _go to the same URL_, with another set of buttons on the site:

![site](https://user-images.githubusercontent.com/560001/34252334-160139ea-e63b-11e7-892c-f72ed214b78d.png)

and an update to the report isn't recorded until one of these is chosen _and_ a Submit button (which for me is off the bottom of my screen) is clicked. I wonder if we're losing a lot of updates because people are clicking the links in the emails and expecting that to be all that's needed, or picking yes/no on the site and not realising they also have to submit.

**Comment by dracos** [comment]
Don't know should be in the email too, and at the very least should be preselected when they select one, see comment here https://github.com/mysociety/fixmystreet/pull/1735#issuecomment-313657327 but that never made it into new ticket that I can see. I agree, clicking should create a questionnaire response immediately ideally, and then if they don't fill it in any more we still have that (though there are issues to consider, we require some update text if they're saying it's still open, and we want them to confirm whether they want to receive another questionnaire, etc).

**Comment by dracos** [comment]
This is done by #1998
