### ISSUE TITLE
Westside BID Data Request

### ISSUE THREAD

**Issue by davideaton2** [mysociety/fixmystreet#1946]
The BID utilise FMS in and around the post code B1 2HF.  From Paradise Circus to Five Ways and are interested in any and all data related to any and all FMS posts within this small area.  They want to use the data to help the council keep up to scratch with their statutory obligations.

**Comment by dracos** [comment]
https://www.fixmystreet.com/alert/list?pc=b12hf is the alert page for that postcode. Ladywood wad covers the area asked for and quite a bit more, but could perhaps be good enough to monitor.

You can specify a radius in km with the RSS feed, e.g. https://www.fixmystreet.com/rss/pc/B12HF/1 is anything new within 1km of that postcode – if they could get a postcode or point nearest the middle of the area they wanted, that might also be another possibility that would be more accurate. Email alerts having a custom radius is #68.

Other than, that I'm not sure what this ticket is requesting.

**Comment by jukesie** [comment]
OK I think what is actually needed is a CSV of six months worth of reports for that geography basically. I guess it falls somewhere between the 'alerts' and the 'dashboards' typically.

The Birmingham Westside Business Improvement District team have some kind of relationship with making sure things get reported/resolved.

**Comment by dracos** [comment]
That's not a trivial amount of development work - someone would need to construct a digital boundary from http://westsidebid.co.uk/wp-content/uploads/2015/01/Map-of-Westside.png (I assume they haven't provided one), then construct a query to locate the reports within that boundary and hook that into the CSV code to generate data. And that would be a one-off, there's no mechanism currently to use a custom area in any way.
