### ISSUE TITLE
Not possible to add a phone number to your user account

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1948]
Initially raised by a site user, replicated by me: a legitimate phone number seems to be failing validation.

![nospaces](https://user-images.githubusercontent.com/560001/34558645-dc4be07c-f136-11e7-8188-a031c4f2a039.png)
![withspaces](https://user-images.githubusercontent.com/560001/34558646-dc642ff6-f136-11e7-8823-c2eb7c6a0c7d.png)

**Comment by dracos** [comment]
This was working locally so I was confused, but I had forgotten to set a 'phone country' on the server (what country to assume a number is if not given in +NN international format). I've set it to UK now, so this is fixed.
