### ISSUE TITLE
Changed "Top 5 responsive councils" criteria

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1957]
The "Top 5 responsive councils" list on FixaMinGata shows a municipality that has only solved one problem (back in 2013) at the top, since that action took only about four minutes, and that beats any other average response time on the site.

![stats1](https://user-images.githubusercontent.com/777056/34680458-6eb2652a-f499-11e7-8f7d-0a56d54b9da7.png)

This does not seem like a fair representation of responsiveness, although I'm not sure what a better criteria would be. Perhaps there should be a minimum number of reports to be able to make the list. Perhaps reports of a certain age should not be taken into account.

**Comment by jonkri** [comment]
On a related note, is it possible to modify the information displayed on the All reports page for a specific cobrand? In particular, we are considering to maybe replace the "Top 5 most used categories" table with something else, as well as changing the responsiveness criteriera according to the post above.

Thank you!

**Comment by dracos** [comment]
You can override the template as per normal - or ideally, add one or more new hook templates to the template so you only need to override the specific parts (assuming e.g. the large graph/top half is okay with you :) ).

In terms of providing data to the page, it loads in whatever has been saved by the `bin/update-all-reports` script for use by the template – so you could write your own script that ran after that script that loaded in the file, added new data to it/changed it, then saved it out again. That would seem the cleanest way to proceed, probably. Of course, if it's only a little change to what it currently does, then we could look to add a cobrand-based hook to the script itself.

**Comment by jonkri** [comment]
I noticed that a hidden report that has a comment with a `mark_fixed` value of `TRUE` will be affect `calculate_average` in `FixMyStreet.DB.Result.Body`. Is this the intended behaviour? (We have a municipality in the "Top 5 responsive councils" with no fixed reports, except one which is hidden.)
