### ISSUE TITLE
Adjust zoom to show the entire body on mobile

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#1958]
When visiting a body (say, https://beta.fixamingata.se/reports/Ale) with a desktop sized browser, the zoom level shows the entire body (and all reports, which staff users appreciate). When visiting the same page using a mobile sized browser, the zoom level shows only a small part of the body. Would it be possible to adjust the zoom level in the mobile context, so that the entire body is shown there as well?

Another thing that seems inconsistent is that when visiting the above page on mobile, all three reports are shown in the list, even though only two reports are visible on the map. (My expectation is that the report list would only show the reports that are visible on the map. However, if the mobile version of the site is adapted to show the entire body on page load, this may not be a problem.)

**Comment by dracos** [comment]
Agreed, I've committed a fix to no longer have a minimum initial zoom on mobile.
