### ISSUE TITLE
MaPit LWP:UserAgent() call behind corporate proxy

### ISSUE THREAD

**Issue by Dylanderv** [mysociety/fixmystreet#1959]
Hello,

I wanted to use fixmystreet for some development test behind a corporate proxy, and I couldn't report any problem, or access to the admin->bodies tab.
It keeps giving me this kind of error: 
```
Caught exception in FixMyStreet::App::Controller::Council->load_and_check_areas "The call to http://global.mapit.mysociety.org/point/4326/5.722819,45.188761?generation=8;type=O08 at line 75 of FixMyStreet::App::Controller::Council failed
```

I dug into that and I found that the object LWP:UserAgent used in MaPit.pm had some problem working with proxies.

In order to avoid the problem I had to add this line just after the object was created (line 44 of MaPit.pm):
```perl
$ua->proxy(['http', 'https'], 'proxyurl');
```

I don't know if it's an issue, or just FixMyStreet isn't supposed to be used behind a proxy.

**Comment by dracos** [comment]
No reason it shouldn't, just don't think it's come up before :)

You don't need to alter any code to work behind a proxy, though, I think; you should be able to set the environment variables:
```
PERL_LWP_ENV_PROXY=1
http_proxy=proxyurl
https_proxy=proxyurl
```
and have the same effect as your line. I guess the user-agent should theoretically be customisable somehow so you could change it as necessary (for this or something else).
