### ISSUE TITLE
[fixmystreet.com] Check chart.js dashboard charts in IE8–11

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#2005]
I don’t think chart.js works at all in IE8, so we should check that the `/reports` and `/reports/<area>/summary` pages work fine without it.

There also look to be some chart.js rendering issues in IE9, and in IE10–11 the big "pull out" numbers on the chart at the top of `/reports` are way too far right, suggesting either a CSS issue, or a chart.js issue.

**Comment by wrightmartin** [comment]
## IE10 on Win7

![screen shot 2018-03-20 at 16 29 15](https://user-images.githubusercontent.com/2292925/37668220-de14899e-2c5b-11e8-93c1-68651a60e2ea.png)

**Comment by wrightmartin** [comment]
## IE10 on Win8
![screen shot 2018-03-20 at 16 30 14](https://user-images.githubusercontent.com/2292925/37668289-0cd59034-2c5c-11e8-8c17-1f4a2991a6e5.png)

**Comment by wrightmartin** [comment]
## IE11 on Win10
![screen shot 2018-03-20 at 16 31 18](https://user-images.githubusercontent.com/2292925/37668347-2bc18ffc-2c5c-11e8-8a5c-bc0368146260.png)

**Comment by wrightmartin** [comment]
# Summary page

## IE9 on Win7
![screen shot 2018-03-20 at 16 54 14](https://user-images.githubusercontent.com/2292925/37669683-644d81a2-2c5f-11e8-8b08-806eb19d2455.png)

**Comment by wrightmartin** [comment]
Ironically, it falls over nicer on IE8 than the newer browsers. What is out desired level of browser support for fms.com?

**Comment by dracos** [comment]
Looking at analytics, hits from anything below IE11 are very small (past 6 months or past month only, all IEs<11 0.5%, IE11 10%). I don't think graphs are core by any means, so I'd be happy if, graph wise:
* IE11 fixed the issue with number placement;
* IE9 displayed like IE8;
* IE10 displayed like IE11 if possible (fixing the scaling issue) or IE8 if that's not possible (chart.js doesn't say it supports IE10 after all).

**Comment by wrightmartin** [comment]
It looks like IE10's bugs with scaling are because we're not sizing the canvas directly (although we have specified height and width in the HTML), but relying on its wrapper `.labelled-line-chart`'s size and using:

```
width: 100% !important;
height: auto !important;
``` 

on `.labelled-line-chart canvas`

**Comment by wrightmartin** [comment]
IE8 fails over so nicely because the javascript doesn't run - it doesn't try to do any clever positioning nor attempt to paint the contents of the `<canvas>` object. I wonder if our best bet for IE9 (and possibly IE10) is to do the same - block the contents of `dashboard.js` from running completely

**Comment by wrightmartin** [comment]
## IE9 👎 

My first thought was we could just detect `<canvas>` support before we ran anything in dashboard.js, but IE9 supports `<canvas>`.  So the issue is that Charts.js doesn't support IE9, I don't really want to do any browser sniffing here, anyone got a better idea?

**Comment by dracos** [comment]
I'm perfectly happy to do browser sniffing for this. Doesn't even have to be browser sniffing, can use IE-only conditional comments.

**Comment by zarino** [comment]
@wrightmartin You can do `$('html').is('.ie9')` to check for IE7/8/9: https://github.com/mysociety/fixmystreet/blob/0ea49ebd2a33b2c14ab79bb1865e3fc45b4a5d05/templates/web/fixmystreet.com/header.html#L7-L9
