### ISSUE TITLE
Untranslated strings related to two-factor authentication

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#2008]
Are "patch" releases, like 2.3.1, supposed to be updated to Transifex?

I found the following strings that are not translated when I upgraded to 2.3.1:

- /my: Security
- /auth/generate_token: Security; Activate two-factor authentication

Thank you!

**Comment by dracos** [comment]
Yes, sorry, I clearly forgot! Will get it up shortly.

**Comment by jonkri** [comment]
Thank you!

(I assume that it will be included in the updated translation file, but I noticed an untranslated string on the "new report" page ("Your password should include 6 or more characters.").)

**Comment by dracos** [comment]
Gah, so much for shortly, sorry! Yes, that will be there too, promise :) But I can't do it right now for reasons, apologies for the further delay. Definitely today at some point.

**Comment by jonkri** [comment]
Oh, there is no rush. :) Thanks!

**Comment by dracos** [comment]
Okay, it should be pushed now.
