### ISSUE TITLE
git.mysociety.org Connection problem

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#2009]
Running the update script, I got this problem:

```
$ script/update 
fatal: unable to connect to git.mysociety.org:
git.mysociety.org[0: 46.43.39.75]: errno=No route to host

Unable to fetch in submodule path 'commonlib'
```

I'm guessing this is something temporary, but I thought it would be best to report it anyway.

**Comment by dracos** [comment]
I can connect fine, so I'm afraid that sounds like an issue at your end (if it's still happening), nothing we can do.
