### ISSUE TITLE
Find out ratio of people entering their postcode to view existing problems vs to report a new problem

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#2021]
A core assumption that has appeared at the centre of recent tickets (#2016, #1462) is that people are viewing the `/around` map to _view_ reports just as much as they are to _create_ new reports. But @wrightmartin and I just realised we have _no data_ to back this argument up either way.

Let’s do some science!!

Quick amendment to the FMS.com homepage that replaces the single "GO" button with two buttons: "Report a new problem" and "Show problems". And then track clicks on those buttons in Google Analytics. Both buttons will just submit the form as normal, taking people to the `/around` page.

**Comment by wrightmartin** [comment]
Ok, interesting science ahead. I might need to consult a member of the research team to verify the findings and my analytics are a _little_ rusty, but it looks like **more users are _reporters_ than _browsers_**.

**Comment by ajparsons** [comment]
Storing here, there are still conversions coming from the browsing path, but less:

![image](https://user-images.githubusercontent.com/8157058/39368267-0c40cb50-4a31-11e8-9233-9bd4b3e5bb5d.png)

**Comment by ajparsons** [comment]
Constructing another segment that gets people who have clicked BOTH buttons, this accounts for 784 reports - so the browse is still leading to conversions, but less. 

But also, there is then another behaviour that leads to people clicking both.

**Comment by zarino** [comment]
Okay, so the answer to this ticket was: Roughly **2 "browsers"** for every **3 "reporters"** … although, some people who intially click "browse" go on to actually make a report.

That’s good enough for me!

**Comment by dracos** [comment]
Some reporters may then not report anything, too, of course.

**Comment by wrightmartin** [comment]
> Some reporters may then not report anything, too, of course.

About 8% according to the exit numbers

![image](https://user-images.githubusercontent.com/2292925/39534682-1221e0b6-4e2a-11e8-9a46-f0d630493e5a.png)
8%
