### ISSUE TITLE
Change to cursor type when hovering over report pin

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/fixmystreet#2038]
Something for discussion

Currently, in the new report screen when you hover over the green pin where your report is being made it goes transparent (I assume so you can see the map behind it) and the cursor changes to the 'pointer' style (the same one you get on a clickable link), however it's not a clickable item.

Would it be better to change the cursor on hover to the 'grab' style cursor, to show you can grab and move it

**Comment by dracos** [comment]
I'd move from discussion to bug - it didn't used to do that!
