### ISSUE TITLE
Photos from hidden reports visible on /alert for up to 60 minutes

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#2053]
Hidden reports may be included in the list of photos on `/alert` until the cache expires after 60 minutes.

Steps to reproduce:

 1. Visit `/alert` and follow a link to a report from the photos displayed.
 1. Hide that report, either via the moderation tool or the admin editor.
 1. Return to `/alert` and the photo is still there.

When hiding a report the Memcache keys for recent photos (`bci:recent_photos:0:10` etc) should be flushed.

**Comment by dracos** [comment]
Should be fixed by #2064
