### ISSUE TITLE
Giant report button obscuring map interface on mobile browser

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#2060]
Report via Twitter: https://twitter.com/rowlandshaw/status/981513996179267585

"Not able to submit a new issue"
"a Lumia 950 (so running windows mobile 10, with the creators update)"

![dz8jxjfxkaadzkh](https://user-images.githubusercontent.com/944656/38311599-7c5abaa8-3817-11e8-97dc-0b183ee28291.jpg)

(Copy of misplaced https://github.com/mysociety/fixmystreet-mobile/issues/258, sorry)

**Comment by zarino** [comment]
This is related to https://github.com/mysociety/fixmystreet/commit/0da09e1c25ef5e5d5e5970d552ef594dfd43bf34 and the experiment we’re running.

My initial reaction is that the green button shouldn’t be showing there at all – it’s only for desktop visitors.

Have added this to the design sprint, so we can investigate quickly.

**Comment by zarino** [comment]
Aha! Looks like the

```
html.banner-position-variant-1 .banner-position-variant-1 { display: block !important; }
```

in https://github.com/mysociety/fixmystreet/commit/0da09e1c25ef5e5d5e5970d552ef594dfd43bf34#diff-e194d97a38ccf14e5f45ad74d35d1280R16 is overriding the

```
.map-fullscreen .big-green-banner { display: none }
```

from `_base.scss`, revealing the button even for mobile users.
