### ISSUE TITLE
Should response templates only be triggered if state changes?

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#2075]
Reports having their updates fetched from Confirm are ending up with duplicate responses, e.g.: https://fix.bathnes.gov.uk/report/1278104

In this case there are multiple `EnquiryStatusLog` entries within Confirm that haven't changed `EnquiryStatusCode`, and `open311-adapter` is simply converting these into service request updates.

The response template handling code in `GetServiceRequests.pm` should probably only trigger the template if the problem state has *changed*, and if it hasn't and the update text is blank then the update should be marked as hidden.

**Comment by dracos** [comment]
Makes sense to me (no update text and no media, I guess, just in case that ever happened...).

**Comment by dracos** [comment]
The updates are still appearing, only without the response template text, so blank.

**Comment by dracos** [comment]
This was fixed
