### ISSUE TITLE
More helpful error messages for open311 sending errors

### ISSUE THREAD

**Issue by struan** [mysociety/fixmystreet#2078]
At the moment the errors from problems sent via open311 include the raw dump of the POST and details of the error condition. As such it's a bit hard to pick out things like where the report was being sent, which report it was as these are embedded in the POST dump.

We should update this to include some basic information about the body, report id and probably the category in an obvious way to make initial triage a bit easier.

**Comment by davea** [comment]
👍 to this. Even if it just pretty-printed the parsed POST string that'd be good enough most of the time.

I use a one-liner fairly often to see what the email is on about: `pbpaste | python -c 'import pprint, urlparse; pprint.pprint(urlparse.parse_qs(raw_input()))'`
