### ISSUE TITLE
Scripts should check they are running in latest deployment

### ISSUE THREAD

**Issue by struan** [mysociety/fixmystreet#2079]
It's possibly when FixMyStreet has been deployed using timestampted deployments to find yourself running a script in the previous deployment. E.g. if you are on a server, have changed to the FixMyStreet directory and then re-deployed you will be in the previous deployment.

If a script is running inside a symlinked directory it should do some checks to make sure it's running under the latest deployment.

**Comment by davea** [comment]
Arguably, having to run shell scripts manually on a production server is a bit of a red flag and something we shouldn't need to do. I've opened #2081 for one particular instance of this.

As a workaround, could a script refuse to run unless it was called with its full absolute path?
