### ISSUE TITLE
$nav_fg_hover variable is used to change *background* colour in _layout.scss – confusing name!

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#2080]
In `_layout.scss`:

```sass
.nav-menu {
  a {
    color: $nav_fg;
  }
}
```

Ah, so "fg" must mean "foreground", as in, the colour of the _text_ rather than its background?

Errrr, nope. Only a few lines further down, in `_layout.scss`:

```sass
.nav-menu--main {
  a:hover {
    background-color: $nav_fg_hover;
  }
}
```

So "fg" here means "background"?

I think it’s this poor variable naming that has caused the confusion in https://github.com/mysociety/assets-community-value/issues/49.

**Comment by dracos** [comment]
I think how I read it was as the background colour when you `hover`ed over the `nav_fg`, sorry.
