### ISSUE TITLE
Contact form bug

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#2084]
A user contacted us to say that our form was calling her email address invalid, and I've replicated it on https://www.fixmystreet.com/contact by selecting 'my issue has not been fixed', as she did.

In this case, the form is supposed to display the message that the user should contact the council, rather than that their email address is invalid.

![screenshot-2018-4-16 contact us 1](https://user-images.githubusercontent.com/944656/38797554-c32c771c-4156-11e8-8fa1-3735256d3bf5.png)

**Comment by dracos** [comment]
Given the email address validation is client side but the "Topic" validation is server side, I am assuming there is a space at the start or end of your/their email address, or something else wrong with it, even though it looks okay; that would lead to the behaviour shown, as it complains about the email before it even gets to checking the topic question. If the form is submitted to the server, it displays the correct behaviour.

**Comment by MyfanwyNixon** [comment]
Weird. I can't replicate this now either, even with a space before my address. I tried her address and mine earlier and had the same issue with both.

Closing, then: let's see if any other incidences happen.
