### ISSUE TITLE
Critical CSS scripts should be under version control

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#2099]
The critical CSS generation script doesn't currently seem to be under version control or a repeatable part of the deployment process. This is OK for day-to-day deployments, but is likely to cause surprise if the site needs to be moved to another server in a hurry.

(This is specific to the deployment of fixmystreet.com, not the platform as a whole.)

**Comment by dracos** [comment]
And `/home/bci/auto-js-update` as well, cough.

**Comment by dracos** [comment]
Okay, this is now done in the https://github.com/mysociety/fixmystreet.com repo.
