### ISSUE TITLE
Date range is not clear when downloading dashboard data as CSV

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/fixmystreet#2103]
> For the reports section, the Export as a CSV defaults to a This Past Month date span which isn’t apparent of you are looking at the This Past Year data range using the dropdown. It would be useful to have the actual dates displayed on the chart to clarify (for instance, does This Past Month relate to the calendar month, the month to date or the last 4 weeks)

**Comment by dracos** [comment]
Is this /reports/*/summary or /dashboard? The CSV does default to the same as the dropdown. Just on /reports/*/summary it is limited to 100 reports, if that's the actual issue.

**Comment by dracos** [comment]
As for 'past month', well, it means the English phrase 'past month', which is not 'past 4 weeks' or 'month to date' ;)

**Comment by wrightmartin** [comment]
> Is this /reports/*/summary

I _think_ this. This was from an email from some of the team at Oxford, a screenshot of `/reports/*/summary` was attached

**Comment by wrightmartin** [comment]
> it is limited to 100 reports, if that's the actual issue.

Yes, this is the issue.

I think we should add this to the page design to make it clear as it doesn't say so.
