### ISSUE TITLE
Strip EXIF data from report photos

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#2134]
An app user has emailed to suggest FixMyStreet removes EXIF tags from photos before they're made available for download from the site.

> Using exiftool (for example), I could see the make/model of my phone and various other settings. [...] I can also see the potential for finger-pointing, finger-printing a device or identifying a user posting an issue anonymously. [...] Best to strip (eg mogrify --strip) before publicly displaying.

We already run `jhead` on uploaded photos to correct the orientation, perhaps `mogrify` could be run subsequently. Alternatively, if we wanted to preserve the EXIF tags in the on-disk file, they could be stripped at the point `PhotoSet::get_image_data` generates the cached files.

**Comment by dracos** [comment]
Previous history at #1411
