### ISSUE TITLE
Consider ditching placeholders for a more accessible approach

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/fixmystreet#2180]
For discussion, probably

https://www.smashingmagazine.com/2018/06/placeholder-attribute/

**Comment by zarino** [comment]
The recently "standardised" https://design-system.service.gov.uk/components/text-input/ is a nice example:

```html
<div class="govuk-form-group">
  <label class="govuk-label" for="email">
    Email address
  </label>
  <span id="email-hint" class="govuk-hint">
    We’ll only use this to send you a receipt
  </span>
  <input class="govuk-input" id="email" type="text" aria-describedby="email-hint">
</div>
```

**Comment by zarino** [comment]
Looks like we have about 50 inputs with `placeholder` attributes, across core, fms.com, and the other cobrands. Generally:

* Homepage postcode form
* Problem report form
* Problem update form
* Alert signup form
* "Receive email when updates are left on this problem" form
* "Extra details" input on Report Inspect form
* "Moderation reason" input on report page

**Comment by zarino** [comment]
WIP pull request here: https://github.com/mysociety/fixmystreet/pull/2194
