### ISSUE TITLE
Private report update email links should log the user in

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#2193]
Support email from a user:

> FixMyStreet sent me an email with a link asking me to set my complaint back to open but the link does not work. It displays a webpage with the message "Error - The report can not be viewed on fixmystreet"
https://fixmystreet.oxfordshire.gov.uk/report/1345659

This is presumably because the report in question is marked as private, and the user is not logged in when following the link in the email. Perhaps it'd be better if the links were token URLs to log the user in, or the error message invited the user to login and view the report?

**Comment by dracos** [comment]
The error message does now invite the user to log in.
