### ISSUE TITLE
Make password policy clearer

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/fixmystreet#2210]
If we're checking for common words, or expecting the account password to be of a certain complexity we should say so on the form 

![screen shot 2018-08-17 at 10 42 35](https://user-images.githubusercontent.com/2292925/44259777-686ac300-a20a-11e8-8439-164d11d4a77c.png)

**Comment by dracos** [comment]
The policy is length and not-extremely-common. I did consider this, promise, but I thought that anyone using a stupidly common password is hardly likely to do anything different if the text said "Your password should include 6 or more characters and not be stupidly common"...
