### ISSUE TITLE
Cannot report problems in categories that contain subcategories, in Bromley at least

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#2275]
Subcategory box is not shown after category is chosen, in Bromley.

Then, once you _do_ select a subcategory, the selection is immediately lost.

Therefore, totally unable to report problems in this area.

**To Reproduce**
1. Go to https://www.fixmystreet.com/report/new?longitude=0.0601714563445887&latitude=51.40870207776534 or search for the postcode `BR7 5LZ` and click on "Old Hill"
2. Select the "Road and Pavement Issues" category
3. Notice that the form does not ask you for a subcategory
4. Fill in the remainder of the form, then submit it
5. Note that you are now shown an error about not having selected a subcategory
6. Select a subcategory
7. Note how the subcategory panel disappears as soon as the subcategory is chosen
8. Try submitting the form again
9. Note how you get looped back to the error from step 5
10. Cry

**Expected behavior**
The grey Subcategory panel should be shown automatically, as soon as you select a category.

And selecting a subcategory should not then hide the subcategory panel, rendering the form unable to be submitted.

**Screenshots**

![image](https://user-images.githubusercontent.com/739624/46474469-e135d680-c7da-11e8-9c3e-965b91148ee9.png)

**Comment by dracos** [comment]
Fixed in 96bb52d44
