### ISSUE TITLE
handlemail always uses the auto-reply template from the default cobrand

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/fixmystreet#2331]
When the handlemail script replies with the reply-autoresponse template, it always uses the one from the default cobrand.

**To Reproduce**
1. Configure the .forward file for the fms user to execute the handlemail script
2. Set up an alias or similar for the DO_NOT_REPLY address to the fms user
3. Send a regular email to the DO_NOT_REPLY address.

Note that the DO_NOT_REPLY address needs to start with the "fms-" prefix, otherwise it seems the handlemail script doesn't handle the mail (even if it matches the DO-NOT-REPLY regex in the script, not sure if this was intended).

I can supply a pull request with a fix for this if it's ok to specify cobrand with an argument to handlemail. As in:

```handlemail --cobrand=fixamingata```

**Comment by dracos** [comment]
Sorry for not spotting that! Sure, that sounds good, thanks.
