### ISSUE TITLE
handlemail doesn't handle utf-8 correctly

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/fixmystreet#2332]
If the reply-autoresponse template is a UTF-8 encoded text file with non-ASCII characters it doesn't seem to send it correctly.

I'm not sure what the issue is, I can see that it has correctly set the Content-Type header:

```Content-Type: text/plain; charset="utf-8"```

Still the text shows up as ASCII (in for instance gmail).

Sorry for not investigating further before creating an issue, I can perhaps find time to look more at it eventually.

We're using Postfix as MTA. See attached sample headers.

[headers.txt](https://github.com/mysociety/fixmystreet/files/2609345/headers.txt)

**Comment by joesiltberg** [comment]
I tested this with the DO_NOT_REPLY address for the UK site now (fms-do-not-reply@fixmystreet.com). There's no UTF-8 problems there since the reply is in English, but there seems to be something wrong with the headers. The subject line shows up as empty in my mail client and a couple of headers show up as part of the body (Content-Type and Content-Transfer-Encoding).

**Comment by dracos** [comment]
Oh dear, that doesn't look right does it! Thanks for spotting (shows hopefully that this isn't a well-used thing!), I'll see if it's something obvious/easy to fix.

**Comment by dracos** [comment]
Thanks for spotting this, hopefully on master it should be okay now.

**Comment by joesiltberg** [comment]
@dracos This seems to work much better now, I get correct From: and Subject: headers. Thanks!

My email client still doesn't interpret the body as UTF-8 for some reason. The fixed handlemail from you with the Swedish cobrand can be tested by emailing fms-do-not-reply@fixamingata.se , if you'd like to see what it looks like in your email client.

Perhaps not so important since it's only the auto reply for the do-not-reply address.

**Comment by dracos** [comment]
Hopefully fixed in #2334
