### ISSUE TITLE
xmas donate banner

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#2348]
As per #1299  - could we run the xmas donate banner from 14th Dec to 6 Jan please?

**Comment by dracos** [comment]
Do we have any statistics on what impact it had last year?

**Comment by MyfanwyNixon** [comment]
Good question. 

Analytics appears to indicate that 67 people came from WTT to the donate page during the period the banner was up last year (Dec 16-Jan 3), and that 3 of them saw the 'thanks' page. This may be stronger proof that the donate page could be more compelling.

Perhaps @abimysoc has figures for actual donation amounts - but I don't know to what extent she can see where they came from.

**Comment by MyfanwyNixon** [comment]
52 people came to the thanks page from paypal, so I don't know if any of those were also routed from WTT.

**Comment by MyfanwyNixon** [comment]
Content for the banner, thanks: 

Text
If we've helped you keep your neighbourhood tip-top this year, could you help us do more in 2019?

Link https://www.mysociety.org/donate/?utm_source=fixmystreet.com&utm_medium=banner&utm_campaign=december_2018&utm_content=banner+keep+neigh
