### ISSUE TITLE
Missing space between category select box and category_meta div

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#2368]
For categories with "extra data", the little grey arrow at the top of the `category_meta` div overlaps the `category` select box:

![screen shot 2019-01-08 at 13 15 04](https://user-images.githubusercontent.com/739624/50833103-1e64b400-1348-11e9-987e-a33ad51943b1.png)

It looks like we’re applying a `margin-top: 1.5em` to `.extra-category-questions`, but it’s being overridden by the `margin: 0 -1em` on `body.mappage .full-width`.

Note, if we reintroduce the `margin-top` here, we’ll need to make sure it doesn’t cause _extra_ space between the category questions and the "pick from the map" hint on categories with asset layers:

![screen shot 2019-01-08 at 13 15 24](https://user-images.githubusercontent.com/739624/50833258-85826880-1348-11e9-9c87-eee7efbb0b8c.png)

I’m tempted to say, if the `#category_meta` doesn’t _immediately_ follow the `#form_category_row` (eg: because there’s a `.category_meta_message` in the way) it shouldn’t have the little arrow.

**Comment by zarino** [comment]
#2433 now includes a fix for this.

**Comment by dracos** [comment]
#2433 is merged, so I assume this is fixed
