### ISSUE TITLE
Minor issue in process-inactive-accounts

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/fixmystreet#2376]
For FixaMinGata, we're running process-inactive-accounts and process-inactive-reports nightly. We're expecting to anonymize the first real users during spring so I did some testing to make sure it works as expected. 

It seems to work fine! 

I noticed one minor thing which perhaps isn't worth fixing, but perhaps it'll be a problem when more users are anonymized.

**Describe the bug**
process-inactive-accounts seems to anonymize already anonymized users. Not sure if this is a problem, but if you're running the script with --verbose to see which users were anonymized you'll eventually get a very long list instead of just the ones that were anonymized this time.

Not sure if we're actually doing any db writes due to these since we'd be writing the same values, but if we do perhaps it will be a performance issue once there are many old accounts.

**To Reproduce**
1. Make sure there's at least one user where last_active is old enough
2. Run the script with high verbosity as the fms user, for instance: 
```/var/www/beta.fixamingata.se/fixmystreet/bin/process-inactive-accounts --verbose --anonymize 12 --email 11```
3. Note that some users are anonymized
4. Do step 2 again
5. Note that the same users are anonymized again

One idea is to check for empty passwords to avoid re-anonymization. But perhaps there could be accounts with empty passwords which would still need to be anonymized? Checking the anonymized email seems a bit ugly...

**Comment by dracos** [comment]
Yes, you're right, it is anonymizing already anonymized users. You can't check for empty passwords as that would include anyone who never set a password, I think. Sadly, I think checking the email might be the only way; bit ugly as you say, but should work okay nonetheless.
