### ISSUE TITLE
Reduce gap between labels and checkboxes in inline forms

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/fixmystreet#2411]
> there is a gap between the tickbox and the ‘Show my name publicly’ field which means the person testing with a zoomed-in screen didn’t see the tickbox

![image](https://user-images.githubusercontent.com/2292925/53558007-0f77d200-3b3f-11e9-95f4-fbe8ea344a04.png)

**Comment by dracos** [comment]
`label.inline` has a left padding of 1em. Should be 0, or not em-based?

**Comment by wrightmartin** [comment]
Em based means it gets larger with text zoom, which could cause the issue described, so a pixel unit would be better (although for browsers who zoom any other way this doesn't help).
 
Reducing it to 0 makes it too close, perhaps `5px` is a good middle ground?

**Comment by dracos** [comment]
Does any browser not do pixel zoom by default now? Anyway, 5px is what gov.uk front end has (though with their giant checkboxes) so sounds good :)
