### ISSUE TITLE
Link to category with slash in does not work

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#2439]
The refactor in #2400 broke the links to categories with slashes in them; the code copes with those slashes not being escaped, but they now are (a difference between uri_for and uri_for_action). Changing %2f to / in the URL gets them working as a workaround.

**Comment by dracos** [comment]
I don't think this is our code, now, but Apache: "The AllowEncodedSlashes directive allows URLs which contain encoded path separators (%2F for / and additionally %5C for \ on accordant systems) to be used in the path info. With the default value, Off, such URLs are refused with a 404 (Not found) error."
Added NoDecode option in Apache sever, is working again now.

**Comment by abimysoc** [comment]
Not resolved; saving a change to the category still results in Page Not Found.

**Comment by dracos** [comment]
So, a page such as `/admin/body/N/Parks%2Flandscapes` (which is now loading fine as per above), the form tries to submit to `../../N` ie. `/admin/N` when it should be `../N` – the slash is being treated as an actual slash by something when it comes to constructing the form action.

**Comment by dracos** [comment]
Should be fixed now, by b928e9ce1cf475ea5139e5846049db63ba53a48b
