### ISSUE TITLE
Can't edit a category with a forward slash in its name

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#2459]
**Describe the bug**

Forward slashes in category names aren't being escaped properly, presumably.

**To Reproduce**

In admin, find a body with a category that has a forward slash in its name, e.g. Cherwell DC's 'Parks/Landscapes'; Derry City's 'Pavements/footpaths'.

Click on category name, 404 Not Found (it's treating the slash as part of the path and looking for /admin/body/21085/Pavements/footpaths).

**Comment by dracos** [comment]
Dupe of https://github.com/mysociety/fixmystreet/issues/2439
