### ISSUE TITLE
Allow categories to appear under multiple groups

### ISSUE THREAD

**Issue by struan** [mysociety/fixmystreet#2475]
Where categories are grouped it would be helpful to be able to place a category under multiple groups for categories which could be related to more than one. This will enable a category to be listed under all the groups that a user might expect it to appear, hence reducing the likelihood of users trying multiple groups before finding the category they want.

e.g _Flytipping_ might appear under both a _Rubbish and Litter_ group and an _Environmental Issues_ group.

The category would be the same in each location it appeared.

**Comment by struan** [comment]
Parts of plan are:
- Allow multiple groups in open311 services response
- Store multiple groups in FMS DB
- Show category in multiple groups on front end

**Comment by struan** [comment]
For the multiple groups in open311 bit of this it's not totally obvious how to do this.

In theory we should be using the `keywords` bit of the service description for extra group for the extra groups, although the spec is a bit hazy on that. It's still going to be plain text though unless we wanted to extend things. I guess we could just specify CSV escaping and then use that when importing it.

**Comment by dracos** [comment]
The code is live, and activated on staging for BANES, emailed James about it. So considering this 'done' in that it can be switched on for any council that wants it now.
