### ISSUE TITLE
Extra fields not available under problem.extra in email templates.

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/fixmystreet#2512]
**Describe the bug**
When adding an extra field to a category, there's a help text that says the extra field should be available as 'problem.extra.address' or similar in the templates. I can't get this to work in the email templates.

Maybe I'm missing something, but I'll create a pull request with a solution that seems to work the way I would have expected.

**To Reproduce**
1. Create a new category with an extra field
2. Set the code for the new field to e.g. 'building'
3. Edit the submit.txt template, use ```[% problem.extra.building %]``` in e.g. the subject line
4. Submit a new report and enter something in the extra field
5. Note that the field doesn't show up in the email

**Expected behavior**
All extra fields available through ```problem.extra.<code>``` in the templates.

**Comment by dracos** [comment]
I don't think that help text is accurate, sorry; the extra fields are stored as a list (as you know). I think you can access the field you want in an email template using `report.get_extra_field_value("building")` though.
( The fact we sometimes use `problem` and sometimes `report` is also annoying, sorry!)

**Comment by joesiltberg** [comment]
Thanks! ```report.get_extra_field_value("building")``` works, would you like me to just update the help text instead?

**Comment by dracos** [comment]
That'd be great if you could, thanks!

**Comment by joesiltberg** [comment]
I've updated the pull request to only change the help text (https://github.com/mysociety/fixmystreet/pull/2513).

**Comment by dracos** [comment]
Now merged, thanks.
