### ISSUE TITLE
Chrome's autofill get confused when creating a new report

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/fixmystreet#2570]
**Describe the bug**
Google Chrome sometimes inserts your email address in the title input box when you're creating a new report. Apart from being a bit annoying I suppose it could lead to privacy issues if users accidentally publish their email address.

**To Reproduce**
1. Make sure you've asked Chrome to save your username and password when you logged in.
2. Log out.
3. Start to create a new report.
4. See error (your email address in the title input box)

**Screenshots**
![autofill](https://user-images.githubusercontent.com/25550775/61523622-09628f00-aa15-11e9-8000-5878c564ee74.png)

**Expected behavior**
Autofill shouldn't be used for the title input box.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.142

I don't see the problem in Firefox or Edge. I've tried to work around it by adding autocomplete="username" and autocomplete="new-password" to the input boxes for email and password, but Chrome seems to ignore it. Setting autocomplete="off" or autocomplete="new-password" on the title input box also does nothing.

**Comment by dracos** [comment]
Yes, we've noticed this recently. We started with one of your suggestions at https://github.com/mysociety/fixmystreet/pull/2518 as you can see, but as you note didn't appear to fix the issue. I wonder if we rename the name of the input field, would that help, is it somehow looking for 'title' for some reason? Without knowing the logic of why it is doing this, it's hard to know what to do :-/

**Comment by joesiltberg** [comment]
I tried renaming the input field without any luck. 

There's an article at MDN that suggests using jQuery.disableAutoFill:

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields

But that seems to work by changing the name as well so it's perhaps not likely to work.

If we're lucky Chrome's behaviour will change back :-)

**Comment by dracos** [comment]
I turned on Chrome's autofill prefilling info thing, and get this:
```
overall type: UNKNOWN_TYPE
server type: NO_SERVER_DATA
heuristic type: UNKNOWN_TYPE
label: Summarise the problem
parseable name: title
section: status_presets_1-default
field signature: 1431592867
form signature: 6119969779355539103
```

Which doesn't appear to help much :-/ Not sure that jquery thing will work given it changes the field name and I also have tried that and it still does it!

**Comment by joesiltberg** [comment]
Good to see you added validation to prevent this from causing problems.

I've tried a couple of other workarounds but nothing seems satisfactory. To mitigate it a bit I tried adding some JavaScript which clears the title when it contains an email. Something like this in our cobrand's js.js:

fixmystreet.fixChromeAutocomplete = function() {
    let title = document.getElementById("form_title");

    if (title) {
        if (title.value == "" ||
            /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@(?:\S{1,63})$/.test(title.value)) {
            title.value = "";
        }
    }
}

(the weird "if empty -> set to empty" thing is because title.value will sometimes be empty when it is autofilled and sometimes contain the email. Even when title.value is empty it helps to set it to "").

I've experimented a bit with when to call this, but you easily get into a ping-pong game with Chrome where the browser adds it back. What I found did seem to work was to call this when the category is selected. It's not pretty but I think it's still an improvement.

Since it's a bit of a hack, perhaps you don't want this in the base/default cobrand(?). I can add it just to ours, my only problem is that I'd prefer not to modify report/new/category.html in order to set the onchange attribute. Any idea how I can do that in a more maintenance friendly way? I tried adding it in an onload event listener in js.js, but it seems onload isn't triggered when I start creating a report by clicking on the map.

Thanks!

**Comment by dracos** [comment]
The best way to listen for that change is in your JavaScript file, either listen to our own change event, or a standard listen to the select changing, e.g.
`$(fixmystreet).on('report_new:category_change', fixmystreet.fixChromeAutocomplete);`
or
`$("#problem_form").on("change.category", "select#form_category", fixmystreet.fixChromeAutocomplete);`
Either of those should have the same effect you want, hopefully.

**Comment by joesiltberg** [comment]
That works, thanks!
