### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by dotbm** [mysociety/fixmystreet#2648]
I have installed Fixmystreet via the script and all seems fine so far.

The only issue I'm facing is that I can not upload any images to the sever. It fails every time I try.

Site: http://208.113.134.164/report/new?longitude=-64.7147016931154&latitude=32.350625872789166

**Comment by dracos** [comment]
I just created a test report on that link and the photo upload appeared to work successfully (it got an ID from the server in the ajax upload, and the report was created successfully). I haven't yet received a confirmation email to confirm my test report, but you should be able to see it in your admin etc.

**Comment by dotbm** [comment]
Thanks, I have tested it now in a few version of browsers and it seems the beta FireFox seems to not work. 

Somehow I had the same versions on my mobile as my pc.
