### ISSUE TITLE
Email has stopped working since latest update

### ISSUE THREAD

**Issue by dotbm** [mysociety/fixmystreet#2693]
**Describe the bug**
Email was working from the localhost until I updated yesterday. 

**Expected behavior**
Email to be sent when report is created or when user resets password.

**Additional context**
I had the full site working until I updated. With help I have solved the issues with bodies and TIME_ZONE but now I have found this email error. 

Nothing is showing in the logs as these are that last lines I have:

Process Backgrounded
2019/10/18-14:44:17 Starman::Server (type Net::Server::PreFork) starting! pid(327)
Resolved [*]:9000 to [0.0.0.0]:9000, IPv4
Binding to TCP port 9000 on host 0.0.0.0 with IPv4
Setting gid to "1000 1000 4 20 24 25 27 29 30 44 46 102 1000"
[info] 1 is logged in for this report
[info] 1 is an inspector - redirecting straight to report page for 2
[info] 1 is logged in for this report
[info] 1 is an inspector - redirecting straight to report page for 3
[info] 3 is logged in for this report
[info] 3 is an inspector - redirecting straight to report page for 4

**Comment by dracos** [comment]
It is impossible to say what the issue could be based upon the information given. We do not know how you have configured your server to send email, or anything else outside the FixMyStreet environment. You will need to e.g. check your mail server's logs (e.g. in /var/log/mail.log or somewhere like that) to see what is happening to mail sent on your server, assuming that it is getting from FixMyStreet to the mail server successfully.

Generally, this bug tracker is for bugs in the software itself, not issues with your particular installation. We have a mailing list, see https://fixmystreet.org/community/ where people can discuss questions and issues like that.

**Comment by dotbm** [comment]
Thank you for the info. I will head over there to figure it out.
