### ISSUE TITLE
Group categories in dropdown on map & inspector UI

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#2702]
Showing of category groups in category dropdown:
- [ ] Map filter
- [x] Inspector form
- [x] Dashboard
- [x] Admin selecting categories for user/templates
- [x] Admin report edit
- [x] Admin body page, list of categories

For cobrands with a lot of grouped categories, showing all categories in a flat list in the dropdown on the map filters isn't very helpful:

![Report Snapshot](https://user-images.githubusercontent.com/4776/67674214-d022af00-f973-11e9-90c9-9b7b9278692f.JPG)

And it's the same on the inspector tool when changing category:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/4776/67674231-dd3f9e00-f973-11e9-833f-b3dac1c01e82.png">

At the very least it would be good to use some `<optgroup>` hierarchy like we do for non-JS on the new report form:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/4776/67674328-1d9f1c00-f974-11e9-8cab-5fc9348aa878.png">

**Comment by dracos** [comment]
Also dashboard category dropdown, admin selecting categories for user/templates, admin report edit.

**Comment by dracos** [comment]
Chat about the map filter one in Slack: https://mysociety.slack.com/archives/C0260Q88Y/p1572862477014100

**Comment by davea** [comment]
PR for map filter one at https://github.com/mysociety/jquery-multi-select/pull/20
