### ISSUE TITLE
Unable to submit report, forms are submitting to http instead of https

### ISSUE THREAD

**Issue by ensirc** [mysociety/fixmystreet#2814]
**Describe the bug**
The site www.fixmycommunity.com is being run as https enabled website. But the forms have http://www.fixmycommunity.com instead. Currently unable to submit a report because of this.
The site is also being displayed as not fully secure because of http forms and not https.

**To Reproduce**
1. Go to 'www.fixmycommunity.com'
2. Click on Try and report an issue, using like 'half way tree road'
3. Complete the report and submit
4. Report is not saved

**Expected behavior**
Expected the report to be saved.

**Screenshots**

**Additional context**
Site is SSL enabled using Let's Encrypt. BASE_URL in the general.yml file is pointed to "https://www.fixmycommunity.com"

**Comment by davea** [comment]
What is the value of `SECURE_PROXY_SSL_HEADER` in `general.yml`? What front end server are you using, e.g. nginx/apache? How is that configured to pass requests to the FMS instance?

**Comment by dracos** [comment]
Also see the thread at https://groups.google.com/a/mysociety.org/forum/#!topic/fixmystreet/4Xt21ZL3OhM which has someone else having this behaviour and what config someone used to get it working for them.
