### ISSUE TITLE
Contacts with Open311 send method shouldn't allow new Open311 attributes to be added via admin

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#2817]
If a contact is managed via Open311 then the admin UI for adding/removing extra questions should be disabled. Allowing admins to add new questions has caused issues with reports being rejected by `open311-adapter` because the extra request parameters aren't recognised.

The one exception to this is adding notices, which BANES have requested.

**Comment by dracos** [comment]
I can't find it now, but I thought at one point we did have an Open311 endpoint that accepted any questions and then passed it on as e.g. additional text in a description field. In which case you might want to still allow this. But perhaps I dreamt it :-/

**Comment by dracos** [comment]
We do allow this because e.g. Peterborough can add any extra field starting pcc- and it works okay. Perhaps we need a generic way of doing that, which would fix this if it could be explained clearly...

**Comment by dracos** [comment]
(note open311-adapter now allows any parameter)
