### ISSUE TITLE
Support for uploading HEIC format images

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#2871]
User support request:

> Please add .HEIC to file upload types
> See https://www.macworld.co.uk/feature/iphone/what-is-heic-3660408/

Safari on iOS does appear to convert to JPEG when uploading, so not sure yet on the mechanism by which a user would be uploading HEIC photos.

**Comment by dracos** [comment]
https://caniuse.com/#search=heic - not even Safari supports showing them? :) So we'd have to convert them to JPEG ourselves, and https://github.com/ImageMagick/ImageMagick/issues/507 made me cry.

**Comment by davea** [comment]
The user followed up to say it was a one-off error when using the mobile app on iOS.
