### ISSUE TITLE
Allow inspectors to post a photo along with their update

### ISSUE THREAD

**Issue by chrismytton** [mysociety/fixmystreet#2902]
(From the FMS Pro Feature identification session in London, February 2020.)

Related to https://github.com/mysociety/fixmystreet/issues/2901, which is about making the inspector UI less confusing.

At the moment the inspector can upload a photo with a regular update, but they can't upload a photo through the form that's specific to inspectors.

**Comment by davideaton2** [comment]
This is something TfL have asked for

**Comment by chrismytton** [comment]
> This is something TfL have asked for

Forgive me if this is a silly question: Why can't their inspectors use the regular update form to upload a photo?

**Comment by davideaton2** [comment]
I'm guessing because they are all logged in as inspectors and don't want to log back out to post updates with photos?

**Comment by chrismytton** [comment]
Hmm, I must be misunderstanding something then, on the Oxfordshire version it seems like you can upload a photo as an inspector:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/22996/78541367-6c879200-77ed-11ea-99f0-f84625637691.png">

**Comment by dracos** [comment]
Yeah, as discussed on call last week, I think they literally don't realise they can do this now and this could be "sorted" (ignoring improving it in #2901) by just telling them how they can do this *now* if they want to.
