### ISSUE TITLE
script/update no longer working for some installations

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/fixmystreet#2930]
I'm not sure how much of a problem this is, but perhaps it will cause problems for some installations.

Running script/update after upgrading to v3.0 will now require sudo access (since bootstrap will run the new bin/install_packages), and only work on systems with APT.

I think it's great if fixmystreet helps make sure its dependencies are installed, but should it be done automatically when running script/update?

Also, if bootstrap installs the needed packages, the installation instructions for manual installation (https://fixmystreet.org/install/manual-install/) can be simplified.

**Comment by sagepe** [comment]
Thanks for raising this, @joesiltberg. I think you are right - this should be discretionary rather than automatic, and it certainly shouldn't run where the prerequisites are not met.

**Comment by dracos** [comment]
This affects eg. any AMI install.
