### ISSUE TITLE
The documentation still says access to /admin should be restricted

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/fixmystreet#2937]
We haven't started letting staff users into the admin interface yet, and still use htaccess to restrict access to /admin as the documentation advises (docs/running/index.md).

But I'm guessing this isn't still necessary? The privilege system in fixmystreet handles access to the admin interface now, right? 

Or is there still some reason left to restrict access with htaccess?

**Comment by dracos** [comment]
No, there's no reason to restrict with htaccess any longer that I can think of, unless you wanted the extra level of access restriction.

**Comment by joesiltberg** [comment]
Thanks!
