### ISSUE TITLE
Remove 2020 FixMyStreet Survey

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet#2971]
On April 30th we will finish the first tranche of the FixMyStreet User research survey, we'll close the survey on surveygizmo and we would like to take the link off the main FMS.com site as well.

<img width="1439" alt="Screenshot 2020-04-21 at 10 09 59" src="https://user-images.githubusercontent.com/4170351/79847898-469ae980-83b8-11ea-8a1e-22ff4e09ac4a.png">

Date due 2020-04-30

**Comment by LouiseMySociety** [comment]
https://trello.com/c/w2IdyhLR/615-remove-survey-banner
