### ISSUE TITLE
Consider default link colour in #front-main

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#3007]
While working on https://github.com/mysociety/fixmystreet/pull/3006, I noticed that a fair few cobrands where having to override the colour of `a#geolocate_link` because they want it to look like a normal (usually blue) link but `web/cobrands/sass/_layout.scss` is setting `#front-main a { color: inherit }` which, in most cases, would result in a black or white link.

Oxfordshire and Peterborough are two examples of this:

![Screenshot_2020-05-01 FixMyStreet](https://user-images.githubusercontent.com/739624/80804403-f0def200-8bac-11ea-9e0e-1350c862372e.png)

![Screenshot_2020-05-01 FixMyStreet(1)](https://user-images.githubusercontent.com/739624/80804543-63e86880-8bad-11ea-9f43-e15a781e3ce8.png)

I decided to test every cobrand, to see which ones actually set a custom text colour for `a#geolocate_link`, and of the remainder, which ones actually _need_ the `color: inherit` from core, and which could happily do _without_ the `color: inherit` on links in `#front-main`.

Annoyingly, I ended up with three nice neat lists of almost 8 cobrands a piece. So there’s no obvious benefit to changing it either way:

### Cobrands where `a#geolocate_link` is given a custom colour in layout.scss, to override the `color: inherit` applied to `#front-main a` in `_layout.scss`.

- bristol
- cheshireeast
- eastherts
- oxfordshire
- peterborough
- tfl
- warwickshire
- westminster

### Cobrands where the `color: inherit` in `_layout.scss` is *actually* needed.

*(eg: because #front-main has a dark background colour, so the links need to inherit the black or white text colour of a parent element, rather than a generic blue link colour.)*

- bathnes
- bromley
- fiksgatami
- fixamingata
- fixmystreet
- hart
- hounslow
- isleofwight
- rutland

### Cobrands where the `color: inherit` in `_layout.scss` doesn’t make a big difference, so could be kept or removed, dealer’s choice.

*(eg: all the `inherit` does is change dark blue links to black links.)*

- bexley
- borsetshire (no geolocation link at all!!)
- buckinghamshire
- greenwich
- highwaysengland
- lincolnshire
- northamptonshire
- stevenage
- zurich

My instinct is that links in `#front-main` should be left to inherit the default page-wide link colour.

But really, if we do that, then `#front-main` shouldn’t be given a background-color in the default styles either, because _that’s_ what’s causing all of this. In this new regime, if cobrands wanted to *opt in* to a coloured `#front-main`, then they should also override their `#front-main` link colours (perhaps to `color: inherit`, or to something else!) at the same time.

As I say, there’s not a huge benefit to doing this, though, so I figured I’d document what I’d discovered, and leave it for another day. I expect, as more council cobrands start moving away from the default (2012) fixmystreet styling with the big coloured band on the homepage, and instead start adopting a more stripped-back, GOV.UK style form design, then the list of cobrands having to override the `color: inherit` from `_layout.scss` will tip the balance in favour of changing the default.

**Comment by dracos** [comment]
How about if you add a new variable `$primary_link_color` which defaults to nothing? Then the base style can use that (or not set anything), and your middle set can set it in _colours to inherit and have it work. (Assuming first set overrides are presumably always back to the standard link colour.)
