### ISSUE TITLE
Review the promotional messaging on report emails sent to councils

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#3071]
Some time ago, we created some copy to go at the foot of emails sent to non-cobrand councils.
We might consider updating this to reflect current priorities - @davideaton2 suggests promoting the Pro webinars for example.

**Comment by davideaton2** [comment]
what do we currently send?

**Comment by MyfanwyNixon** [comment]
Report currently looks like this:

![image](https://user-images.githubusercontent.com/944656/86579605-74360e80-bf75-11ea-948d-bb47fe121164.png)

Suggested:

Replace the 'in-depth stats' message with:

### Looking for a better solution?

Authorities across the UK are discovering that FixMyStreet Pro saves them money from the day it's installed. Full-service reporting that can work with your existing systems -- whatever they are. [Book in for a friendly webinar and we'll show you how](https://www.fixmystreet.com/pro/take-a-tour/webinar-schedule/)!

**Comment by MyfanwyNixon** [comment]
Oh I'm clearly losing my memory because I'd already written

**FixMyStreet Pro is making savings for authorities across the UK**
Join one of our regular informal webinars to discover how FixMyStreet Pro integrates with your existing systems, drives channel shift, and saves you money from day one.

**Comment by abimysoc** [comment]
User's email address visible in the screenshot - needs redacting.

**Comment by MyfanwyNixon** [comment]
Oops thanks @abimysoc - have removed the screenshot for now.

**Comment by zarino** [comment]
As @abimysoc would say – this doesn’t need a designer 🙂 Anyone can edit the text in this template, and then submit a pull request: https://github.com/mysociety/fixmystreet/blob/master/templates/email/fixmystreet.com/_submit_footer.html

**Comment by zarino** [comment]
This has been merged and deployed now.
