### ISSUE TITLE
Improve sort display of reports

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#308]
(This issue brought to you by my thwarted desire to look at the most recent reports in my area.)

I don't know how the current sorting of the list of issues works, but it could definitely be improved as I've been puzzled or annoyed by it several times now.

E.g. on http://www.fixmystreet.com/reports/Oxford the first three reports I see in the list are from last Sunday, 3 Dec 2011 and 30 April 2012.  From this we deduce that the sorting order isn't chronological.  Those three problems are not anywhere near each other on the map, so it clearly isn't geographical either.  Or by status (two are fixed and one isn't), or any variety of alphabetical.  There's definitely a consistent sort, as the list is the same in different browsers on different devices, I just can't work out what on earth it's sorting by.

Anyway, I think it would be nice to add the ability to re-order the report list by date, location (if not insanely hard - maybe by distance from the area shapefile centroid?), status, whatever other criteria people can think of.  And to filter it by selecting multiple variables, but now I stray into moon-on-stick territory.

**Comment by dracos** [comment]
DONE!
