### ISSUE TITLE
Can't click floating navigation links on /faq on desktop browsers

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#3287]
Looks like a layer ordering problem - double clicking selects the text in the main body of the page. Tested on Safari/Chrome/Firefox with the same result on each. Works fine on mobile.

**Comment by dracos** [comment]
It's due to my moving the navigation to the top in the HTML, but I don't yet see how. If I remove the div.nav-wrapper and the a name=content then it becomes clickable again, but neither of those two things cover the aside box.
