### ISSUE TITLE
handle attribute external_id (fms_id) as a special case in Open311 send-reports

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#329]
Proposed change: when sending a problem report over Open311 that has an attribute['fms_id'] , automatically populate that attribute with the report's id. 

FMS-endpoint expects the FMS report ID to be provided in an attribute called external_id (although there's a strong case for this being fms_id -- see https://github.com/mysociety/fms-endpoint/issues/19 so there's no risk of a nameclash with some other use of external_id).

Currently we're doing this by switching on the cobrand (fixmybarangay) which means FMS-endpoint doesn't quite work as expected with default FMS installs.

**Comment by dracos** [comment]
Dealt with, as `fixmystreet_id` (or overrideable id field name in PopulateServiceList), by #1499.
