### ISSUE TITLE
Reporting as another user, mandate either email or phone (0.5d)

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#3294]
When staff is reporting as another user, you can leave both email and phone blank (and then it creates basically an anonymous report for that staff user), it should presumably make sure you've entered at least one.

**Comment by dracos** [comment]
OTOH, it's the only way to leave a report with a different name and unknown email/phone. So perhaps it should mark it as an anonymous user report (so e.g. no questionnaire sent to staff user) but still record the name given.

**Comment by dracos** [comment]
Have done that suggestion (preventing questionnaire, think that covers the main issue) in https://github.com/mysociety/fixmystreet/pull/3390

**Comment by jacquelinebylau** [comment]
Toggl: https://plan.toggl.com/#timeline/317959/tasks/33852137/embed
