### ISSUE TITLE
Spot anonymous reports before sending questionnaires, auto-replies or other responses by email [4hrs]

### ISSUE THREAD

**Issue by sagepe** [mysociety/fixmystreet#3330]
**Describe the bug**
Sometimes questionnaires, auto-replies from bodies and other email is generated on anonymously made reports that do not have a valid email address associated.

**Expected behavior**
No emails should be sent for anonymous reports.

**Comment by dracos** [comment]
Reports made as body or anonymous will no longer send questionnaires.

**Comment by davea** [comment]
Moderation emails are incorrectly being sent for anonymous reports.

**Comment by jacquelinebylau** [comment]
Toggl: https://plan.toggl.com/#timeline/317959/tasks/33852437/embed
