### ISSUE TITLE
YAML Error: Inconsistent indentation level

### ISSUE THREAD

**Issue by UmairVarin** [mysociety/fixmystreet#3454]
YAML Error: Inconsistent indentation level
   Code: YAML_PARSE_ERR_INCONSISTENT_INDENTATION
   Line: 26
   Document: 1
 at /var/www/html/fixmystreet/local/lib/perl5/YAML/Loader.pm line 804.
Compilation failed in require at /var/www/html/fixmystreet/perllib/FixMyStreet/DB/Schema.pm line 22.
BEGIN failed--compilation aborted at /var/www/html/fixmystreet/perllib/FixMyStreet/DB/Schema.pm line 22.
Compilation failed in require at /var/www/html/fixmystreet/perllib/FixMyStreet/DB.pm line 5.
BEGIN failed--compilation aborted at /var/www/html/fixmystreet/perllib/FixMyStreet/DB.pm line 5.
Compilation failed in require at bin/update-all-reports line 19.
BEGIN failed--compilation aborted at bin/update-all-reports line 19.
 

Please tell me what's the issue, I'm stuck badly over here, many struggles I've done and I reached on this step
![image](https://user-images.githubusercontent.com/34236799/119986429-41f22d00-bfdd-11eb-834c-47b2e3e3f0b4.png)

After this error occurs, please anyone has a look, help will be appreciated..

**Comment by dracos** [comment]
That error means you have a mistake in your conf/general.yml file - hopefully on line 26, but it's possible the actual error is earlier in the file. You need to look at the changes you've made to that file and make sure it is consistent in the way you've inputted any lists or similar.

Support for using the software is best done on our mailing list as mentioned at https://fixmystreet.org/community/ - this repository is generally for features and bug reports in the software itself, not in people's use of the software.

**Comment by UmairVarin** [comment]
What is this issue now dear
[image: image.png]

**Comment by dracos** [comment]
Your image did not attach to that comment, I'm afraid, if you meant to include one.

**Comment by UmairVarin** [comment]
Check please

**Comment by UmairVarin** [comment]
![image](https://user-images.githubusercontent.com/34236799/120025190-c35fb480-c009-11eb-8776-b8c34906bd40.png)
This is stopping again and again, what should I do...

**Comment by dracos** [comment]
If the server is stopping when you start it, then it will be erroring, either on the console or to a log file. If you haven't fixed the original error you raised (I don't know, you haven't said), then the server will not run. To run a server in production, you could use one of the methods further down https://fixmystreet.org/install/manual-install/ than your screenshot, e.g via Apache+FastCGI, or via nginx as a daemon, and so on.

**Comment by dracos** [comment]
As the original issue is presumably fixed, I am closing this issue.

**Comment by UmairVarin** [comment]
Ok, thanks for the clarification. But tell me one thing, When I run on
script/server
it is running on  http://ghfixit.com:3000/, but I dont want to run always
this command... So tell me how can I visit my website on single link...
