### ISSUE TITLE
 Worker processes cleaned up / Server closing!

### ISSUE THREAD

**Issue by UmairVarin** [mysociety/fixmystreet#3455]
Could not finalize SSL connection with client handle (SSL accept attempt failed error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown)
Could not finalize SSL connection with client handle (SSL accept attempt failed error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown)
Could not finalize SSL connection with client handle (SSL accept attempt failed error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown)
Could not finalize SSL connection with client handle (SSL accept attempt failed error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown)
::ffff:59.103.194.182 - - [28/May/2021:18:17:05 +0000] "GET / HTTP/1.1" 200 9508 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
::ffff:59.103.194.182 - - [28/May/2021:18:17:06 +0000] "GET /cobrands/default/base.css?1622200423 HTTP/1.1" 200 81599 "https://ghfixit.com:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
Could not finalize SSL connection with client handle (SSL accept attempt failed error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown)
Could not finalize SSL connection with client handle (SSL accept attempt failed error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown)
Could not finalize SSL connection with client handle (SSL accept attempt failed error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown)
Could not finalize SSL connection with client handle (SSL accept attempt failed error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown)
2021/05/28-18:17:06 Bad fork [Cannot allocate memory]
  at line 167 in file /var/www/ghfixit.com/html/local/lib/perl5/Net/Server/PreFork.pm
2021/05/28-18:17:06 Received QUIT. Running a graceful shutdown
Sending children hup signal
Child process 6105 exited with status 0 - signal was 1
Child process 6108 exited with status 0 - signal was 1
Could not finalize SSL connection with client handle (SSL accept attempt failed error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown)
Child process 6111 exited with status 0 - signal was 1
2021/05/28-18:17:08 Worker processes cleaned up
2021/05/28-18:17:08 Server closing!

Please tell me how to solve it, when I try to run this command "script/server --listen :3000:ssl --ssl-cert=my.crt --ssl-key=my.key --Reload perllib,conf"

**Comment by dracos** [comment]
Please do not @ random people in issue reports. I have already said this repository is for bug reports in the software itself, not problems you are having getting the software to run. As to this issue, the error seems quite clear - "Cannot allocate memory" - your server does not have enough memory to run the server.

**Comment by UmairVarin** [comment]
OKay thanks dear
