### ISSUE TITLE
Update FMS installation webpage to specify correct Cypress version

### ISSUE THREAD

**Issue by ludovic-tc** [mysociety/fixmystreet#3523]
FMS currently requires a specific version of testing software Cypress to be installed (i.e. 3.8.3), rather than the latest version. 

This information should be added to https://fixmystreet.org/install/manual-install/ or another suitable location. 

The recommended command string is:

`npm install -g cypress@3.8.3 @cypress/code-coverage@3.9.4 codecov`

**Comment by dracos** [comment]
Fixed in 887d1d5cf
