### ISSUE TITLE
[% IF problem.councils > 1 %] <small>[% loc('(sent to both)') %]</small> [% END %]

### ISSUE THREAD

**Issue by timsk** [mysociety/fixmystreet#353]
https://github.com/mysociety/fixmystreet/blob/master/templates/web/base/report/_item.html [edit]

This appears to assume that there are never more than two levels of government responsible for a particular issue, and should perhaps be generalised to allow for more levels.

For example, France is sub-divided as état, régions, départements, arrondissements, cantons, communes, tennis courts, and carpet tiles, each of which has its own fiercely competitive administration. "Both" for n>1 may turn out to be inadequate.  :)

**Comment by dracos** [comment]
Done in fed75f471279cda99b877a6015024a5c59eeeafd!
