### ISSUE TITLE
Change/clarify wording for dashboard for authorities with devolved contacts

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#356]
If an authority has devolved contacts (as we do in FixMyBarangay), which effectively means problems reported there are being sent to several different authorities, then then wording on the dashboard suggests that problem reports are being fixed (or not fixed) by that authority. This seems misleading; consider breakdown of problems stats if this can make the actual division of responsibility clearer (I think part of the current problem is that we don't have a pretty name for a devolved contact, only an Open311 endpoint).

**Comment by dracos** [comment]
I think if I understood right if it was different bodies, it should be different bodies in FMS? Perhaps misunderstanding, but anyway, project dead
