### ISSUE TITLE
Send councils reminders once number of updates reaches certain level

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/fixmystreet#358]
Suggestion from user, perhaps worth considering (especially for those reports where someone fills in the questionnaire for months and months):

Some time ago I posted an update on an issue logged by somebody else.
Since then, the OP has posted many more updates which obviously go
nowhere.
I have also posted a couple of updates on some of my own reports and
the road affected remains untouched.

It occurs to me that if there is an input "hiccup" at the Council
call-centre when the fault is passed to them, then that's it. Similarly,
perish the thought, but if the relevant roads office was having a bad
day and "overlooked" the report rather than passing it out for
inspection, nothing more would happen. I realise that Councils should
have checks in place to guard against this, but do they?

Here is my bright idea! Would it be possible for you to place an
"update counter" on incidents and if the number of updates breaches a
threshold - say five, ten, fifteen - then a reminder/refresher gets sent
to the relevant Council? The existence of this counter need not be
advised to the general public but it would close a potential "pothole"
in your effectiveness.

Hope this is of assistance.

**Comment by Gemmamysoc** [comment]
User feedback: 

"I think you should be able to send a photo to the council when you
update a problem. Sometimes I add a photo after I've made a report,
for instance if I see something one day then take a photo of it when
I go back the next. It'd be good to know why photos aren't sent when
you update a problem. (I'm sure the council would find a photo of
the problem useful.)"

**Comment by MyfanwyNixon** [comment]
Via Twitter: 'maybe updates should be sent to council':

https://twitter.com/rugbytap/status/782895536462565377

**Comment by MyfanwyNixon** [comment]
On balance I agree with these users.

- Many users already think updates *are* sent to the council, despite the wording explaining that they aren't
- It's not really ideal to have to begin a new report if you want to chase an old one or say that a repair has been ineffectual
- Councils would probably be glad to be kept informed in the cases where community discussions are breaking out, but if any became overwhelming/off topic, perhaps we could introduce a 'don't send me any more updates' button for council workers, within the report emails; the reports where this had been clicked could have a design that showed this was the case.

**Comment by MyfanwyNixon** [comment]
Via [Twitter](https://twitter.com/therealmrbenn/status/822806461344583682):

>  If you don't send updates to the council, how am I supposed to get them to look at further evidence?

**Comment by abimysoc** [comment]
A further user comment in support of sending updates:

>If a problem is reported, then subsequently updated as fixed, couldn't that fixed update be sent on to the council? It might save some unnecessary council work.

**Comment by dracos** [comment]
Just not going to happen; would only annoy and lead to more refusing emails.
