### ISSUE TITLE
IoW test isn't actually testing anything

### ISSUE THREAD

**Issue by chrismytton** [mysociety/fixmystreet#3586]
This Isle of Wight test isn't actually testing anything.

https://github.com/mysociety/fixmystreet/blob/de7cca5338c578b7f74a4849636b524533bdcc79/t/cobrand/isleofwight.t#L342

It passes a `current_open311` parameter to `Open311::PostServiceRequestUpdates->new`, but that class doesn't support `current_open311` and therefore isn't actually testing anything.

https://github.com/mysociety/fixmystreet/blob/de7cca5338c578b7f74a4849636b524533bdcc79/t/cobrand/isleofwight.t#L391-L393

**Comment by dracos** [comment]
Coincidentally I was doing https://github.com/mysociety/fixmystreet/pull/3588 on Friday which changes how these things are mocked (which was the reason for the current_open311 here), so I think without realising it it may have fixed it/this code isn't needed in the test (with a small tweak I've just pushed).
