### ISSUE TITLE
Links in alert emails hard to read

### ISSUE THREAD

**Issue by chrismytton** [mysociety/fixmystreet#3643]
We've had a report from a user that the blue links in alert emails are hard to read.

They provided this screenshot:

![image0](https://user-images.githubusercontent.com/22996/140292650-43e059b1-f3b0-4091-aa47-22a8a90c76a7.png)

It looks like they have dark mode enabled, which could be related?

**Comment by dracos** [comment]
https://www.litmus.com/blog/the-ultimate-guide-to-dark-mode-for-email-marketers/ weirdly says Apple Mail doesn't change anything in HTML email? So I'm confused as to what's happening here.
![image](https://user-images.githubusercontent.com/154364/140301806-ede699c5-f16d-4dc7-a7d6-9d82905eff95.png)

The grey background certainly implies to me it thinks it can apply dark mode, but hasn't worked out some of the text colours. <Insert auto-dark mode if you can't do it properly, don't bother grumble here>

**Comment by lizettal** [comment]
Added to design sprint https://trello.com/c/MLYodxUx/1005-links-in-alert-emails-hard-to-read

**Comment by zarino** [comment]
Can confirm, looks like this on my iPhone 11 Pro running iOS 14.8.1 in dark mode:

![IMG_FDE79DE8BB15-1](https://user-images.githubusercontent.com/739624/140947098-9276f844-cd73-4eaa-bce9-e8aef2303804.jpeg)
