### ISSUE TITLE
Hide "assigned to" bits when there's noone to assign reports to [4hrs]

### ISSUE THREAD

**Issue by chrismytton** [mysociety/fixmystreet#3646]
Since the changes to the inspector tool in #3535 we're now showing "Assigned to:" in a couple of places, even when it's not relevant.

On the admin report_edit page, underneath the category dropdown:

<img width="216" alt="Screenshot 2021-11-08 at 15 58 57" src="https://user-images.githubusercontent.com/22996/140775579-f34284b7-3646-4147-83d5-8856c168228b.png">

On the report page's inspector sidebar:

![image](https://user-images.githubusercontent.com/22996/140775621-5921e7e3-05e4-4cf6-a042-f455d14c5460.png)

I think these should only be shown if there are users with the relevant permission.

Related Freshdesk ticket: https://mysocietysupport.freshdesk.com/a/tickets/1579

**Comment by dracos** [comment]
Also on list pages, anywhere in the country, I'm seeing it on every report in the sidebar, it's a bit annoying.

**Comment by jacquelinebylau** [comment]
Toggl: https://plan.toggl.com/#timeline/317959/tasks/33843711/embed
