### ISSUE TITLE
Manage my own robots.txt

### ISSUE THREAD

**Issue by fixmystreetfr** [mysociety/fixmystreet#3656]
i want use my own robots.txt
how can i simply manage it ?
Added without success in my template or cobrands web directory but without any effect.

**Comment by dracos** [comment]
Hiya - the easiest way would probably be to add something to your web server to serve a different file directly. For example, if you're using nginx:
```
location /robots.txt {
    alias /path/to/your/robots.txt;
}
```

**Comment by fixmystreetfr** [comment]
oooh good idea :) why i did not think that before posting ....

thanks
