### ISSUE TITLE
Un-document manual Mac installation

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#3689]
**Is your feature request related to a problem? Please describe.**
https://github.com/mysociety/fixmystreet/pull/3630 – Manual Mac installation (with the documented `brew install gettext perlmagick jhead postgresql`) fails, because the `perlmagick` homebrew formula is no longer available, and the closest thing we‘ve got is @davea’s unsupported, outdated [`homebrew-perlmagick` mirror](https://github.com/davea/homebrew-perlmagick).

**Describe the solution you'd like**
We have a working Docker setup, for running FMS on Intel and Apple Silicon Macs. Mac users should use that.

Remove the Mac installation instructions from the FMS documentation – or at least make clear they’re only _indicative_ and won’t work without modification.

Close https://github.com/mysociety/fixmystreet/pull/3630.

**Describe alternatives you've considered**
We considered officially "adopting" @davea’s [`homebrew-perlmagick` mirror](https://github.com/davea/homebrew-perlmagick). But we really can’t guarantee we’ll always be able to keep it up to date with upstream. We shouldn’t have to maintain Perl bindings for a dependency of FMS.

**Comment by dracos** [comment]
Have added a line of explanation to the docs HomeBrew section. I think I'd probably be able to get it running should I get a Mac, so didn't want to totally remove it ;)
