### ISSUE TITLE
Allow placing of pin by entering latitude and longitude directly

### ISSUE THREAD

**Issue by struan** [mysociety/fixmystreet#371]
User suggestion:

The reports you send to councils seem to take location data (OS or
lat/long) from the map pin. However, placing the pin in the right place can
be difficult on country roads where there are no obvious land marks, hence
my use of GPS. It would be useful if there were a facility where GPS data
could be entered by the user and, if entered, this should replace the
information derived from the map pin. Even better would be to place the pin
using the GPS data provided by the user.

**Comment by dracos** [comment]
You can enter lat,lon in the front page box and it will go there, which might help (and note when you click map, you could change co-ords in URL and hit refresh). Also tie in with #15
