### ISSUE TITLE
Default to unchecked for 'name appearing on site' checkbox

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#374]
Suggestion from user, via email 8/1/13:
The public default should  be "anonymous", although the site
     administrator should be able to view the poster's name. I feel
     that complaining to officialdom, like voting, should be
     private.

**Comment by Gemmamysoc** [comment]
User feedback:

It would be really helpful if the default was either for anonymous posting, or could be set by the user.

**Comment by Gemmamysoc** [comment]
User feedback: "Box for making sure report is anonamous unclear and broken on mobile
app. Make option larger and clearer at start of report."

**Comment by MyfanwyNixon** [comment]
Hey Gemma, previous comment might be better on https://github.com/mysociety/fixmystreet-mobile/issues

**Comment by Gemmamysoc** [comment]
Thanks Myf, I actually added it to this ticket too: https://github.com/mysociety/fixmystreet-mobile/issues/194 I will delete it from this thread :)

**Comment by Gemmamysoc** [comment]
User feedback:

"is there a way to remain anonymous permanently rather than having to
choose every time."
