### ISSUE TITLE
Unexpected error from process-inactive-accounts

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#3761]
**Describe the bug**

We recently got a Cron message related to the command...

```
$ "/var/www/fixamingata.se/fixmystreet/bin/process-inactive-accounts" --anonymize 12 --email 11
```

... saying:

> Argument contains empty address at /var/www/fixamingata.se/fixmystreet/local/lib/perl5/Email/MIME/Encode.pm line 70.

**To Reproduce**

N/A

**Expected behavior**

No “Argument contains empty address” message.

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**

 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

The server is running Debian GNU/Linux 10 (Buster).

This only happened once. Subsequent invokations of the script didn't generate this message again.

**Comment by dracos** [comment]
What version are you running? This sounds like something that could have been fixed by https://github.com/mysociety/fixmystreet/commit/251acf7799e78fd46a39154f0381c7470d5542a9 - at least that commit certainly prevents it trying to send email to empty addresses.

**Comment by jonkri** [comment]
Hi @dracos!

Thank you for your reply! :slightly_smiling_face: 

We are running https://github.com/Sambruk/fixmystreet/commit/cda52d35288a30900e67ada6f5504483d1445a54, so 251acf7 is currently not applied.

Under what circumstances will addresses be empty?

Do you have any idea why this “Argument contains empty address” message was only sent once?

The script seems to run fine now:

```
$ "/var/www/fixamingata.se/fixmystreet/bin/process-inactive-accounts" --anonymize 12 --email 11
$ echo $?
0
```

I'm assuming that the script exiting normally means that this bug could not be preventing 1) “inactive” e-mails from going out or 2) accounts from being anonymized. We are planning to upgrade to version 4, but it probably won't be for a couple of weeks or so. Do you see a reason to cherry-pick 251acf7 before that? All things equal, I'd rather wait for the planned upgrade.

**Comment by dracos** [comment]
An address could be empty if it was a phone-only account, for example. It was only sent once, because the script sets a flag on any account it is sending an email for, to not send one again. So yes, this bug won't have caused any issues at all,it just meant it couldn't send the inactive email to an account that didn't have an associated email address. So there should be no issues in waiting.

**Comment by jonkri** [comment]
Thank you, @dracos! :pray:
