### ISSUE TITLE
Logos appear not good in email client in dark mode

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/fixmystreet#3768]
![Screenshot_20220129-081249_K-9 Mail](https://user-images.githubusercontent.com/11923618/151653689-8f502b92-cac2-4cc4-b8cf-b1b378eb4e8c.jpg)

**Comment by chrismytton** [comment]
This should now be fixed by the changes in https://github.com/mysociety/fixmystreet/commit/6d15fc86630a07366565ed055a302cc858cff588.
