### ISSUE TITLE
Emails should not be sent to cobrand's anonymous user account

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#3770]
For reports made anonymously (using the "Report anonymously" button, or "Report as anonymous user" by members of staff), FMS shouldn't try and send any emails.

The following emails are known to be sent, there may be others:

- [ ] [Moderation notifications](https://github.com/mysociety/fixmystreet/blob/a2e8c80e35570c34b87543a9e4b312e49f05d2fd/perllib/FixMyStreet/App/Controller/Moderate.pm#L192-L208)

Related to https://github.com/mysociety/sysadmin/issues/1599

**Comment by sagepe** [comment]
See also #3330

**Comment by davea** [comment]
Thanks @sagepe, I hadn't spotted that. Closing this in favour of the existing ticket.
