### ISSUE TITLE
Enable smaller movements with modifier key when using keyboard to move around the map

### ISSUE THREAD

**Issue by struan** [mysociety/fixmystreet#3819]
Further to #3321 it'd be nice to be able to use a modifier key (e.g CTRL) when moving about the map to make smaller movements to enable more precise positioning of the pin, a la photoshop etc. The current jumps are quite large even on the highest zoom level so pin positioning is a bit approximate.

**Comment by dracos** [comment]
Done in https://github.com/mysociety/fixmystreet/commit/1f51f92fabe99dc630463c7e13529d2fccfedb5a
