### ISSUE TITLE
IRC/Freenode

### ISSUE THREAD

**Issue by KanchiMoe** [mysociety/fixmystreet#3906]
Hi all,

If you're not aware, in 2021 the IRC network freenode had a "hostile takeover" by a 3rd party. [More information can be found here](https://en.wikipedia.org/wiki/Freenode#Ownership_change_and_conflict).

As such:
- Communities that existed on freenode moved to [Libera.Chat](https://en.wikipedia.org/wiki/Libera_Chat).
- The #fixmystreet channel was deleted.

The 2 links/references to freenode are:
- https://github.com/mysociety/fixmystreet/blob/master/docs/community/index.md
- https://github.com/mysociety/fixmystreet/blob/master/docs/community/irc.md

What would be FixMyStreet's view or action for this?
- Should the community migrate, or stay on freenode?
- Should the references be removed?

**Comment by dracos** [comment]
Hi, Thanks for reporting this. We were aware, apologies for not getting around to doing anything about it until now. I've removed the embedded page, and updated the main page to point at Libera.chat, where there is a room set up though sadly I don't think it gets much use nowadays (including from myself, I'm afraid).
