### ISSUE TITLE
Allow report to be marked as not going to be sent [4hrs]

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#3908]
You can mark a report as sent in the admin, but would be good to have a way to remove the bodies_str entirely if it's not going to be sent (or some other way of doing that - that's historically the way a report exists but "not reported", but that does lose the "who would this report have gone to" - if we want a difference between that, might need a different way of marking this, but is rare?)

**Work required**

- [x] Add a way to edit the send state of a report from the admin

**Comment by dracos** [comment]
Ties in with https://github.com/mysociety/fixmystreet/issues/4048

**Comment by lizettal** [comment]
@dracos this old ticket is showing as in progress, but the ticket you linked above is complete so is there anything further that needs doing on this ticket?

**Comment by dracos** [comment]
Yes, we still ideally would like a way to edit the send state of a report from the admin, which is currently not possible.
