### ISSUE TITLE
User suggestion for promotional products - car stickers

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#392]
I needed to report a serious pot hole issue in my neighbourhood
     and simply by "googling" pot holes, came across your fantastic
     website. I had never heard of your website before - so do you
     have or intend issuing car window stickers for extra awareness
     for motorists ?

**Comment by abimysoc** [comment]
I happen to be sitting next to a box labelled 'FixMyStreet car stickers' so I'm calling this done.
