### ISSUE TITLE
User suggestion: better route to reporting a subsequent problem

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#393]
Feedback via email:

 I really like this site. One thing: having reported a problem I
     cannot see a way of simply reporting another problem further up
     the map. That is, I would like to scroll the map following a
     route (say, my commute) and stick pins in it as I go along.
     Clicking the 'Report a problem' button takes you back asking
     for a post code or place, not the location you had previously
     scrolled to on the map.

**Comment by dracos** [comment]
Will see if #1351 has any bearing on this (might well do, if we make report pages and around pages act more similarly).

**Comment by abimysoc** [comment]
Support email today entitled "Unable to report a problem - no field on site to do so"; got the user to supply a screenshot; they were on a report page, presumably expecting the map to be clickable to report a problem at/near that location.

**Comment by dracos** [comment]
Hmm, I was going to say if they had gone directly to a report page we should add the other pins around the area, so it acts more like an around page, but I see from the screenshot that was the page they were on (with other pins viewable). So this is more similar to #1462, they clicked map in right location, but were actually clicking a report pin and then didn't know what to do. I don't think they expected the map to be clickable, from their POV they had already clicked it. If the floating banner from https://github.com/mysociety/fixmystreet/issues/1519#issuecomment-248543620 was done, this could still be shown on a report page but saying "Report a new problem HERE" to cover this case.
