### ISSUE TITLE
Map bug when attempting to pan the map while pressing on a report pin

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#4132]
**Describe the bug**

The map can enter a state where:

- Panning touch movements (**not** pinch/zoom movements) can result in the map being zoomed in our out.
- Existing reports can no longer be opened. (Instead, FixMyStreet offers to create a new report when touching a pin.)

**To Reproduce**

1. Search for a location where there are map pins
2. Touch a pin and immediately (while pressing down on the pin) pan the map
3. A preview of the report shows up
4. The map may now (it doesn't always happen) have entered the state described above

**Expected behavior**

The map should continue to work like it did before opening the report preview. Panning movements should pan the map (not zoom it). Additionally, touching existing map pins should show a preview of the report in question (as opposed to offer to create a new report).

**Screenshots**

Here's a video:

https://fixamingata.se/static/fixmystreet-map-problem.webm

Please not that only panning movements (no pinch movements) were performed after the report preview was opened. Despite this, the map is zoomed in an odd way.

**Smartphone (please complete the following information):**
 - Device/OS: Emulated Pixel 3a
 - OS: Android, API 32
 - Browser: Chrome
 - Version: 91.0.4472.114

**Comment by jonkri** [comment]
Here's a video showing the problem on a physical Android device:

https://fixamingata.se/static/fixmystreet-map-problem.mp4

The user who sent this video to us said he experiences this issue everytime he uses the map. (That was prior to the changes in #4220 which, while not solving the problem completely, appears to have helped.)

**Comment by dracos** [comment]
Sorry to hear this. I'm not sure what could be causing it, and haven't had any other complaints come in. I assume it's some sort of race condition or conflict in terms of the touch events being sent by the browser. I don't see how it would get in a zoom-instead-of-pan state if the browser is sending the right events. I can't reproduce it here, but someone would have to trace what's happening when it does happen in terms of which events are fired, which code paths are run, and so on.

**Comment by dracos** [comment]
Actually of course now saying that I did manage to have it happen to me too. Wonder what it could be.
