### ISSUE TITLE
Bug when pressing the back button twice after leaving report page via the around view

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#4175]
**Describe the bug**

When a user leaves a report via the around view and presses the back button twice in order to return to the around view, the back button doesn't work the second time.

**To Reproduce**

1. Visit a report via the around view (It doesn't matter if All reports or searching via the home page is used)
2. Click on a report.
3. Leave an update, click "Help", or anything that involves a page load of a new page.
5. Click the back button (The report page with the new update is (correctly) displayed)
6. Click the back button again (Do **not** click on Back to all reports; instead, use the browsers native back button)
7. The UI is unchanged and the console displays "TypeError: can't access property "use_page", fixmystreet.markers.protocol is null" triggered from an assignment to `fixmystreet.markers.protocol.use_page` in `setup_popstate` (line 1957)

Stack trace:

- `setup_popstate` `/cobrands/fixmystreet/fixmystreet.js:1957`
- `setup_popstate` `/cobrands/fixmystreet/fixmystreet.js:1917`
- `setTimeout handler*setup_popstate` `/cobrands/fixmystreet/fixmystreet.js:1915`
- jQuery
- `<anonymous>` `/cobrands/fixmystreet/fixmystreet.js:1910`
- jQuery

**Expected behavior**

- I expect the UI to look like it did after having completed Step 1.
- No error message in the console.

**Screenshots**

Not applicable.

**Desktop (please complete the following information):**

 - OS: macOS
 - Browser: Firefox
 - Version: 107.0

**Additional context**

I reproduced this problem with ccfa9579a0a83353eb787ff8dd1485ab30199e4c, the latest commit on the `master` branch on this repository (mysociety/fixmystreet).

**Comment by dracos** [comment]
This is hopefully fixed by 2850dc6956df0c5fdccb09aabdd410f11ed1dcc4  in https://github.com/mysociety/fixmystreet/pull/4260

**Comment by jonkri** [comment]
> This is hopefully fixed by the "Fix JS error going back from page to report page to map page." commit in #4260

Thanks! It seemed to work when I tried it out, and we're now testing it in production.

**Comment by jonkri** [comment]
We're running FixMyStreet 4.0 and we seem to be having some difficulties testing the changes in #4260 in production. Just cherry-picking the commits seemed (based on a message from a body user I received) to lead to an error where the shortlist filter could show reports from other users' shortlist. We have sinced rolled back the commits.

Perhaps we will have to defer testing the changes until there's a new FixMyStreet release.
