### ISSUE TITLE
Crosshair way of positioning map pins

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#4176]
**Is your feature request related to a problem? Please describe.**

It can be difficult to position map pins using touchscreens, in particular with smaller devices like phones.

**Describe the solution you'd like**

The crosshair way of reporting (used in the Cordova app) is arguably better suited for touchscreens.

**Describe alternatives you've considered**

None.

**Additional context**

See the message [here](https://groups.google.com/a/mysociety.org/g/fixmystreet/c/-E8kZALgvBE/m/sGwCxaFUAgAJ).

**Comment by dracos** [comment]
Hi @jonkri - yes, like my message you link to, I think I agree (Google Maps directions uses a crosshair method too on mobile, I see) - so we'll try and get some time in the near future to look at trying to implement this with some user testing.

**Comment by jonkri** [comment]
@dracos: Hi! 👋 Thank you! 🤞
