### ISSUE TITLE
Display different text depending upon category selected

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/fixmystreet#42]
So that we can give specific prompts (e.g., if street lighting is picked then it could ask the user to find the light number) rather than generic hints.

Related to this: add in categories for reports which we DON'T want (e.g. noise, ASB, speeding, bins, etc.) and filter the user elsewhere if they are selected.

**Comment by dracos** [comment]
The admin interface lets you add extra notices per category which are shown, and disable form per category, so I think this can be considered done in the general case.
