### ISSUE TITLE
Update filter_category docs in manual

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#4282]
Copy of #4118 just for the docs update, which is higher priority.

The `filter_category` parameter can be used to prefilter the map & preselect a category when linking to FMS. However the current behaviour doesn't seem to line up with the manual, which suggests the `filter_category` parameter [can be used on its own](https://www.fixmystreet.com/pro-manual/deep-linking/):

> [...]an extra parameter that will restrict the default map view and reporting to a particular category[...]

For example this link will prefilter the map to Graffiti reports but doesn't select that subcategory on the reporting form (even if the user knows what top-level category to select): https://fixmystreet.merton.gov.uk/?filter_category=Graffiti

Including the `filter_group` parameter _does_ preselect the top-level category and subcategory: https://fixmystreet.merton.gov.uk/?filter_category=Graffiti&filter_group=Street%20Cleaning%20Problems%20or%20Weeds

However this doesn't always work, e.g. https://fix.bathnes.gov.uk/?filter_group=Drains%20and%20flooding&filter_category=Blocked%20drain:%20Blockage%20on%20surface will prefilter the map to all subcategories in 'Drains and flooding' and doesn't preselect the 'Blocked drain: Blockage on surface' subcategory. This is because the `filter_category` parameter must use the category's actual name, not display name, which in this case is `Blocked drain surface`. This link works as expected: https://fix.bathnes.gov.uk/?filter_group=Drains%20and%20flooding&filter_category=Blocked%20drain%20surface

### Work required

- [ ] Ensure user manual is updated with accurate instructions for using the feature

Related to FD-2412.

**Comment by nephila-nacrea** [comment]
Some notes:
- We don't seem to handle categories containing a `+` - we use `+` to denote spaces so I think the system gets confused. (Haven't come across any `+`-categories in the wild on live, however).
- We support a comma-separated list for selecting multiple `filter_category` values, but do not do the same for `filter_group`.
