### ISSUE TITLE
Make it easier to report issues on greenways.

### ISSUE THREAD

**Issue by neprune** [mysociety/fixmystreet#4288]
From user support inbox:
> When reporting issues on greenways it’s difficult to confirm location with street type map. Why don’t you have satellite or what three words options. I’ve reported several footpath and greenway issues most of which they say they can’t follow up because they can’t find them. Even with pictures.

**Comment by dracos** [comment]
We do have satellite - click the little picture of a satellite?

**Comment by dracos** [comment]
I'm not sure there's anything actionable here, I'm afraid; we have geolocation, so if you're in the location you can report it using that, I don't think we have any plans for anything else. We're not using W3W.

**Comment by davea** [comment]
It's possible the user is using the app, which doesn't have satellite view currently. The forthcoming update will bring that functionality though.
