### ISSUE TITLE
Contact form not working

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/fixmystreet#4383]
**Describe the bug**
When submitting the contact form at https://www.fixmystreet.com/contact the error shows: "There was a problem showing this page. Please try again later. "

**To Reproduce**
1. Go to https://www.fixmystreet.com/contact
2. Enter your message and other data
3. See error

**Expected behavior**
An acknowledgement of the sent message

**Screenshots**
![Screenshot_20230413_094905_Chrome](https://user-images.githubusercontent.com/11923618/231707968-93515be4-a11e-4239-8b18-f02f2998275a.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S22 Ultra
 - OS: Android 13
 - Browser Chrome
 - Version 112.0.5615.48

**Comment by davea** [comment]
Thanks for the report. A couple of questions:

 - Were you logged in or out when using the form?
 - Which of the Topic options did you select?

**Comment by kingqueen3065** [comment]
Hi

"I have feedback about the site"

This was the message:

"Hi
Have you any idea how this spam has appeared as an "update"?
https://streetcare.tfl.gov.uk/report/4383264
Thank you! I enjoy it! delaware online casino <a href=https://bestonlinecasinoreal.us/ >casino game online</a> best online blackjack casino

Posted anonymously at 22:23, Tuesday

It then was automatically sent to my friend in an email from FMS.

Cheers

Doug"

**Comment by dracos** [comment]
Yes, the contact form will block that submission due to the spam in it (and sadly can't give a nice error message as that would assist spammers). We've blocked the subnet responsible for this spam and looking at other ways to prevent it. Sorry for the inconvenience/confusion.
