### ISSUE TITLE
Promote our survey

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#4419]
We're currently running a series of surveys in the hope of gathering material to go into our anniversary impact report. It's FMS' turn at the moment.

The aim is to try and get responses from people who have used FMS successfully, and ideally have achieved something meaningful. For example, they might have lobbied for a zebra crossing, got a piece of wasteland turned into a community garden or had a particular reason for wanting their local streetlights fixed... or, even better, they've done something that we'd never have thought of ourselves!

Please could we add a '[Fill in our survey](https://survey.alchemer.com/s3/7284721/How-have-you-used-FixMyStreet)' link to some or all of the following:

- The 'success' screen when someone reports a problem as fixed
- Alert emails to people who have subscribed to a local area
- The site banner
- Anywhere else that feels appropriate

Responses from councils are welcome too, so maybe @sallybracegirdle could put the request into a newsletter as well? Councils might have something to say about their backend experience, or they might know of a citizen whose usage is worth highlighting. 

We'll be promoting this survey for the period of a month. 

Thanks!

**Comment by dracos** [comment]
We are already asking users to fill in a survey when they complete a questionnaire for @sallybracegirdle/@ajparsons. Should that be replaced with this? If you don't mean that page, I'm not sure what you mean by the 'success' screen, are you thinking of something in particular there?

The main place to change would be the `templates/web/fixmystreet.com/next_steps.html` template which is displayed in a few places and currently has Spread the world/share; Donate; link to Goodies page in three columns (rows on mobile). Which of those would you want to change to link to the survey?

Alert emails - how would you want this to be worded/look? We can probably add some basic text, but have to be careful it only applies to .com and not cobrand alerts.

I'd probably not suggest the site banner, given lots of people are updating the app at present and some not enjoying it.

**Comment by MyfanwyNixon** [comment]
Thanks both!
By success' screen I meant when people click on 'yes my problem was fixed' but I am happy to take advice on the best spot. It has been a while since I've been through that process myself so I can't remember if you just get a 'that's great' screen or if it's the one you mention.

Out of the three calls to action you mention, it feels to me like 'spread the word' is the most expendable for now so we could switch that over for now if that's ok.

Alert emails: for the WDTK ones they just put 'Please fill in our survey' , followed by the link, at the very top. As it happens I had provided some text but actually I think this concise version sufficed and may actually have been intriguing enough to encourage people to click through.

**Comment by dracos** [comment]
Have replaced existing survey with this one (and shown whenever `next_steps.html` is shown, not only after main questionnaire), and added line to top of email alerts.
