### ISSUE TITLE
Map panning breaks in mobile app after long press (zooms)

### ISSUE THREAD

**Issue by neprune** [mysociety/fixmystreet#4423]
From user support:

*Steps to reproduce*

On Samsung Android 13, with chrome as the default browser, launch either [fixmystreet.com](http://fixmystreet.com/), or [report.brent.gov.uk](http://report.brent.gov.uk/) (in the latter case launching directly with chrome or using the Report Brent app to launch it).

Tap "use my current location" (entering a location and and tapping the looking glass also exhibits the problem).

Long press within the map areas until the chrome context menu appears (for the map tile image).

Dismiss the context menu (either by tapping outside it, or by tapping the device's bottom right soft key).

Slide single finger across map.

*Expected behaviour*

Map pans along with the finger, at constant zoom.

*Actual behaviour*

The map zooms with some slight panning and can also jump around. I'm not certain, but it may be behaving as though it was seeing one finger permanently down, so the single finger, used to pan, is interpreted as the second finger in a zoom gesture.

*Additional information*

I've found this very easy to trigger accidentally, particularly when trying to look at existing reports nearby, as well as if I'm a little slow off the mark starting finger slide.

I generally have to go back to the starting screen to get it out of this state.

If the use of the desktop version is forced on the same device, it does not show the same problem.

The problem has been present since I first started using the mobile version, about a month ago.

*Version Information, etc.*

Android 13

One UI 5.1

Chrome 112.0.5615.135

Report Brent 2

FixMyStreet.com/[report.brent.gov.uk](http://report.brent.gov.uk/) Live versions as of 2023-05-08T12:00:00+0000 (I can't see how to find the corresponding GitHub versions)

<details>
<summary>Device details</summary>
Device Product Name: Galaxy A22 5G

Device serial number: R9AT5031X7X

Kernel: 4.14.186-25962536 #1 Tue Mar 21 12:32:29 +07 2023

Security patch level: 1 April 2023

DROID INFO REPORT

DEVICE
Model: SM-A226B (a22xnseea) [About phone on device says SM-A226B/DSN]
Manufacturer: samsung
Baseband Version: A226BXXU5DWC1,A226BXXU5DWC1
RIL Version: Samsung RIL v5.0
Build Number: TP1A.220624.014.A226BXXU5DWC1
Build Fingerprint: samsung/a22xnseea/a22x:13/TP1A.220624.014/A226BXXU5DWC1:user/release-keys
Bootloader: A226BXXU5DWC1
Java VM: ART 2.1.0
OS Version: Tiramisu (13)
SDK: 33

DISPLAY
Resolution: 1080x2408 pixels
Software Density: 480 dpi (xxhdpi)
Refresh Rate: 60 Hz

PROCESSOR
CPU Architecture: ARMv8-A
Board: a22x
Chipset: MT6833V/NZA
Cores: 8
Clock Speed: 500 MHz - 2203 MHz
Instruction Sets: arm64-v8a
CPU Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU Governor: Not Available
Kernel Version: 4.14.186-25962536
Kernel Architecture: aarch64

GRAPHICS
Renderer: Mali-G57 MC2
Vendor: ARM
OpenGL Version: OpenGL ES 3.2

RAM
Total: 3631 MB
Java Heap: 256 MB

STORAGE
Internal: 49.7 GB
EXTERNAL: Not Detected

PRIMARY CAMERA
Resolution: 12 MP
Flash: Yes
Video Resolution: WQHD, 2560x1440
Supported Resolutions:
Image:
4000x3000
4000x2250
4000x1800
3840x2160
3264x2448
3000x3000
2560x1920
2560x1440
2408x1152
2408x1080
2048x1152
1920x1440
1920x1088
1920x1080
1600x720
1560x720
1520x720
1440x1440
1440x1088
1440x1080
1440x720
1280x960
1280x720
1080x1080
1080x720
960x720
720x720
720x480
640x480
352x288
320x240
176x144

Video:
2560x1440 (WQHD)
2408x1152
2408x1080
2048x1152
1920x1440
1920x1088
1920x1080 (Full HD)
1600x720
1560x720
1520x720
1440x1440
1440x1088
1440x1080
1440x720
1280x960
1280x720 (HD)
1080x1080
1080x720
960x720
720x720
720x480
640x480 (VGA)
352x288
320x240
192x144
176x144

SECONDARY CAMERA
Resolution: 8 MP
Video Resolution: WQHD, 2560x1440
Supported Resolutions:
Image:
3264x2448
3264x1824
3264x1472
2560x1920
2560x1440
2448x2448
1920x1440
1920x1088
1920x1080
1600x720
1560x720
1520x720
1440x1440
1440x1088
1440x720
1280x960
1280x720
1080x720
960x720
720x720
640x480
320x240

Video:
2560x1440 (WQHD)
2408x1080
1920x1440
1920x1088
1920x1080 (Full HD)
1600x720
1560x720
1520x720
1440x1440
1440x1088
1440x1080
1440x720
1280x960
1280x720 (HD)
1080x1080
1080x720
960x720
720x720
720x480
640x480 (VGA)
352x288
320x240
192x144
176x144

FEATURES
Bluetooth: Yes
Bluetooth LE: Yes
GPS: Yes
NFC: Yes
USB Accessory: Yes
WiFi: Yes
WiFi Direct: Yes

BATTERY
Technology: Li-ion
Health: Good

SENSORS
icm40607_acc
mmc5603
ORIENTATION
icm40607_gyro
stk33562_l
stk33562_p
GRAVITY
LINEARACCEL
ROTATION_VECTOR
UNCALI_MAG
GAME_ROTATION_VECTOR
UNCALI_GYRO
SIGNIFICANT_MOTION
STEP_DETECTOR
STEP_DETECTOR_WAKEUP
STEP_COUNTER
GEOMAGNETIC_ROTATION_VECTOR
TILT_DETECTOR
UNCALI_ACC
A96T3X6 Grip sensor
A96T3X6 Grip sensor for sub
A96T3X6 Grip sensor for wifi
Screen Orientation Sensor
Motion Sensor
Orientation Sensor

Created by Droid Info
</details>

**Comment by davidw65** [comment]
This is actually mine.

I've experimented a bit more and it is definitely behaving as though a finger was still down at the location at which the long press was made.  The map implodes as you approach that point.

Also, I tried it with with the developer options for tap and cursor tracking enabled.  If I interpret the information at the top of the screen correctly (P:1/1, when trying to pan), the system itself has the correct finger down count.

Would a video of the screen be useful? That probably depends on whether you can successfully reproduce it.  A dry run came out at 21MB, and I don't know if there are filesize limits on bug report attachments.  This model doesn't seem to include the Android screen recorder, so I would have to use a third party app.

**Comment by dracos** [comment]
I added `user-select: none` in https://github.com/mysociety/fixmystreet/pull/4401 which should have prevented any user selection on the map, but clearly isn't working properly. I can't reproduce this in Safari on iOS or on Chrome 81 on an old Android (long press on the map does not show the context menu at all), but can reproduce on Chrome 113 on a newer Android. I think the solution will be to put a user-select: none somewhere where it will take effect properly, but finding out where that is might be the tricky step.

**Comment by dracos** [comment]
A hopeful fix for this, disabling the context menu on the map, has now been deployed.

**Comment by davidw65** [comment]
Sees to work for me.
