### ISSUE TITLE
Outlook 'safelinks' breaks confirmation link UX.

### ISSUE THREAD

**Issue by neprune** [mysociety/fixmystreet#4543]
An Outlook 'safelink' visits the confirmation link before the user is directed to it, effectively clicking it twice, doing the actual confirmation the first time.
When the report is already confirmed, visiting a confirmation link redirects to the report without logging the user in, to prevent the scenario of someone sharing their confirmation link rather than their report link by accident, and others gaining access to their account.
This means for public reports, a user using Outlook 'safelinks' is directed to the report page, rather than the post-confirmation page, and doesn't get logged in. For private reports the user sees an access denied page instead.

**Comment by davea** [comment]
Do we know if the automated visit from Outlook identifies itself in any way? User-Agent header or something? If we determine the request isn't from a real user we could skip the logic that invalidates the token.

**Comment by neprune** [comment]
It doesn't appear they send any User-Agent header.
