### ISSUE TITLE
Reports filter doesn't show correct selection on Your Account page

### ISSUE THREAD

**Issue by HandyHat** [mysociety/fixmystreet#4558]
**Describe the bug**
On the Your Account page (https://www.fixmystreet.com/my), the reports filter says "Open" when no filtering options are selected. Rather than only showing open reports, however, all reports are shown.

**To Reproduce**
1. Go to https://www.fixmystreet.com/my
2. Observe how the filter dropdown says "Open"
3. Observe that all reports, regardless of status, are shown.
4. Click on "Open" to see that no filters are selected.

**Expected behavior**
The filter to say "All" when no filtering options are selected.

**Screenshots**
![image](https://github.com/mysociety/fixmystreet/assets/58530748/bc88d550-b58f-473f-8563-0c9cb4e639be)

![image](https://github.com/mysociety/fixmystreet/assets/58530748/acac9bb0-c0c9-4e53-8314-81e38f72a0fa)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 115.0.1901.188

**Comment by dracos** [comment]
Thanks for spotting this! Should be fixed next deploy.

**Comment by HandyHat** [comment]
Thank you! 🚀
