### ISSUE TITLE
Duplicate council option in FMS technical support contact page

### ISSUE THREAD

**Issue by ethanknights** [mysociety/fixmystreet#4676]
**Describe the bug**
On the [contact page ](https://www.fixmystreet.com/contact), in this section:
`Send a message to FixMyStreet’s technical support team`

The 3rd and 4th options below in bold are duplicated: 

I need help using the site
I have feedback about the site
**I am from a council and I have a question for the FixMyStreet team
I am from a council and I have a question for the FixMyStreet team**
I want to report a street problemMy street problem hasn’t been fixed

- Issue appears across chrome & firefox.
- Searched the codebase but couldn't find the relevant section to modify & raise a PR.

**Screenshots**
![Screenshot 2023-10-18 at 09 27 54](https://github.com/mysociety/fixmystreet/assets/34215814/ea076181-ab0f-4ab7-8aac-d31f1cbfa6f1)

**Comment by dracos** [comment]
Thanks for spotting :)
