### ISSUE TITLE
Repeat headings on All Reports page or make them static/sticky/frozen

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/fixmystreet#50]

**Comment by zarino** [comment]
I recently wrote a little plugin that does this (floating table headers) on EveryPolitician.org – https://github.com/mysociety/popolo-viewer-sinatra/blob/5150ba73601018bad2f0a072e16b13df1711bc81/public/javascript/main.js#L3-L72

I wonder whether we could reuse that code directly? It *should* be simply a case of calling:

```javascript
$('.nicetable thead').fixedThead();
```
