### ISSUE TITLE
Publish OpenAPI schema for our Open311 extensions

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#5016]
We publish a wiki page outlining our extensions to the Open311 spec: https://github.com/mysociety/fixmystreet/wiki/Open311-FMS---Complete-Spec

It might be nice to capture those in an OpenAPI schema - perhaps building on top of https://github.com/open311/schema-validation/blob/master/schema/georeport-v2/swagger.json

**Comment by davea** [comment]
Maybe 3-4 hours for someone to get a handle on the OpenAPI spec and include our additions - it's just a YAML/JSON doc.

If we wanted to be extra helpful I suppose setting up an interactive hosted version of the spec using Swagger/ReDoc might be worthwhile, but that becomes a bigger task. Maybe another hour to investigate options and decide what to do.

**Comment by dracos** [comment]
Published at https://pages.mysociety.org/fixmystreet.com/open311-openapi/ can be edited in fixmystreet.com repo.
