### ISSUE TITLE
User-reported bug in Chrome

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#510]
Not sure if this is related to #388.

"I tried to report a problem using Oxfordshire County Council's
instance of FixMyStreet at http://fixmystreet.oxfordshire.gov.uk/

I wanted to report it using my phone but found a slight problem. After
placing the pin on the map, I was asked at the top of the screen
"RIGHT PLACE?" but saw no way to confirm it. This was in Chrome
version 28 on an iPhone 5; switching to Safari, I saw that there was a
strip at the bottom of the screen, below the map, where I could
confirm the location. This doesn't seem to be visible in Chrome, so I
couldn't progress any further with the report."

**Comment by abimysoc** [comment]
The ticket is nearly 3 years old, Chrome has moved on considerably, and I can't replicate this in version 49.0, so I'm going to take the plunge and close this.
