### ISSUE TITLE
user comment: It's not obvious that we include user email address with anonymous reports

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#524]
"I was disturbed to receive a reply to a recent anonymous post. If I had wanted the Council to know who made the report, I would have contacted them myself."

Looking at the 'reporting a problem' page, it is not that obvious that we include the user's email address with reports, and that they can expect a response from the council.

Could one of the small info boxes pop up when the user clicks on the email field? Wording could be something like:

"Your email address will be sent to the council with your report, so they can contact you directly with any further questions or to update you on progress".

While we're at it, unclicking the 'show my name publicly' checkbox could trigger an info box that says:

"Your name will not be displayed on FixMyStreet. However, we will send your name and email address to the council so that they can respond to your report".

**Comment by abimysoc** [comment]
New reporting form makes this much more obvious, I think (in so far as you can rely on people reading the words, anyway :) ).
