### ISSUE TITLE
Improve design of email confirmation page

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/fixmystreet#577]
Looks a bit lopsided on a desktop.

Context: People see this page a lot, when they submit a report and ask for email confirmation (instead of supplying a password).

![screen shot 2015-09-01 at 15 31 05](https://cloud.githubusercontent.com/assets/739624/9606994/7a9e6f90-50be-11e5-99dc-e6d6e1285a43.png)

**Comment by zarino** [comment]
Same for the main login page too:

![screen shot 2015-09-01 at 15 31 50](https://cloud.githubusercontent.com/assets/739624/9607012/9a636e0c-50be-11e5-8177-b091c656981c.png)

**Comment by dracos** [comment]
Interestingly, the page with this message when reporting a problem is a bit nicer – wider and doesn't overlap at bottom. It's only the /auth flow that looks specifically like that. Have added easier way to see the report confirmation page and auth confirmation page on the branch for #1209.

**Comment by zarino** [comment]
Ok, so there are roughly four pages we're interested in here:

- /templates/web/base/email_sent.html
    - `http://fixmystreet.127.0.0.1.xip.io:3000/report/new/_test_?email_type=problem`
    - `http://fixmystreet.127.0.0.1.xip.io:3000/report/new/_test_?email_type=update`
    - `http://fixmystreet.127.0.0.1.xip.io:3000/report/new/_test_?email_type=alert`
- /templates/web/base/auth/token.html
    - `http://fixmystreet.127.0.0.1.xip.io:3000/auth/_test_`

Here's how they look as of 13bb31d073c858821e1713248ae4d6595170dfa2, simply reusing the existing "confirmation page" styling we use everywhere else, just with a new "check your email" type of icon:

![screen shot 2015-09-15 at 12 38 36](https://cloud.githubusercontent.com/assets/739624/9875543/bb373d1e-5ba6-11e5-9172-bdd4b805e6f2.png)

![screen shot 2015-09-15 at 12 31 57](https://cloud.githubusercontent.com/assets/739624/9875544/bd66bd8a-5ba6-11e5-91d3-9eb978dc3bb1.png)

![screen shot 2015-09-15 at 12 38 45](https://cloud.githubusercontent.com/assets/739624/9875547/c0d8b46e-5ba6-11e5-80c8-c50a4771bdc7.png)

![screen shot 2015-09-15 at 12 31 59](https://cloud.githubusercontent.com/assets/739624/9875549/c4882662-5ba6-11e5-8f65-73d68563192a.png)

There's quite a lot of text there!

So we either shorten it to the stuff we *know* people don't already understand, or I can work out some nicer way of displaying the finer details as secondary information (a bit like we display the mobile app and goodies page as cross-sells in a row at the bottom of the other confirmation pages).

@MyfanwyNixon do you think we could shorten the text without causing upset?

**Comment by MyfanwyNixon** [comment]
OK, I think this could be shortened to:

*Nearly done! Now check your email*
Click the link in our confirmation email to [confirm your problem/confirm your update/activate your alert/activate your account].

Can’t find our email? Check your spam folder -- that’s the solution 99% of the time.
