### ISSUE TITLE
Search in admin reports within a body

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#578]
If you click 'list of all reported problems' from within a Body's page in Admin, at the moment you get taken to the live site.

Which is ok, but it'd be handy to stay in Admin, and be able to search the reports within that body.

I know I can search for the name of the body AND the key phrase I'm looking for, but this is a small issue that'd make life a wee bit easier.

**Comment by abimysoc** [comment]
To add a +1 to this: an admin-interface list of the most recent reports sent to a body (or contact, see #1466), sorted by time sent, is a thing I find myself wanting at least once a week.

**Comment by abimysoc** [comment]
(Just having a list would enable searching within it to some degree via browser search; that wasn't obvious from my last comment.)

**Comment by davea** [comment]
Searching using the cobrand admin limits to reports sent to that cobrand.
