### ISSUE TITLE
User feedback: states other than 'fixed', 'not fixed' and 'don't know'.

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#588]
" Just completed your questionnaire about a problem I'd
     reported.  It was only half fixed, but the questionnaire only
     asks yes, no and don't know.  Can you change it to reflect if a
     problem hasn't been completely resolved? "

**Comment by dracos** [comment]
Unlikely this will happen (they could say either and leave explanation). Will link to #285 in terms of other states being available.
