### ISSUE TITLE
Update text on "not fixed" page to emphasise we're not the council

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#591]
Some users take offence at the message we display when they come back to mark their problem has not been fixed, (ie the crosslinks to Pledgebank and WTT). For example:

"Checking back & telling me to contact the councillors or get some local people together to do something is a joke. You are not fixing my street at all, just becoming another layer of beaucracy."

I think this arises because it's another point where they may be mistaking us for the council - the situation might be circumvented by the addition of a reminder within the text (on the web page or in the reminder email) along the lines of 'FixMyStreet is an independent website which helps people to contact councils all over the UK.'

We might also want to give them a path via which to chase their report, eg a 're-send' button, although I can see this could be contentious.

**Comment by dracos** [comment]
Text broadly matches this
