### ISSUE TITLE
User suggestion: capture tracking numbers

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#611]
"There is possibly something that you can do.  [My direct, ie not FMS] enquiry produced an immediate response with their help desk tracking number. You could try to capture that and add it to your problem record.  I imagine a table driver approach would allow the same code to be shared across most councils, with only regular expressions, etc., changing.

[..] the current result is that one is not able to modify their record before a human looks at it and replies to the email address contained in the body of the message".

This user is suggesting that if we captured tracking numbers, users could amend their reports [qf comment 4 on #358, same user]. I suppose he means that updates on the report could be sent to the council with the tracking number attached.

**Comment by davea** [comment]
Users can add the tracking number in an update if needed. Plus we have lots of integrations which handles this automatically.
