### ISSUE TITLE
Add a set OpenGraph Image to stop Facebook picking unsuitable images

### ISSUE THREAD

**Issue by Jedidiah** [mysociety/fixmystreet#613]
Image:
![fms_square2-og_image](https://f.cloud.github.com/assets/113929/1581501/abbc2438-51d7-11e3-8338-060c24191bc0.png)

Meta tags for &lt;head&gt;

``` html
<meta property="og:image"            content="**URL_FOR_IMG**/fms-og_image.png">
<meta property="og:image:secure_url" content="**URL_FOR_HTTPS_IMG**/fms-og_image.png">
<meta property="og:image:type"       content="image/png">
<meta property="og:image:width"      content="500">
<meta property="og:image:height"     content="500">
```

OpenGraph Documentation at:
https://developers.facebook.com/docs/opengraph/property-types/#image

**Comment by wrightmartin** [comment]
I don't think this is a design ticket - however we will do a new default image design
