### ISSUE TITLE
User suggestion - allow users to edit or delete posts within a short time after submission.

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#645]
"I am surprised that there is not an option for amending or deleting posts, even if only within a set time-frame"

**Comment by abimysoc** [comment]
Kickstarter's "Response submitted! Need to fix a typo? Edit (for another: 10 minutes)" (where "Edit" is the link for editing) is nice.

**Comment by abimysoc** [comment]
User comment:
> It would be great to be able to edit a post to correct typos, or to add photos later.
