### ISSUE TITLE
Allow users to make their reports anonymous, post-submission

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#658]
Alternative to  #374 - allow users to change the anonymous state after making a report

**Comment by Gemmamysoc** [comment]
User feedback:

"To be honest, it would be helpful if anyone who entered a report was able to change this sort of thing. Occasionally I would also like to amend the text as once published typos become very evident!"

**Comment by zarino** [comment]
Makes sense that the option to remove your name should be located near to where your name is displayed on the public report page. That way, users can act immediately upon seeing their name (erroneously) published. Something super simple like this might even do:

![screen shot 2016-10-13 at 10 35 43](https://cloud.githubusercontent.com/assets/739624/19344090/d13ff536-9130-11e6-9665-3d9a7411aa16.png)

We can obviously display this if we know the report is yours (ie: you’re logged in with the email address that was used to make the report). However – I wonder whether users will typically be logged in like this, or whether we need to display the action for *all* users, on the off-chance that they’re the report owner and want their name removed?

Feels like it’s important that we explain how their name has *already* been sent to the council, and could potentially have been indexed by search engines. We could display this in a confirmation box that folds out when you click the first link:

![screen shot 2016-10-13 at 10 47 40](https://cloud.githubusercontent.com/assets/739624/19344547/7d8ceb9a-9132-11e6-891d-884fb4663232.png)

Thoughts @MyfanwyNixon @Gemmamysoc @wrightmartin.

**Comment by MyfanwyNixon** [comment]
This is all good thinking - just one point: "this page may have already been indexed and cached by search engines" could be worrying to the sort of person who would need to be told that - it doesn't include the other crucial piece of information which is that eventually it should drop off. 

I think it's better just to omitthat sentence, since the number of people who write back to say the page is still in the search results is pretty small (if nothing's changed since my days on FMS user support - NB @abimysoc does it now). 

Another option might be to put it in the 'success' screen (reworded as 'it may take a few days for this change to be noticed by search engines' or similar), but on balance I think it's best not to mention it.

**Comment by zarino** [comment]
If we wanted to *really* worry them, we could remind them that their name has already been emailed out to however many FixMyStreet users are subscribed to email alerts for reports in that area! ;-)

**Comment by MyfanwyNixon** [comment]
Ha ha yes perhaps not.

**Comment by dracos** [comment]
Was just writing what @MyfanwyNixon said.

The logged in nature was something I wondered about too, though if they've recently made the report, they probably will be logged in. I was perhaps considering it an option on Your Account page by each report, in some way. With a FAQ saying you can anonymise yourself from Your Account page; but it could just as easily say go to Your Account then view a report you wish to anonymise yourself on. However, in most cases, is it probably not the case that they want to anonymise all their reports? It seems more likely from the support I have seen at least, in which case a single option on Your Account would be easier (but perhaps allow toggling per report too).

**Comment by dracos** [comment]
PS I don't think names are included in email alerts, unless I've remembered wrong.

**Comment by zarino** [comment]
> PS I don't think names are included in email alerts, unless I've remembered wrong.

Oh! You’re right! \o/

**Comment by abimysoc** [comment]
Probably important wording clarity nitpick: we are not removing their name from the report, we're removing it from public display on the internet. As well as saying that the name has been sent to the council, we should point out that we're going to retain the name in our database associated with the report (copywriter! improve this!).

On search engines - a few people request anonymisation after Googling themselves but my impression is that this is the minority of such requests. With most people they've posted a report, realised they forgot to untick that box, and then contact support more or less immediately.

**Comment by MyfanwyNixon** [comment]
> copywriter! improve this!

I would just change "We can remove your name from this report" to "We can remove your name from this page".  Yes, it's retained in our database but again this is giving them more information than they really need (and likely to worry them, thus generating more user support) since we're unlikely to ever do anything with it. Those details are in the privacy policy I assume anyway.

**Comment by abimysoc** [comment]
Ooh, also, let's not forget about updates. It's not just reports that people might want their name removed from.

**Comment by zarino** [comment]
> Probably important wording clarity nitpick: we are not removing their name from the report, we're removing it from public display on the internet.

Maybe we should talk about "Hiding" rather than "Removing" the name? Better implies the idea that the name is still there, just invisible.

Link could read:

    (Hide your name?)

Message could read:

    Your report—including your name—has already been sent to
    Liverpool City Council, but we can hide it on this page:

    [Hide my name on this report]

    Alternatively, we can hide your name on *all* of your reports:

    [Hide on all reports]

We probably won’t need a message like this for Updates – since they’re not sent to the council. (Or are they, in the brave new world of FMS For Councils?)

**Comment by zarino** [comment]
There’s a work in progress pull request over here, with screenshots: https://github.com/mysociety/fixmystreet/pull/1554
