### ISSUE TITLE
switch off questionnaires via config setting, rather than in the Perl

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#663]
Currently to switch off questionnaires, you need to create a Cobrand module and set `send_questionnaires()` to return 0.

This seems like something that could be controlled by config perhaps, so a Perl module wouldn't be necessary just to suppress it.

**Comment by dracos** [comment]
Needs to be in code too (for some council cobrands not wanting them, for example). Could also read config variable, but I think it's probably okay as is.
