### ISSUE TITLE
throw up a modal dialogue inviting alert subscription on a newly created problem report

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#666]
related to #665 -- so sometimes there's no confirmation page (e.g. you're logged in already) -- be bold and throw a modal up on page load when a page of a just-created-by-previous-page problem report is displayed.

If so, this presumably would be instead of #665 because that would be a bit much.

Note this is quite "aggressive" behaviour but let's see how it goes.

**Comment by dracos** [comment]
There is a confirmation page always now.
