### ISSUE TITLE
User bug report - Gimp photos not accepted

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#697]
"I keep finding that when I enhance an image with GIMP, it gets silently ignored by FMS.  As one only gets one chance to get an image to the council, that is awkward.

Often, some minor tweaking, or reloading and re-saving the image gets the image to take, but I haven't worked out anything that is 100% reliable.

The example image is of a faulty street light.  I enhanced it by adjusting the colour levels, to correct for under exposure, and drawing a ring around the dark lamps.  The unretouched image loaded OK ".

NB GIMP may be a red herring: other users have complained about photos not uploading but have not mentioned any photo editing.

**Comment by dracos** [comment]
Not replicated.
