### ISSUE TITLE
User request: alphabeticisaton of bodies - way to circumvent 'city of' etc

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#699]
"I see several cities are alphabetised under the style "City of" and there might be historical or legal reasons for this but we wouldn't be wasting our time if there was an explanation or  search redirects or simply standardisation to the common, informal placenames: London, Greater, London, City of, Edinburgh, City of, etc. "

**Comment by dracos** [comment]
Done, with redirects for old City of URLs.
