### ISSUE TITLE
Report road-related issues on Highways Agency managed roads to the Highways Agency

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet#736]
<a href="http://www.dracos.co.uk/temp/scrshot-2014.03.28-22:12:10.png"><img hspace=10 align="right" src="http://www.dracos.co.uk/temp/scrshot-2014.03.28-22:12:10.png" alt="Bit of the M61" style="max-width:100%;" width=400></a>

(This is one particular body that is mentioned in #16)

A few people have written over the years asking about FixMyStreet sending reports about Highways Agency managed roads to the Highways Agency rather than the council covering the point. 

[This WhatDoTheyKnow request](https://www.whatdotheyknow.com/request/highways_agency_managed_roads?unfold=1) contains a shapefile of Highways Agency roads.

The dataset is all line strings (so no width), so I guess you might have to do something when the map is clicked and then perhaps add a road choice to the category (or separately) if there's one nearby. Or just make an assumption if it's a road category  and close enough to a line.

**Comment by Gemmamysoc** [comment]
User feedback: 

"I made a report through fixmystreet.com about potholes
on the A11. The report was forwarded to Suffolk County Council by
fixmystreet. Suffolk County Council have replied to me saying that
they are not responsible for the road; they say it is 'maintained by
the Highways Agency and you will therefore need to contact them
directly with your concern'.  You may wish to know this for future
reports received on that road."

**Comment by abimysoc** [comment]
"Currently the main A roads - A83, A84, A85 etc are managed by a
private company - BEAR Scotland. The minor roads, eg A827 are
managed by the local council.

When I report an issue on the A83/A84/A85 the local council are
notified instad of BEAR, which means the website isn't much use for
my area."

**Comment by Gemmamysoc** [comment]
Email from Calderdale council:

A fault with a light on the M62 falls under the Highways Agency England for the motorway, it is nothing to do with Calderdale Council.

You can contact them on their website http://www.highways.gov.uk/our-road-network/our-network/key-roads/m62/

Please can you redirect this request to them and update the Fix My Street App to allow future requests to go straight to them.

**Comment by abimysoc** [comment]
User: "Can you send trunk roads enquiries to the Highways Authority, not Local Authority?"

**Comment by Gemmamysoc** [comment]
Message from council to user:

"Thank you for your report.  I have attempted to log the issue on your behalf using our website, however the road in question does not appear to be maintained by Devon County Council and is the responsibility of Highways England. I have copied them into this email so they can be made aware of the issue.  I have also copied in Fix My Street so they can amend their records accordingly."

**Comment by Gemmamysoc** [comment]
Message from user:

"Hello, I have discovered today that reports on the A120 in Essex are
going to the wrong agency. They are going to Essex County Council
when this road is actually managed by Highways England. Essex
Council will not re-direct them. "

**Comment by Gemmamysoc** [comment]
User feedback:

"When I locate a pin on a Motorway such as the M62, M621, ECT, ECT,
ECT it sends the problem report to the local council well actually
Motorways and motorway slip roads and dull carriageways are NOT
managed by the local council so wouldn't it be better to send the
reports to the correct authority, Highways Agency manandged and
maintain the Motorways, Now known as Highways England, Same Company
just changed its name to Highways England so now can you trash the
local authorities on Motorways and now change it to Highways
England, The email address for them is below"

**Comment by Gemmamysoc** [comment]
User feedback:

"please note that Island Roads now deal with maintenance (under PFI
contract ) and not Isle of Wight Council"

**Comment by Gemmamysoc** [comment]
User feedback:

"It seems reports are sent to County & District Councils but what
about roads maintained by the Highways Agency ?  I have submitted a
report about the A38 trunk road but will they receive it - do
Councils forward such items or is the Highways Agency, like some
other Govt depts in this day and age, able to ignore it, until a
planned episode of resurfacing or vegetation/litter  clearance takes
place. Would like to know  - appreciate that it may not be possible
to add them as a message recipient as mapping cannot indicate
responsibility and many people may not know with whom the
maintenance resonsibility lies."

**Comment by abimysoc** [comment]
Today we had a user support email about Transport NI roads.

**Comment by abimysoc** [comment]
Today's mailbox brings an email about motorways / Highways England from a user, and an email about TFL roads from a council employee.

**Comment by davea** [comment]
Another user message today in response to the newsletter:

> Regarding the update on Red Routes in FixMyStreet - I would like to see
reports about trunk roads to go to Highways England. It can be hard to tell
who is responsible for a particular A road, as the Ordnance Survey colours
some County roads with the same colour as Highways England roads.
