### ISSUE TITLE
Update FAQs for FixMyStreet

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#753]
The copy is here: https://docs.google.com/a/mysociety.org/document/d/1oQuv3yyk90HBuMEUb5KnH836Oz2sYneb1b6Aq6SQ-0Q/edit

Martin suggests that an accordian design might be one way of addressing the length.

These FAQs represent an attempt to address the most common user support questions.

**Comment by Gemmamysoc** [comment]
Is it possible to change the wording slightly under the 'What shouldn't I report?' section on the FMS FAQ page to this: 'For problems that might put people in immediate danger, like gas leaks or falling trees, please contact your council or the appropriate utility company or emergency service directly – by phone if possible.'

**Comment by dracos** [comment]
Done.

**Comment by Gemmamysoc** [comment]
Please could we add these 'House rules' to the FAQ page at the bottom of the 'What shouldn't I report?' section: https://docs.google.com/document/d/1RzSKmtNldxdcWNKsGEALrnxnQLAxMmqCyAkluwKlDYA/edit ? This will help guide people about how we expect the site to be used.

**Comment by dracos** [comment]
Closing, as this ticket was about updating the FAQ with the content given in the ticket; reopening of a ticket is for when the intent of that ticket has not been done, new things that happen to be on the same topic should be a new ticket. Have opened one :)
