### ISSUE TITLE
tidy the UK-specific code in Open311 send-reports

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#768]
Could things like 
https://github.com/mysociety/fixmystreet/blob/master/perllib/FixMyStreet/SendReport/Open311.pm#L35
be something that could live in the Cobrand module, for example (as a method that Open311 could expect to call, perhaps)?

At the very least we ought to make these conditional on the cobrands rather than the body IDs I think.

**Comment by dracos** [comment]
This was done in 8b43050c549bc3bb233bab2b7bd5652dfbb39a12
