### ISSUE TITLE
Tweet at a council when an appropriate report is submitted

### ISSUE THREAD

**Issue by paullenz** [mysociety/fixmystreet#770]
When a report, for, e.g. Lambeth, is submitted, have the FMS twitter account (or similar) tweet at https://twitter.com/lambeth_council to let them know and include a link to the problem

Related to this - run an RCT to see if tweeting in this manner  increases the fix rate

**Comment by dracos** [comment]
X (Twitter as was) does not have a usable API any longer, and is not a service with which we wish to associate.
