### ISSUE TITLE
A/B test app cross-sell on success page 

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/fixmystreet#773]
The page people currently see after submitting a report is a bit… meh.

![screen shot 2014-07-09 at 15 59 21](https://cloud.githubusercontent.com/assets/739624/3526159/b11f27ba-0779-11e4-97e4-cad11db59109.png)

We want to improve this page, so people are reassured that their complaint is being handled, and also, so that they're made blatantly aware of the apps we offer (because they're awesome!)

It would be interesting to see how much of an impact this has on app downloads, using an A/B test – although we could probably just get away with making a note in Google Analytics and comparing the app download figures either side of that date.

**Comment by zarino** [comment]
If https://github.com/mysociety/fixmystreet/issues/972 gets done, then this ticket (which I thought was closed ages ago) will probably become obsolete.
