### ISSUE TITLE
Review London ReportIt category overrides

### ISSUE THREAD

**Issue by osfameron** [mysociety/fixmystreet#777]
See https://github.com/mysociety/fixmystreet/pull/776 -- a seemingly simple piece of work "change send method to email" required cobrand exceptions in `FixMyStreet/App/Controller/Report/New.pm` to make it happen.

To avoid the confusion and cobrand-related exceptions that aren't nicely encapsulated in `Cobrand/`, we could possibly do something along lines of:

 * override the categories by send_method=London, rather than mapit_type=LBO
 * as most LBO locations will want that, update the default sender (in FixMyStreet/DB/ResultSet/Problem.pm I think) to default to London if appropriate (currently always defaults to Email)

Does that sound vaguely plausible?

**Comment by dracos** [comment]
Code no longer exists.
