### ISSUE TITLE
How can we change the "create new report" process to improve over-all report completion levels?

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/fixmystreet#785]
Eg: User testing shows a couple of people who get lost in looking at old reports instead of succeeding in making a new one. An A/B test on hiding/showing the existing reports list would show whether this was a common problem, or just an accident of user tests.

Are there other things we can improve at the top of the reporting funnel? (ie: load homepage – find location – place marker on map)

**Comment by dracos** [comment]
Closing as undecided. Will see if #1350 (and follow-on #1351) do anything, and perhaps look at #525/#724.
