### ISSUE TITLE
User thought pins showed search results

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#794]
"I put our postcode [...]  but the area shown is some distance away and totally
irrelevant."
Subsequently, asked for clarification:
"The markers displayed are either side of [street name], which is not where we live, [our street] is half  a mile to the right on the map"

I guess this kind of confusion arises from familiarity with Google Maps, which displays several pins in response to search terms.

**Comment by dracos** [comment]
Think highlighting and changes since put paid to this
