### ISSUE TITLE
Reports page stats are confusing

### ISSUE THREAD

**Issue by garethrees** [mysociety/fixmystreet#797]
http://www.fixmystreet.com/reports

Not entirely clear which issues are open and which are resolved.

User has to work out totals themselves:

```
Open = (New problems + Older problems + Old unknown problems)
Resolved = (Recently fixed + Older fixed)
Total = Open + Resolved
```

Would be nice to make these available on the [council page](http://www.fixmystreet.com/reports/Cardiff) so that you can link someone to the stats for the particular council.

**Comment by dracos** [comment]
Page changed now
