### ISSUE TITLE
Allow multiple photos to be included in reports

### ISSUE THREAD

**Issue by struan** [mysociety/fixmystreet#825]
Some people would find it handy, e.g https://www.fixmystreet.com/report/499197

**Comment by Gemmamysoc** [comment]
User feedback:  

"...it would also be helpful to be able to upload more than 1 photo of a pothole (for example). One photo can be of the pothole, and another a broader location photo…"

**Comment by osfameron** [comment]
Some of the backend work for such a feature will be coming in shortly via
Zurich's https://github.com/mysociety/FixMyStreet-Commercial/issues/664

(No nice UI for an uploader as yet though)

Hakim
-- 
*Developer*, mySociety Services
http://www.mysociety.co.uk

**Comment by Gemmamysoc** [comment]
User feedback:

"I wanted to send 2 photos at the time of writing to make finding the location easier.  Is there any way you can add another "choose file" button so we can send more than 1 image per report? "

**Comment by dracos** [comment]
The ability to add up to three photos is now present and running in the backend code. This needs adding to the front end – very basically with multiple choose file buttons as suggested above would at least fix this ticket, and/or at last doing #190 and providing a nicer modern photo uploader tool.

**Comment by dracos** [comment]
#190 has been done.
