### ISSUE TITLE
User suggestion: When marking report as 'fixed' don't make 'update' box mandatory field

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/fixmystreet#844]
"When I mark a report as fixed, the comments field is mandatory. Most
times I am just marking it as fixed so don't have a comment. Please
can you make the comment field not mandatory when marking a comment
as fixed."

**Comment by Gemmamysoc** [comment]
Similar user feedback:

"I have a lot of old reports that have been fixed. Whenever I go to
fix them though, it takes forever, and I give up and leave them.
Firstly I have to go to my reports, find the relevant one, then
click on details, then click fixed, then I am forced to put a
comment in (unnecessary) and finally I can mark it as fixed.

It would be a lot simpler if there was a page/list of my reports,
where I could review and close them with one click."

**Comment by dracos** [comment]
I don't think mandating something here is too arduous. We do want to slightly discourage complete drive-by closings.
