### ISSUE TITLE
Bromley geocoding issues

### ISSUE THREAD

**Issue by osfameron** [mysociety/fixmystreet#850]
"We’ve been alerted by customers of a few roads in LBB which are not recognised when used as a search term when reporting on FMS:
 
·        Leith Hill; which runs from Mickleham Road to Breakspears Drive (although it does pick up when entered as Leith Hill BR5)

 
·        Kelsey Road; which runs from Broomwood Road to Pleasance Road (although again it does pick up when entered as Kelsey Road BR5)

 
·        There has also been a road name change for a section of Ramsden Road (BR5) between Church Hill and Court Road has changed to ‘Old Priory Avenue’ – presently entering Old Priory Avenue simply takes the user to a different Priory Avenue in Petts Wood"

**Comment by MyfanwyNixon** [comment]
Judging by this user email, this may still be an issue: "How can I report rubbish dumped in Rookery Lane, Bromley when your useless website tells me "Sorry, we could not find that location"

**Comment by dracos** [comment]
"Rookery Lane" works on fix.bromley.gov.uk and "Rookery Lane, Bromley" works on www.fixmystreet.com.
