### ISSUE TITLE
Fix creation of (UK?) bodies from admin interface to use MapIt IDs

### ISSUE THREAD

**Issue by osfameron** [mysociety/fixmystreet#857]
e.g. on my dev instance, if I try from /admin/bodies to create a body "Wyre Forest District Council", I get an error about duplicate ID=2.

Even if the body was created correctly, it would have id=2, whereas I really want it to have ID 2475, e.g. as per http://mapit.mysociety.org/area/2475.html  (it seems to be a UK-specific requirement for the ID to be same as area_id, as this is hardcoded in various cobrand etc. business logic).

CC @davea and @dracos / @struan for comments if I'm confused/wrong.

See also #856 which could alleviate the need to do that for a lot of development cases.

**Comment by dracos** [comment]
UK-specific requirement for ID==area_id removed in e57cbf483790bedfef6496be3c7ffa42882c3ffc
