### ISSUE TITLE
Set up MakeMyIsland site on production server

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet#863]
Acc. Ian "site up on mastodon, database on buffalo" please

Matthew's staging site: http://makemyisland.fixmystreet.dev.mysociety.org/

**Comment by dracos** [comment]
This was all presumably done. Note for future that I think for a "go into production" or other overarching ticket such as this, it is preferable to use it to link to other tickets which can then have their own progress, rather than multiple updates with new requirements.
