### ISSUE TITLE
Vagrant - sync the fixmystreet folder to /vagrant instead of ~

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#864]
Currently the Vagrantfile sets things up to put the checked out repo folder into the vagrant user's home dir. This works fine, but it means you can't see/access other things that it creates from your host machine (like the `cache` or `data` folders that get created in the parent dir) without syncing the whole home folder. Would it be possible to change it so that the site folder ends up in `/vagrant` instead?

It's made more confusing because (for me at least) Vagrant automatically syncs the project folder to `/vagrant` anyway, so I end up with the code in two places, but only one of them works (the version in `~`). The version in `/vagrant` doesn't let me run the `bin` scripts for example.

**Comment by davea** [comment]
We've recently made some vast improvements to the Vagrantfile which should have sorted this.
