### ISSUE TITLE
creating new report: don't show existing problems until category is known

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#871]
When creating a new problem (i.e., about to click on the map to position the pin), don't show existing pins... until the category is known, at which point, show pins with the same category. This could still catch the majority of "duplicate problem" reports (since the categories ought to match) but would solve the problem we've observed of users getting lost when accidentally/unwittingly clicking into such a pin's details page, or general pin-density #525 (and on the app: https://github.com/mysociety/fixmystreet-mobile/issues/175 ).

Needs testing, especially considering:

* how would post-category choice processing work without JS (an extra step, on placement, that shows the nearby problems
* possibly easy to miss a pin appearing on the map when attention is on the drop-down that has just been selected (interrupting dialogue if revealed problem looks very close?)

[NB I thought this issue had been raised but if so I can't find it... (was discussed at team meeting in Birmingham 30-Jul-14) ]

**Comment by dracos** [comment]
Not doing this any time soon.
