### ISSUE TITLE
Creation of problem reports from body to FixMyStreet

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#874]
We would like to allow for something like the following use case:
1. A citizen calls a municipality and reports a problem
2. The municipality employee creates an issue in their issue tracking system
3. The problem is submitted onto FixMyStreet, and is immediately visible there

Perhaps the best way to build this integration between the issue tracking system and FixMyStreet would be to allow for Open311 client polling for FixMyStreet (or, in the other direction, adding support for FixMyStreet's Open311 server to receive "create problem" requests). (I guess that this would require an API key for the municipality in question. I also guess that the e-mail address in the problem report would be one of the municipality (perhaps a no-reply address).)

Does this feature make sense for FixMyStreet?

How difficult would this be to implement?

(A related problem is that we want to be able to import a lot of old problem reports from a municipality to be displayed on FixMyStreet.)

**Comment by davea** [comment]
We now have a `fetch-reports` script which does this.
