### ISSUE TITLE
Make photos directory hierarchical

### ISSUE THREAD

**Issue by Flupsy** [mysociety/fixmystreet#879]
FMS's photos directory now had over 50k files in it, and our backup utility (duplicity) is starting to get very upset at the effort required to do an incremental backup.  Duplicity jobs for this directory frequently allocate 13GB memory on leopard and ocelot.

Could this directory be made hierarchical?

**Comment by dracos** [comment]
I think the reason duplicity is getting upset at the effort required is not that it isn't hierarchical, but that it is dealing with the files in a random order each day. The backups aren't very incremental.

**Comment by dracos** [comment]
Backup now direct rsync, c. 1 minute instead of 3.5 hours. Incremental backup now c. 150MB, not 40GB.
