### ISSUE TITLE
Street name not recognised without entering town/city

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/fixmystreet#894]
User feedback:

"On homepage, entering 'Great Ormond Street' brings up a 'Sorry, we could not find that location.' error message. However, when inputting 'Oxford Street', it brings up the London street.

'Great Ormond Street, London' brings up the right location.

Why does city need to be entered for some streets and not others? Seems arbitrary."

**Comment by dracos** [comment]
At the mercy of the geocoder, not much we can do about it.
