### ISSUE TITLE
Cannot leave pin on Nexus 4

### ISSUE THREAD

**Issue by owenblacker** [mysociety/fixmystreet#911]
I'm running Android 4.4.4 on my Nexus 4 handset and it won't let me drop a pin onto the map after going to report an issue (either by locating me automatically or by entering the postcode, either logged in or not).

SupportDetails.com tells me I'm using Chrome 38.0.2125.102 and I'm happy to demo this to someone at next week's retreat ;-)

**Comment by owenblacker** [comment]
Not that I'm aware, no. I did try stabbing quite hard. Taking another look, it does indeed appear just to be that I need to stab really hard and avoid it thinking I'm dragging. Fair enough…

**Comment by owenblacker** [comment]
Well, it worked that one time, but I can't get it to work since. It's effectively unusable for me, I'm afraid

**Comment by stevenday** [comment]
Just FYI, the same thing happens for me too - Nexus 4, Android 5.1.1, Mobile Chrome 43. I can't get a tap to register after a good 25 attempts and stabbing hard enough to worry about crushing the phone :(

**Comment by stevenday** [comment]
Just to continue this, I had another go on my nexus 4, and a samsung galaxy tablet (also android chrome) yesterday whilst attempting to show someone FMS, in the end we had to resort to a laptop as neither would register a click.

**Comment by dracos** [comment]
:( still works fine on my Fairphone 2, Chrome 48. Not sure what could be going on :-/

**Comment by dracos** [comment]
Okay, I've hopefully at last found and changed something that might help with this!

**Comment by dracos** [comment]
Hopefully fixed by 5154fa740d3eca75534bd1be7a40f07342419fb7

**Comment by stevenday** [comment]
This is fixed for me - thanks!
