### ISSUE TITLE
Improve cobrand javascript overriding

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#913]
Right now cobrands can override things in javascript by declaring various global functions and variables in their own javascript files, e.g. `position_map_box` and `slide_wards_down`. The main code then calls these at various points. 

As a result, most (all?) cobrand js is not encapsulated in any kind of module/[IIFE](http://benalman.com/news/2010/11/immediately-invoked-function-expression/#iife), exactly what can be/is being overridden is opaque and it's difficult to test.

It would be better if there was one global `FixMyStreet` object that cobrands could modify instead. This would have the advantage of making the interface available to override more obvious, and make modularisation of the js code easier. For example, you could do something like:

```javascript
;(function(FixMyStreet) {
    var cobrand_setting = 'something';
    var cobrand_override_function = function cobrand_override_function(some_param) {
        do_something();
    }
    FixMyStreet.setting = cobrand_setting;
    FixMyStreet.some_function = cobrand_override_function;
}());
```

You could go even further and namespace stuff inside the global object too, it depends on how much there is available to override I guess.

**Comment by dracos** [comment]
- [ ] Better overriding of `big-green-banner` for those who don't want just an h1 as it currently is.

**Comment by dracos** [comment]
JS structure much improved by #1432, enough to close this I reckon.
