### ISSUE TITLE
Consider replacing <select> lists (e.g. categories) with custom widget.

### ISSUE THREAD

**Issue by osfameron** [mysociety/fixmystreet#919]
As per Alice Bartlett's excellent talk "Burn your select tags" https://www.youtube.com/watch?v=CUkMCQR4TpY on the usability problems with <select> tags.

She suggests designing a custom widget (and that it will take far longer than expected.)

**Comment by dracos** [comment]
Just to note we have done this for the multi-selects of filtering.
