### ISSUE TITLE
Contact 150 local councillors

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#940]
Get a list of 150 local councillors names and email addresses (from a developer) and email them to say:

a) FixMyStreet is a great tool for your residents, how about putting it on your website/telling your constituents
b) You can sign up to alerts if you want to know what's happening in your ward/constituency

How to track effectiveness:
- Google Alerts *should* pick up on online mentions of FMS
- Match email addresses to alert sign-ups
- Could target councillors in one specific area of the country (and try the other initiatives in other areas) so that we see whether there's any upturn in usage from there.

If the experiment with the first 150 councillors goes well, roll it out to all/more councillors.

**Comment by dracos** [comment]
Not followed up.
