### ISSUE TITLE
Approach local radio stations 

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#945]

**Comment by MyfanwyNixon** [comment]
As a matter of interest, a local radio station has just indicated that advertising starts at £97 per week with a reach of 34K listeners.

My first thought re: advertising is that it's cheaper to get invited onto a radio show as a guest, but one has less control over the subjects discussed, the time given can be very short, and you can't be as persuasive as you might be in a targeted ad.

**Comment by paullenz** [comment]
So my experience of serious above-the-line marketing is about 12 years old
now, but back then I found that radio was the second worst use of spend
(the very worst was cinema) - to get decent  awareness you have (had) to be
on pretty heavy rotation which really racked up the costs
