### ISSUE TITLE
add favicon to fixmystreet.org (documentation)

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#955]
Currently no favicon in the documentation site (github pages, i.e., `gh-pages` branch)

**Comment by zarino** [comment]
Oddly, while I expected the FMS favicon to be the spanner out of the logo…

![spanner](https://cloud.githubusercontent.com/assets/739624/5740994/2fffd672-9c00-11e4-8b92-3412e1334a9d.png)

It's actually a marker icon…

![screen shot 2015-01-14 at 15 10 41](https://cloud.githubusercontent.com/assets/739624/5740902/9e9d892c-9bff-11e4-8a86-86178faeeaae.png)

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/fixmystreet/pull/1071
