### ISSUE TITLE
Double encoding of Open311 field

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#962]
This is an issue for FixaMinGata.

The string "Länk till ärendet" (perllib/Open311.pm:185) becomes "LÃ¤nk till Ã¤rendet" in the Open311 request.

![open311-encoding](https://cloud.githubusercontent.com/assets/777056/5304782/35cdc82c-7bf6-11e4-9a4d-2b32ad2998fc.png)

As you can see in the above graphic, the encoding of the other text is correct.

**Comment by dracos** [comment]
Closing presumed fixed; reopen if not!

**Comment by jonkri** [comment]
Hi! Sorry for the delay, but we haven't gotten around to testing this yet. We hope to do it soon, though. I'll re-open the issue if it doesn't work, like you said.

**Comment by jonkri** [comment]
I have tested it myself, and it seems to work here too. I got the following request body:

    email=...&lat=57.754022&long=12.049052&service_code=...&description=Beskrivning%3A+R%C3%A4ksm%C3%B6rg%C3%A5s%0D%0A%0D%0AL%C3%A4nk+till+%C3%A4rendet%3A+http%3A%2F%2Fbeta.fixamingata.se%2Freport%2F642%0D%0A%0D%0ASkickad+via+FixaMinGata%0D%0A&last_name=Kristensen&first_name=Jon

I have asked the people that reported the problem to try again. I'll update this issue if the problem seems to persist.

**Comment by jonkri** [comment]
We will most likely hear back about this in the next week. If the problem becomes solved, we believe that we can keep this issue closed and also close #876. I'll update you when I hear more about this.

**Comment by jonkri** [comment]
This works now. Whether it's a result of your change, or something that the developers in this company did, I'm not sure.

Thanks though!
