### ISSUE TITLE
Changes to help with councils who are refusing to accept messages

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/fixmystreet#968]
1 - Write blog post on how councils are trapped by vendors, and what they have to do to cope

1.5 - Where we've had to delete all emails for a council, improve the user experience of being told the bad news.

2 - Write delicate emails directly to the council-staffer responsible. Ask for calls.

3 - Change the FMS email footer asking them to send us bounces.

4 - Send some personal mails to actual local users, encouraging them to write to the council sending this blog post and a personal message

5 - Rejudge

6 - Either write custom form posting scripts, or provide links

---

Example postcode covered by *no* FMS bodies: https://www.fixmystreet.com/around?pc=M50+2EQ

Example postcode where some categories (eg: abandoned vehicles, dog fouling) are covered by a body not accepting FMS reports: https://www.fixmystreet.com/around?pc=DE6+2AD

**Comment by BenJam** [comment]
personally I would bring some WriteToThem action into it, encouraging the user to write to their local councillor about this issue.

**Comment by zarino** [comment]
@BenJam – there are links to WTT in both of the wireframes ("write to your councillor")

**Comment by zarino** [comment]
![image](https://cloud.githubusercontent.com/assets/739624/6347890/66e63d7e-bc13-11e4-9506-bcd58b604909.jpg)

Wireframe from today with @wrightmartin.

**Comment by zarino** [comment]
#IPADFAIL

**Comment by wrightmartin** [comment]
this.rotate(180);

**Comment by zarino** [comment]
Let's try that again:

![cropped](https://cloud.githubusercontent.com/assets/739624/6348325/6c63fa72-bc16-11e4-83d7-3153e2e495a0.jpg)

*Notable features:*

* For two-tier areas, where only certain problem categories are served by a FMS-compliant body, a message is displayed below the "Category" select box once the user selects a category that should be covered by the uncooperative council.
* For areas where we have *no* registered bodies, the message is shown as soon as they click on the map to report a problem.
* In both cases, the message explains the problem, says they can *still* use the form below but it won't be reported, and gives them a link to a page that helps them report it in other ways.
* The new page—which has a URL so it can be shared / included in emails etc—is tailored for people in that area, tells them what's going on (maybe “your council is one of only 2% in the UK…” for pressure), and has a primary CTA with a link to the council’s existing reporting page/system. Secondary CTAs for using WriteToThem, and tweeting about it (with the uncooperative council’s twitter handle included in the pre-filled tweet text).

**Comment by wrightmartin** [comment]
Here's a first cut wireframe for the page.

![fms fail](https://cloud.githubusercontent.com/assets/2292925/6348596/2a7aa1a8-bc19-11e4-9e5d-e8380121379b.png)

- Maybe a hashtag campaign (driven by an initial blog post) could help lend some social currency to this, what do you think?
- We've just put **tweet** here, as it's the easiet to explain, is there any case for Facebook as well?
- What do you think about the tone? (obviously @MyfanwyNixon hasn't even seen this yet, so it's still to go through some polish)

**Comment by MyfanwyNixon** [comment]
That is nice. Some immediate thoughts:
- Hashtag campaign is a nice idea but we'd have to be prepared for it turning sour. We can't control what our users write. (Although in truth - the more likely problem would be that it didn't get enough users).
- Facebook, I'm going to say yes. FMS is the one of all our UK projects where we get the most engagement on our FB page: people posting messages and questions, etc. I think the demographics match between the two sites.
- Tone seems right to me, with a few polishes to actual wording: eg instead of 'tweet to tell x council to start accepting', I reckon 'tweet to tell x council that you'd rather use FMS'.

**Comment by zarino** [comment]
@MyfanwyNixon – my reservation with Facebook was that we can't easily let you @-mention your council. So although your friends might see it, you're still shouting into the void. Twitter, on the other hand, seems to be a generally accepted place to bitch at corporations and government departments *and actually get a reply*.

**Comment by wrightmartin** [comment]
Here's a first go at the message in the sidebar. This appears if you select a category that's affected by your council not accepting reports

![sidebar-message](https://cloud.githubusercontent.com/assets/2292925/6348937/c03ff1f4-bc1c-11e4-972e-cb7d5b6a86a4.png)

**Comment by wrightmartin** [comment]
Thanks @MyfanwyNixon, good feedback that.

Here's an amended version, with the twitter feed removed, and improved calls to action

![fms fail](https://cloud.githubusercontent.com/assets/2292925/6349066/543b4178-bc1e-11e4-924b-0d19f383939b.png)

**Comment by wrightmartin** [comment]
^ @steiny, @dracos it would be good to hear your thoughts on the above, should've mentioned you earlier on

**Comment by MyfanwyNixon** [comment]
@Zarino, I see your point, yes - might be better to channel everything onto Twitter in that case.

**Comment by abimysoc** [comment]
Just to note there's a big difference between a council that we can't send reports to because we don't have contact details (possibly partly our fault, although often the council does not make an email address available / easy to find), and a council that has explicitly told us they won't accept reports. Possibly the UX in each case should be different.

**Comment by wrightmartin** [comment]
@abimysoc - we were working on the assumption that we didn't know the difference. But if we do that's good, and you're right, the wording/process can be different

**Comment by abimysoc** [comment]
To be clear, we (@gemmamysoc) know the difference, but I am not sure if the FMS database does. Hmm.

**Comment by wrightmartin** [comment]
Due to having no internet for some of the day today, I knocked out a design for this page

![fms-council-no-longer-accepts-message](https://cloud.githubusercontent.com/assets/2292925/6398638/de5f794c-bde4-11e4-81fa-8e50e5955ec8.png)

**Comment by Gemmamysoc** [comment]
This looks great! I imagined this showing for councils that have explicitly told us/users they don't accept FMS reports. Here is my list of these councils so far: https://docs.google.com/a/mysociety.org/document/d/1UAeawxiQugeB-AuyjvoayPduphdVzZZ_b4xZ5LXNzUE/edit

**Comment by Gemmamysoc** [comment]
The original message saying we don't have contact details for certain councils can stay the same for the councils that haven't said they don't accept our reports, right?

**Comment by wrightmartin** [comment]
@Gemmamysoc yep, that message will stay the same, and be replaced with a different one if they're on the 'naughty councils' list https://github.com/mysociety/fixmystreet/issues/968#issuecomment-75744357

**Comment by MyfanwyNixon** [comment]
Even though I've seen it in three iterations now, I've only just realised that 'post a tweet' is odd language. Surely just 'Tweet to let example council know...'? :)

**Comment by wrightmartin** [comment]
@MyfanwyNixon yeah, good spot, that's my amazing copywriting skills shining through :)

**Comment by wrightmartin** [comment]
A note to here to say this hasn't been on the design spreadsheet, I'll add it for next sprint

**Comment by Gemmamysoc** [comment]
Is this now on the design spreadsheet? Can't see it myself. What information do you need from me to implement this?

**Comment by zarino** [comment]
@Gemmamysoc – Yes, it's in there: "Implement user flow for reporting issues in councils that do not accept FixMyStreet emails"

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/fixmystreet/pull/1105

It'll need developer attention before it can be deployed. (See pull request for details.)
