### ISSUE TITLE
Link to the goodies page

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#971]
See #905: we need to provide some obvious links to the downloadables page, in places where they will be seen, but not detract from the main purpose of the site or clash with other important messages, eg app downloads and cross-sells.

MN: "Main nav would have been my first choice; but otherwise, perhaps on the homepage under the app links?
But also, as we're trying to target the very happiest people, what about a link at the points where they experience that joy: could be the report confirmation page, and the questionnaire 'yes it was fixed' confirmation page?
Plus a mention in the alerts that we send out would be good. "

GH: "How about putting link to this page on the bottom of the homepage, adding a 'Are you a community activist?' or the like, alongside the 'Are you a developer'/'Are you from a council' bits? "

MN: "Might be worth thinking a bit around what the right term should be - I'm not sure how many people think of themselves as community activists, but maybe just 'Are you a keen FMS user?' or similar?

I still think that a tab with 'goodies' or even 'shop' (even though we're not actually selling anything yet) would grab the most attention, though. People always click on 'shop', they can't help it :) (or maybe that's just me, hmmm)"

**Comment by dracos** [comment]
There's been a link for a while, bottom nav and on confirmation pages.
