### ISSUE TITLE
Google Analytics outbound click tracking for Goodies page downloads

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#973]
The Goodies page has links to .zip and .pdf files for people to download. Although the hits are probably recorded for a short time in the web server logs, it would be good to track downloads as a proper metric in Google Analytics.

Outbound click listeners on the links could easily track download requests, and record them as Google Analytics events (or even pageviews??)

**Comment by jacksonj04** [comment]
Any chance we get this sooner rather than later? Delicious data!

**Comment by zarino** [comment]
@jacksonj04 – do you have a research question in mind that this would help you answer? (Any *actual use* for this feature will give it higher priority at the next design sprint prioritisation session)

**Comment by jacksonj04** [comment]
We want to see if changes to the confirmation pages are actually driving higher downloads, preferably without resorting to log diving.

**Comment by zarino** [comment]
I've added your comments to the design spreadsheet, and set a deadline of the end of next week. I think we should be able to fit it into next week's sprint.

**Comment by zarino** [comment]
@jacksonj04 – While I'm in there, if there's any other links on FMS that you'd like to be tracked, add them to this ticket, and I'll try to install the tracking for them at the same time.

**Comment by zarino** [comment]
@jacksonj04 – This didn't get prioritised this week (26th–30th Jan) and the sprint after (2nd–6th Feb) is looking really full. If this is blocking your research, and you think you can tackle this yourself, please don't feel like you have to wait for Martin or me to do it.

In short: It should be a matter of adding some javascript click listeners to the page, and putting a location.href redirect in the google analytics callback. (I think you and I did something similar to this before, on a different mySociety site, but I can't remember which?)

If you decide to do it yourself, but get stuck, drop me a line.

**Comment by jacksonj04** [comment]
Picked this up since we may as well get this click tracking in before #1001 is merged.

**Comment by jacksonj04** [comment]
Pull request in #1010.

**Comment by zarino** [comment]
As noted in IRC conversation with @jacksonj04 – I’m not saying it’s perfect, but here’s how I did link tracking on my own blog, which caters for a few edge cases you might not immediately think of:

https://github.com/zarino/zarino.co.uk/blob/master/js/blog.js#L119-L140
