### ISSUE TITLE
Generating lists of reports per place name is expensive

### ISSUE THREAD

**Issue by Flupsy** [mysociety/fixmystreet#976]
I just blocked a Spanish address that was making rapid requests of the form `/reports/Placename?t=unknown` (and also `t=new`, `t=fixed` etc) as this was causing very high server load and essentially knocked the site over.  Can anything be done to make these requests less expensive?  Varnish wasn't helping as the requests were iterating through every place name.

**Comment by dracos** [comment]
Should we look more generally at something like `limit_conn` on the web server? http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html

**Comment by dracos** [comment]
Whoops, hit go too early. Do you have any long query logs or anything else relevant to this? I can look to see if there's an index that could be added or something.

**Comment by dracos** [comment]
Might be sped up by #1185. Don't otherwise have anything further to go on.
