### ISSUE TITLE
All reports page: Add time period explanations 

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/fixmystreet#983]
User feedback:

"I’m looking at your report page (https://www.fixmystreet.com/reports) but I don’t understand what time periods you are using to define ‘new’, ‘older’ and ‘old’."

Could we perhaps add an explanation to this page so this is more clear?

**Comment by davewhiteland** [comment]
Current meanings seem to be "New problems' are those that are 4 weeks or less old, 'Older problems' are between 4-8 weeks old and 'Old / unknown problems' are more than 8 weeks old" but this needs to be available on that page.

**Comment by Gemmamysoc** [comment]
Council user feedback:

"Hi, looking at your "all reports" page, what time-scales do the
different columns relate to. I'd like to get an idea of how many
reports you get from our residents per month, and reporting trend..."

**Comment by osfameron** [comment]
This has currently caused an internal discussion involving 5 mySociety staff.  (i.e. yes, this is worth fixing)

**Comment by davewhiteland** [comment]
NB related but different (same page) #797

**Comment by zarino** [comment]
So potentially renaming them to…?

![screen shot 2015-02-27 at 10 34 13](https://cloud.githubusercontent.com/assets/739624/6411062/93affbb4-be6c-11e4-92da-b3ecc2df7bf7.png)

Or…?

![screen shot 2015-02-27 at 10 36 58](https://cloud.githubusercontent.com/assets/739624/6411064/96de04ac-be6c-11e4-8189-de65879888f9.png)

**Comment by osfameron** [comment]
The "month" ones look so pretty, but are ambiguous (month != 4 weeks, and
raises questions about calendar month).

So 2nd option, (or 1st with a tooltip clarifiying that we really mean 2nd)

Hakim
-- 
*Developer*, mySociety Services
http://www.mysociety.co.uk

**Comment by abimysoc** [comment]
Drive-by comment to link this to more 'All reports'-page tickets #254 #50 #635 #699 #560 #178 - if there are redesigny thoughts in progress would be good to consider those as well.

**Comment by dracos** [comment]
Sorry, that's not what the page currently says, so let's get that right first before deciding how to change it :-) It's based around our knowledge of the freshness of the reports too, not just when they were reported (hence the "unknown"); old problems that we know are still extant appear in "Older", not "Old/unknown", I think that's a good feature.

New problems: Open, reported within last four weeks
Older problems: Open, not new, has had an update within the past eight weeks
Old / unknown problems: Open, not had any update in eight weeks
Recently fixed: Marked fixed/closed in past eight weeks
Older fixed: Marked fixed/closed more than eight weeks ago

The main issue I have with the page is it says "fixed" but that includes "closed" reports too. Hover tips on the header columns explaining the above would do for me. The council user could have access to a dashboard?

**Comment by osfameron** [comment]
Two more questions from that clarification:

 - What's the precise distinction between "fixed" and "closed" ?
 - What does "Open, not new"? mean (e.g. how do we define "new" ?)

Hakim
-- 
*Developer*, mySociety Services
http://www.mysociety.co.uk

**Comment by zarino** [comment]
@osfameron: I assume "Open, not new" means "Open, reported more than 4 weeks ago" (since "new" is "reported in the last four weeks").

**Comment by dracos** [comment]
"What's the precise distinction between "fixed" and "closed" ?" – fixed is one of the <a href="https://github.com/mysociety/fixmystreet/blob/master/perllib/FixMyStreet/DB/Result/Problem.pm#L195">fixed states</a>, closed is one of the <a href="https://github.com/mysociety/fixmystreet/blob/master/perllib/FixMyStreet/DB/Result/Problem.pm#L215">closed states</a>?

**Comment by Gemmamysoc** [comment]
User feedback: "Could you add an extra column with
total of all reported against all fixed - ie percentage of success
rate? I know that many will be fixed and that not reported to you -
but it may give encouragement to FixMyStreeters and to councils."

**Comment by dracos** [comment]
Have added tooltips.
