### ISSUE TITLE
Investigate possible timeout when uploading large image

### ISSUE THREAD

**Issue by osfameron** [mysociety/fixmystreet#986]
A client has emailed to say that one of their users has experienced "ERR_UNEXPECTED" (Google Chrome error) while submitting a report with a large photo (6MB).

My guess is that the image upload has timed out (possibly due to poor network connection / proxy / size of image.)

We should investigate if this is the case and there are any solutions (alternative file uploaders?) or mitigations (spotting issue and providing better error?  Advising of maximum file size supported before starting upload?  etc.)

**Comment by dracos** [comment]
This would presumably be fixed by the improvement of #190 (showing thumbnail by uploading as soon as image provided).

**Comment by dracos** [comment]
Closing as #190 is done.
