### ISSUE TITLE
Jump to a specific report

### ISSUE THREAD

**Issue by osfameron** [mysociety/fixmystreet#989]
A commercial client have asked how they can jump to a specific report, e.g. if quoted by a customer.

I've previously wanted this in /admin/reports, but I think it would be a good idea to add to /dashboard, and will add this unless any objections.

(Yes, it's "easy" to hack the URL, but that's hard to explain to less technical users.)

**Comment by dracos** [comment]
On `/admin/reports` - a search for "id:<ID>" will return that report instantly. (Without the "id:" it will still work, but will also be searching content of all reports etc. and take longer, depending on how many reports.)

Would be interested in gathering some knowledge on whether explaining changing a URL is hard to explain to less technical users, from the feedback I get on traintimes from a wide spectrum of users it seems to be quite commonly understood.

**Comment by osfameron** [comment]
Ah great, I didn't know that trick on /admin/reports (and entering just the
id took ages on the live site).  Thanks!

I managed to talk the users I spoke to yesterday through to entering
"/dashboard" on our staging site, but at least over the phone, this was
clearly beyond their comfort level.

For the more complicated idea of inputting a report id in the URL bar at
all, I got no response at all.  (Again, this was over telephone, may have
been easier in person or screen-sharing).
It's certainly received wisdom that non-geek users aren't comfortable with
this -- quick search brings up, for example,
http://www.snyderconsulting.net/article_7tricks.htm#5

On 8 January 2015 at 09:37, Matthew Somerville <notifications@github.com>
wrote:

> On /admin/reports - a search for "id:" will return that report instantly.
> (Without the "id:" it will still work, but will also be searching content
> of all reports etc. and take longer, depending on how many reports.)
>
> Would be interested in gathering some knowledge on whether explaining
> changing a URL is hard to explain to less technical users, from the
> feedback I get on traintimes from a wide spectrum of users it seems to be
> quite commonly understood.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/fixmystreet/issues/989#issuecomment-69156054>
> .
>



-- 
Hakim
mySociety Commercial Team Developer

**Comment by dracos** [comment]
The front page does this on .com with FixMyStreet ID or external ID.
