### ISSUE TITLE
Set client_max_body_size in installation script

### ISSUE THREAD

**Issue by jonkri** [mysociety/fixmystreet#995]
client_max_body_size is not set in the nginx configuration created by the installation script.

The nginx default for <code>client_max_body_size</code> is 1m, which should be quite small for FixMyStreet photos. When a picture of a large size is uploaded, a "413 Request Entry Too Large" error is produced.

Would it be desirable to explicitly set a (large enough) value for <code>client_max_body_size</code>?

Thanks!

**Comment by dracos** [comment]
Good idea, thanks! Have gone with 10Mb.
