### ISSUE TITLE
provide boilerplate texts when staff user is presented with problem report update form

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#996]
(From ESCC) Council staff who take the trouble to send manual updates on FMS will often need to send the same standard reply -- currently requires cut and paste from their staff intranet. It would be superhelpful to load a drop-down with these texts as boilerplate available for populating the update textarea (could still be edited, of course).

Various levels of complexity possible, but supposing a drop-down for populating the textarea such as:
- boilerplate strings hardcoded in the template
- boilerplate strings fetched by AJAX request populating from a JSON file provided on council site (so council can change it... note ESCC are not running off their own domain so maybe CORS issues in pulling data from another source
- strings could be mapped to problem type (so auto-select relevant entry or opt group, especially as often it looks like there often only be one anyway)

For staff on standard browser (i.e., target browser is known, e.g., ESCC use IE10) it seems like this _could_ even be an entirely front-end solution with JS in the template.

Notes:

One or two of these boilerplate replies might include links to clarification/additional info council pages. Currently I don't think we're enabling HTML in the updates, so if we want to enable that on the page that would need additional work (linkily staff updates?) (Note that if the requestor receives the update as an email notification, which is part of the dialogue here, any URLs may well be linkified by their email client, so it's not worth ruling this out of hand even if not linkified... although long un-linked URLs might be unpleasant).

@osfameron suggested we might have something very similar to this already in the Zurich cobrand admin?

**Comment by dracos** [comment]
"CORS issues" - no issue if that JSON file supported JSONP.
"Currently I don't think we're enabling HTML in the updates" - things that look like links are made into links.
"Zurich cobrand admin" - I don't think there's anything like this.

**Comment by BenJam** [comment]
There's a new request for reply templates in the Zurich cobrand admin so we might have a basis for this soon.

**Comment by dracos** [comment]
There is a whole templating interface now.
