### ISSUE TITLE
format easting/northing as E/N single string  in report email for ease of cut-and-paste

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#997]
Dynamics CRM accepts Easting/Northing as a single string with a slash delimiter, no spaces; council staff currently have to cut and paste twice to transfer location information from an incoming email notification in Dynamics (which then produces a map).

Either add it conditionally for ESCC who I saw doing this, or add it as an extra line on all default templates in case the receiving council staff are using the same Dynamics system?

**Comment by BenJam** [comment]
I think we can do this...
